bitwarden/ios

.github/workflows/scan.yml
Internal change.
Sets up SARIF output for Checkmarx scans so we can see results in GitHub and adds SonarCloud. …
=> Additional scanning

.github/workflows/scan.yml
[PM-7288](https://bitwarden.atlassian.net/browse/PM-7288): Deploy scanning workflow organization-wide
Improving code quality and code coverage issues with SonarCloud
[PM-7288]: https://bitwarden.atlassian.net/browse/PM-7288?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Include sources in scan workflow for Sonar

.github/workflows/crowdin-pull.yml, crowdin.yml
https://bitwarden.atlassian.net/browse/PM-9192
This sets up a regular sync every Friday to pull Crowdin translations and create a PR if necessary. Can also be run manually. …
=> [PM-9192] Pull translations from Crowdin

.github/workflows/build.yml
https://bitwarden.atlassian.net/browse/PM-8984
This fixes an issue with inserting the updated version number with yq into the project.yml file on a build
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for …
=> [PM-8984] Fix beta build

.github/ISSUE_TEMPLATE/bug.yml, README.md
https://bitwarden.atlassian.net/browse/PM-9340
Guides users to create Bitwarden prod (.NET MAUI) bugs in their respective repos.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's …
=> [PM-9340] Updates the bug template and readme to direct users to the right repos

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/config.yml
https://bitwarden.atlassian.net/browse/PM-9340
Fixes a syntax error in the Bug template and add a new link to the Issues tab. …
=> [PM-9340] Fix a Bug template syntax error and add a new link to the Issues tab

project.yml
[PM-9534](https://bitwarden.atlassian.net/browse/PM-9534)
Update SDK revision to 71dc81cb29ad2d3634a99c6a3d0823624ee1b152:
- https://github.com/bitwarden/sdk/pull/874
- https://github.com/bitwarden/sdk/pull/857 …
=> [PM-9534] Update SDK revision to 71dc81c

BitwardenShared/Core/Auth/Services/TestHelpers/BitwardenSdk+AuthFixtures.swift, project.yml
[PM-9597](https://bitwarden.atlassian.net/browse/PM-9597)
Update SDK to b0ba3818d7b7ddf0bc6b3777ed350c44de134079
- https://github.com/bitwarden/sdk/pull/875
- https://github.com/bitwarden/sdk/pull/883
- 🤔 …
=> [PM-9597] Update SDK to b0ba381

.github/workflows/scan.yml
Internal change.
Excludes tests from Sonar as a recommended best practice.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially …
=> Exclude tests from Sonar

.github/workflows/scan.yml
Internal change.
Wildcards at the end of a specified path shouldn't have a following slash as it's not a folder. …
=> Fix path typo on Sonar configuration

BitwardenShared/Core/Platform/Services/EnvironmentService.swift, BitwardenShared/Core/Platform/Services/EnvironmentServiceTests.swift
[BIT-2410](https://livefront.atlassian.net/browse/BIT-2410)
If an MDM pushes an app config profile to a device, the app should use the pre-configured URLs by default. If there's an existing account on the device, that account should still continue to work, but the pre-auth URLs should be set to the pre-configured URLs when adding any additional accounts.
App config settings are specified in UserDefaults under the `com.apple.configuration.managed` key. The base URL setting is specified within that dictionary with the `baseEnvironmentUrl` key.
- Used internationalization (i18n) …
=> BIT-2410: Support managed app config environment URLs

BitwardenShared/Core/Platform/Extensions/URL.swift, BitwardenShared/Core/Platform/Extensions/URLTests.swift, BitwardenShared/Core/Platform/Models/Domain/EnvironmentUrlData.swift, BitwardenShared/Core/Platform/Models/Domain/EnvironmentUrls.swift, BitwardenShared/Core/Platform/Models/Domain/EnvironmentUrlsTests.swift
[PM-8018](https://bitwarden.atlassian.net/browse/PM-8018)
Fixes an error if the entered self-hosted URL contains a trailing forward slash.
| --- | --- |
| <video src="https://github.com/user-attachments/assets/8f9e652b-bdfc-4223-8db9-5b5c796bde65" /> | <video src="https://github.com/user-attachments/assets/e1e38476-b129-4c04-8afe-3066672d02bf" /> | …
=> PM-8018: Fix error if self-hosted URL ends with a trailing slash

BitwardenShared/UI/Platform/Application/AppProcessor.swift
[PM-10450](https://bitwarden.atlassian.net/browse/PM-10450)
Clean up code removing not used import. …
=> [PM-10450] Remove OSLog import from AppProcessor

.github/workflows/build.yml
- [Card](https://bitwarden.atlassian.net/browse/BRE-242?atlOrigin=eyJpIjoiYWNiNzdlNTgxYzgwNDFjY2I2YzQ3NjVlZWM3NDhjZjciLCJwIjoiaiJ9)
This PR changes the `altool` to use `apiKey` and `apiIssuer` instead of `username` and `password`.
- ❓ …
=> BRE-242 - Fix App Store Connect Credentials

.github/workflows/build.yml
This fixes an issue with [PR 814](https://github.com/bitwarden/ios/pull/814) where a mistyped variable name meant things weren't getting updated properly.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for …
=> Fix variable in build flow

.github/workflows/CI-main.yml
https://bitwarden.atlassian.net/browse/PM-10838
This creates an empty CI-main workflow to get it added to the list of workflows of the repository, to make building out the actual CI-main workflow easier.
- …
=> Create empty CI-main workflow

BitwardenShared/Core/Vault/Services/PolicyService.swift, BitwardenShared/Core/Vault/Services/PolicyServiceTests.swift, BitwardenShared/Core/Vault/Services/Stores/TestHelpers/MockPolicyDataStore.swift
[PM-10836](https://bitwarden.atlassian.net/browse/PM-10836)
Fix a crash that was reported through crashlytics. No reproduction steps that I know of.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more …
=> PM-10836: Make PolicyService thread safe

BitwardenShared/Core/Platform/Utilities/Resources/public_suffix_list.dat
https://bitwarden.atlassian.net/browse/PM-2126
Pulls the latest from the public suffix list for use. …
=> Update public suffix list

BitwardenShared/UI/Auth/AuthCoordinator.swift, BitwardenShared/UI/Auth/CompleteRegistration/CompleteRegistrationProcessor.swift, BitwardenShared/UI/Auth/CompleteRegistration/CompleteRegistrationProcessorTests.swift
https://bitwarden.atlassian.net/browse/PM-9842
Show expired link screen when the token validation fails on CompleteRegistration  appear.
https://github.com/user-attachments/assets/5cc3773a-3ac0-46c0-9d3a-ba2750162567
- ❓ (`:question:`) …
=> [PM-9842] Show expired link screen

BitwardenShared/UI/Platform/Application/AppProcessor.swift, BitwardenShared/UI/Platform/Application/AppProcessorTests.swift
https://bitwarden.atlassian.net/browse/PM-1528
Change email verification AppLink handling to a new redirect-connector path. …
=> [PM-1528] AppLink new redirect path

BitwardenShared/Core/Vault/Services/PolicyServiceTests.swift
[PM-11430](https://bitwarden.atlassian.net/browse/PM-11430)
This policy service test was added to ensure that simultaneous access to the shared dictionary doesn't crash the app. However, it was also asserting that we only fetch the user's policies from the database once. This was causing occasional test failures. I don't think we can make this assertion though; an actor will ensure the shared state isn't accessed simultaneous from multiple threads, but it isn't going to serialize calls to the `policiesForUser` method. I don't think we need to guarantee that the policies are only fetched once, so I removed this assertion. I also changed the test to run multiple times to prevent a false positive from causing the test to succeed.
- All formatters and local …
=> PM-11430: Fix policy service intermittent test failures

BitwardenShared/UI/Auth/CompleteRegistration/CompleteRegistrationProcessor.swift, BitwardenShared/UI/Auth/CompleteRegistration/CompleteRegistrationProcessorTests.swift
[PM-11396](https://bitwarden.atlassian.net/browse/PM-11396)
In the email verification flow, log the user in and unlock their vault after creating an account. Previously, they would have to manually go through the login and vault unlock flow and re-enter their master password.
https://github.com/user-attachments/assets/e275c4ed-28e7-465e-b9aa-63c2ba2fd47f
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation …
=> PM-11396: Log the user in and unlock the vault after creating an account

BitwardenShared/Core/Platform/Models/Enum/FeatureFlag.swift
[PM-11614](https://bitwarden.atlassian.net/browse/PM-11614)
Enables the email verification feature flag for remote configuration.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's …
=> PM-11614: Allow email verification flag to be remotely configured

BitwardenShared/Core/Auth/Repositories/AuthRepository.swift, BitwardenShared/UI/Platform/Application/Extensions/View.swift, BitwardenShared/UI/Platform/Application/Views/BitwardenTextValueField.swift, BitwardenShared/UI/Vault/VaultItem/ViewItem/ViewItemDetailsView.swift
[PM-11672](https://bitwarden.atlassian.net/browse/PM-11672)
Fix allow copy/share on notes field in cipher item view.
https://github.com/user-attachments/assets/35fe12ab-b233-4608-9d04-85d336d339c9
- 🤔 …
=> [PM-11672] Fix allow copy/share on notes field in cipher item view

.github/CODEOWNERS
https://bitwarden.atlassian.net/browse/PM-9328
Adds repository codeowners. Due to a GitHub Teams restriction we're not able to create a team for LiveFront devs, in order to continue being able to review and approve PRs they'll need to be individually named in this file. 
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical …
=> [PM-9328] Codeowners setup

BitwardenShared/Core/Vault/Services/PolicyService.swift
Adding more comment for `organizationService` param at `PolicyService.swift`
=> [PM-11322] Adding more comment for organizationService param at PolicyService.swift

BitwardenShared/UI/Platform/Application/Views/ActionCardTests.swift, project.yml
https://bitwarden.atlassian.net/browse/PM-11213
This updates [ViewInspector](https://github.com/nalexn/ViewInspector) to version 0.10.0, which has Swift 6 compatibility. This was the main blocker for letting people use Xcode 16.
There is, however, more work to do to update to Xcode 16; this is just one part of the greater Xcode 16 / iOS 18 / Swift 6 effort. …
=> [PM-11213] Update ViewInspector

BitwardenShared/Core/Autofill/Services/AutofillCredentialServiceTests.swift, BitwardenShared/Core/Platform/Services/PasteboardServiceTests.swift
[PM-13142](https://bitwarden.atlassian.net/browse/PM-13142)
The following tests occasionally fail on CI. I think this should fix them from failing in the future.
```
Error: -[BitwardenSharedTests.PasteboardServiceTests test_error_updating] : XCTAssertEqual failed: ("Optional([BitwardenSharedTests.BitwardenTestError.example, BitwardenSharedTests.BitwardenTestError.example])") is not equal to ("Optional([BitwardenSharedTests.BitwardenTestError.example])")
```
https://github.com/bitwarden/ios/actions/runs/11129976827/job/30928320511
```
Error: -[BitwardenSharedTests.AutofillCredentialServiceTests test_syncIdentities_removeError] : XCTAssertEqual failed: ("Optional([BitwardenSharedTests.BitwardenTestError.example, BitwardenSharedTests.BitwardenTestError.example])") is not equal to …
```
=> PM-13142: Fix PasteboardService and AutofillCredentialService tests

.github/workflows/_version.yml
This updates a workflow to remove a line of dashes at the beginning that causes lint to fail. The fix is already on main, so it should merge fine …
=> Remove header from workflow so it can lint

BitwardenShared/Core/Platform/Services/TestHelpers/MockConfigService.swift, BitwardenShared/UI/Auth/AuthRouterTests.swift, BitwardenShared/UI/Auth/CompleteRegistration/CompleteRegistrationProcessorTests.swift, BitwardenShared/UI/Auth/IntroCarousel/IntroCarouselProcessorTests.swift, BitwardenShared/UI/Auth/Landing/LandingProcessor.swift, BitwardenShared/UI/Auth/Landing/LandingProcessorTests.swift, BitwardenShared/UI/Auth/StartRegistration/StartRegistrationProcessorTests.swift, BitwardenShared/UI/Platform/ExtensionSetup/ExtensionActivation/ExtensionActivationProcessorTests.swift
N/A
Backport `release/2024.11-rc1` into main.
- 🎨 …
=> PM-14502: Fix account creation email verification feature flag loading

.github/CODEOWNERS
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) …
=> Remove myself from CODEOWNERS file

.github/ISSUE_TEMPLATE/bug.yml, .github/workflows/test.yml, README.md
https://bitwarden.atlassian.net/browse/PM-12269
https://bitwarden.atlassian.net/browse/PM-12602
1. Adds server related fields to the Bug template
2. Updates readme to remove references to the legacy repo and unused dependency
3. Remove dependency from test.yml, previously missed in #945 …
=> [PM-12269] Update README and Bug template

.github/workflows/build-for-simulator.yml
https://bitwarden.atlassian.net/browse/PM-9375
In order to better automate QA testing, we want to be able to load the app into an arbitrary simulator without an attached Xcode. Because building this will take a slightly different flow from our normal build-archive-and-upload flow, it makes sense to do it as a separate workflow. This establishes that, so that it's easier in the future to run while building out this capability. …
=> [PM-9375] Initial workflow for building to simulator

.github/workflows/crowdin-pull.yml
- [Card](https://bitwarden.atlassian.net/browse/BRE-438?atlOrigin=eyJpIjoiYjc3YjAyYmZjYjg4NDE4OTljMGM3OTAwY2QxYmVlNTkiLCJwIjoiaiJ9)
This PR updates the `Crowdin Sync` workflow to create the PR using a temporary token generated by our `BW-GHApp`.
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or …
=> BRE-438 - Update Crowdin workflow to use app token

BitwardenShared/Core/Auth/Models/Response/IdentityTokenErrorModel.swift, BitwardenShared/Core/Auth/Models/Response/MasterPasswordPolicyResponseModel.swift, BitwardenShared/Core/Auth/Services/API/Auth/Requests/IdentityTokenRequest.swift
https://bitwarden.atlassian.net/browse/PM-10900
The identity response model for the master password policy wasn't deserialising properly, adding coding keys fixed the issue.
Without coding keys:
With coding keys: …
=> [PM-10900] Add coding keys to MasterPasswordPolicyResponseModel

BitwardenShared/UI/Platform/Application/Support/Localizations/en.lproj/Localizable.strings
[PM-14168](https://bitwarden.atlassian.net/browse/PM-14168)
Change "Log In" to "Log in".
| --- | --- |
| <img width="568" alt="Screenshot 2024-12-03 at 4 35 31 PM" src="https://github.com/user-attachments/assets/d61df037-3036-4706-bac7-eeefeb9f12ce"> | <img width="568" alt="Screenshot 2024-12-03 at 4 34 46 PM" src="https://github.com/user-attachments/assets/2e88c111-ccb9-4c4b-bf05-fc8d8455db2a"> |
- Updated any necessary documentation …
=> PM-14168: Update log in button capitalization

.github/ISSUE_TEMPLATE/config.yml
https://bitwarden.atlassian.net/browse/PM-15583
Adds Autofill failure report form to GitHub issues menu …
=> [PM-15583] chore: Adds Autofill failure report form to GitHub issues menu

Scripts/bootstrap.sh
PM-16212
Warns if the installed xcode version doesn't match the version set in our repo.
| 🟡 version mismatched warning  | ✅ version matched  |
| <img width="432" alt="image" src="https://github.com/user-attachments/assets/07247a92-8d89-4283-8e98-5bde79b9cc74" /> | <img width="429" alt="image" src="https://github.com/user-attachments/assets/d96faf44-3d82-4e07-99cd-dbbeb3181484" /> |  …
=> [PM-16212] feat: Add xcode version check to bootstrap script

BitwardenShared/Core/Platform/Models/Enum/FeatureFlag.swift
[PM-17672](https://bitwarden.atlassian.net/browse/PM-17672)
Updates the feature flag name for syncing with the authenticator app. This consolidates multiple app and platform feature flags behind a single `enable-pm-bwa-sync` flag.
- ❓ …
=> PM-17672: Update authenticator sync feature flag name

.github/workflows/build-bwa.yml, .github/workflows/crowdin-pull-bwa.yml, .github/workflows/crowdin-push-bwa.yml, .github/workflows/scan-bwa.yml, .github/workflows/test-bwa.yml
PM-18383
Adding empty GitHub Workflows so we can test the Authenticator files ahead of time. …
=> [PM-18383] Add placeholder workflows for the Authenticator

BitwardenShared/UI/Platform/Application/Views/GuidedTourView/GuidedTourScrollView.swift
[PM-18241](https://bitwarden.atlassian.net/browse/PM-18241)
While working on the guided tour, we disabled the transition animation to implement a custom animation for the tour. This resulted in the disabling of all regular animations. This PR will restore the transition animation once the guided tour is dismissed.
<video width=455 src=https://github.com/user-attachments/assets/faec8c74-fe18-4cd3-ae48-cf074adbc982 />
- Updated any necessary documentation …
=> PM-18241: Fix toggle animation

project-pm.yml
https://bitwarden.atlassian.net/browse/PM-18411
https://bitwarden.atlassian.net/browse/PM-18519
The work to move things into a workspace did not properly set up framework embedding, causing a crash on device. This fixes how the internal frameworks are embedded.
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) …
=> [PM-18411] Fix internal framework embedding

BitwardenShared/Core/Platform/Services/NotificationCenterServiceTests.swift
[PM-18568](https://bitwarden.atlassian.net/browse/PM-18568)
The tests in `NotificationCenterServiceTests` have been failing for me locally. This change has been a lot more stable for me. A few observations that I had:
- `setUp()` initializes the tasks to listen for published notifications, but since this is a background task, it's possible for a race condition here where the task is started after the notification in the test is posted. So I've changed it to wait until the tasks start before ending `setUp()`.
- Using our `waitFor` or `waitForAsync` helpers seems to cause issues with notification center and so I swapped this out for XCTest expectations.
- Written new unit and / or integration tests …
=> PM-18568: Fix intermittent NotificationCenterServiceTests failures

BitwardenShared/UI/Auth/Login/TwoFactorAuth/TwoFactorAuthProcessor.swift, BitwardenShared/UI/Auth/Login/TwoFactorAuth/TwoFactorAuthProcessorTests.swift, BitwardenShared/UI/Auth/Login/TwoFactorAuth/TwoFactorAuthState.swift, BitwardenShared/UI/Auth/Login/TwoFactorAuth/TwoFactorAuthView.swift, BitwardenShared/UI/Platform/Application/Support/Localizations/en.lproj/Localizable.strings
(cherry picked from commit e29448fecb0981d7a7a6eb7ac216364e578df917)
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit …
=> [PM-8222] New device verification page fixes (#1381)

Bitwarden.xcworkspace/xcshareddata/swiftpm/Package.resolved, project-bwk.yml, project-pm.yml
[PM-18511](https://bitwarden.atlassian.net/browse/PM-18511)
Updated **firebase-ios-sdk** dependency from 10.24.0 to 11.8.1. …
=> [PM-18511] Updated Firebase dependency to 11.8.1

SECURITY.md
PM-18656
Update bitwarden/template common file. SECURITY.md was the only in need of an update, also checked the PR template, Issues config.yml and contributing.md. …
=> [PM-18656] Sync with bitwarden/template

BitwardenShared/Core/Vault/Services/PolicyService.swift, BitwardenShared/Core/Vault/Services/PolicyServiceTests.swift
[PM-18676](https://bitwarden.atlassian.net/browse/PM-18676)
- Apply policies even if org is disabled. …
=> PM-18676: apply policy for disabled orgs

BitwardenKit/Core/Platform/Extensions/Bundle+Extensions.swift, BitwardenShared/Core/Platform/Services/AppInfoService.swift, BitwardenShared/Core/Platform/Services/AppInfoServiceTests.swift, BitwardenShared/Core/Platform/Services/ServiceContainer.swift, BitwardenShared/Core/Platform/Services/Services.swift, BitwardenShared/Core/Platform/Services/TestHelpers/MockAppInfoService.swift, BitwardenShared/Core/Platform/Services/TestHelpers/MockBundle.swift, BitwardenShared/Core/Platform/Services/TestHelpers/ServiceContainer+Mocks.swift, BitwardenShared/UI/Platform/Settings/Settings/About/AboutProcessor.swift, BitwardenShared/UI/Platform/Settings/Settings/About/AboutProcessorTests.swift, BitwardenShared/UI/Platform/Settings/Settings/About/AboutState.swift, BitwardenShared/UI/Platform/Settings/SettingsCoordinator.swift
[PM-18224](https://bitwarden.atlassian.net/browse/PM-18224)
As part of the error reporting work, we want to include the app info that is currently accessible on the about screen with the error details. This extracts the app info bits into an `AppInfoService` so it's more easily shared between different parts of the app. …
=> [PM-18224] Add AppInfoService

BitwardenShared/UI/Platform/Application/Views/ToastView.swift
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) …
=> [QA-1108] Adding automation ID for Toasts

.github/workflows/scan-bwa.yml, .github/workflows/scan.yml
https://bitwarden.atlassian.net/browse/VULN-226
Add correct ref/sha reference for main and PR branches, since codeql/upload-sarif doesn't handle pull_request_target properly. …
=> Fix SARIF upload branch ref/sha

BitwardenShared/Core/Platform/Models/Enum/FeatureFlag.swift, BitwardenShared/Core/Platform/Models/Enum/FeatureFlagTests.swift
[PM-19542](https://bitwarden.atlassian.net/browse/PM-19542)
Adds the feature flag for the flight recorder. …
=> [PM-19542] Add flight recorder feature flag

.github/CODEOWNERS, BitwardenShared/Core/Platform/Services/API/TestHelpers/Result+HTTPResponse.swift
- Removed myself from code owners list.
- 🎨 (`:art:`) …
=> Changed code owner

BitwardenShared/Core/Platform/Extensions/URL.swift
https://bitwarden.atlassian.net/browse/PM-13010
URI launch buttons were only showing for a few specific Top Level Domains. Remove the top level domain validation and always show the icon.
- 🤔 …
=> [PM-13010] Show launch url button and ignore TLD

BitwardenShared/UI/Vault/VaultItem/CipherItemState.swift, BitwardenShared/UI/Vault/VaultItem/CipherItemStateTests.swift, BitwardenShared/UI/Vault/VaultItem/ViewItem/ViewItemState.swift, BitwardenShared/UI/Vault/VaultItem/ViewItem/ViewItemView.swift
https://bitwarden.atlassian.net/browse/PM-20115
Feature flag value was not being passed correctly to Item state. …
=> [PM-20115] Delete button visibility based on cipher permissions

BitwardenShared/Core/Platform/Extensions/FileManager+Extensions.swift, BitwardenShared/Core/Platform/Extensions/URL.swift, BitwardenShared/Core/Platform/Extensions/URLTests.swift, BitwardenShared/Core/Platform/Models/Data/FlightRecorderData.swift, BitwardenShared/Core/Platform/Models/Data/FlightRecorderDataTests.swift, BitwardenShared/Core/Platform/Models/Enum/FlightRecorderLoggingDuration.swift, BitwardenShared/Core/Platform/Models/Enum/FlightRecorderLoggingDurationTests.swift, BitwardenShared/Core/Platform/Services/FlightRecorder.swift, BitwardenShared/Core/Platform/Services/FlightRecorderTests.swift, BitwardenShared/Core/Platform/Services/ServiceContainer.swift, BitwardenShared/Core/Platform/Services/StateService.swift, BitwardenShared/Core/Platform/Services/StateServiceTests.swift, BitwardenShared/Core/Platform/Services/Stores/AppSettingsStore.swift, BitwardenShared/Core/Platform/Services/Stores/AppSettingsStoreTests.swift, BitwardenShared/Core/Platform/Services/Stores/TestHelpers/MockAppSettingsStore.swift, BitwardenShared/Core/Platform/Services/TestHelpers/MockFlightRecorder.swift, BitwardenShared/Core/Platform/Services/TestHelpers/MockStateService.swift, BitwardenShared/Core/Platform/Utilities/FileManager.swift, BitwardenShared/Core/Platform/Utilities/FileManagerTests.swift, BitwardenShared/Core/Platform/Utilities/TestHelpers/MockFileManager.swift, BitwardenShared/UI/Platform/Application/AppProcessor.swift, BitwardenShared/UI/Platform/Settings/Settings/About/EnableFlightRecorder/EnableFlightRecorderProcessor.swift, BitwardenShared/UI/Platform/Settings/Settings/About/EnableFlightRecorder/EnableFlightRecorderProcessorTests.swift
This adds the logic to create the log file when the flight recorder is enabled along with persisting the flight recorder log metadata to UserDefaults. …
=> [PM-19577] Add flight recorder log creation

.github/workflows/_build-any.yml, .github/workflows/ci-bwa.yml, .github/workflows/ci-bwpm.yml
[PM-18414](https://bitwarden.atlassian.net/browse/PM-18414)
Adding placeholder files so we can test these new workflows in feature branches. …
=> [PM-18414] CI restructuring #1 - Add placeholders for new workflows

BitwardenShared/Core/Platform/Models/Enum/FeatureFlag.swift, BitwardenShared/Core/Platform/Models/Enum/FeatureFlagTests.swift, BitwardenShared/UI/Vault/Vault/VaultList/VaultListProcessor.swift, BitwardenShared/UI/Vault/Vault/VaultList/VaultListProcessorTests.swift
https://bitwarden.atlassian.net/browse/PM-20147
Remove `app-review-prompt` feature flag from codebase. …
=> [PM-20147] Remove app-review-prompt feature flag.

Bitwarden.xcworkspace/xcshareddata/swiftpm/Package.resolved, project-bwa.yml, project-bwk.yml, project-pm.yml
This updates SPM dependencies to the latest versions. No other code changes were necessary. …
=> deps: Update SPM dependencies

BitwardenShared/UI/Platform/Application/Appearance/Modifiers/ImageStyle.swift, BitwardenShared/UI/Vault/VaultItem/ViewItem/ViewItemDetailsView.swift
https://bitwarden.atlassian.net/browse/PM-20430
Fix color of icons.
Before:
After: …
=> [PM-20430] Fix icon color

BitwardenShared/UI/Vault/VaultItem/ViewItem/ViewItemDetailsView.swift
https://bitwarden.atlassian.net/browse/PM-20429
Fix bug where the icon color in the item view page was not being rendered correctly.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry …
=> [PM-20429] Fix item icon color.

.github/workflows/scan-bwa.yml, .github/workflows/scan.yml
[BRE-609](https://bitwarden.atlassian.net/browse/BRE-609)
update workflows to be compliant with pull_request_target workflow linter rule ahead of changing rule log level to error …
=> BRE-609/workflow-changes

project-bwa.yml
Fix project-bwa to take into consideration local SDK config.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from …
=> debt: Fix project-bwa to take into consideration local SDK config

BitwardenShared/Core/Platform/Services/FlightRecorder.swift, BitwardenShared/Core/Platform/Services/FlightRecorderTests.swift
🍒 Cherry picked from #1567 for `rc`.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and …
=> [PM-19577] [RC] Deactivate flight recorder if appending to the log fails

Bitwarden.xcworkspace/xcshareddata/swiftpm/Package.resolved, project-bwa.yml, project-bwk.yml, project-pm.yml
[PM-20456](https://bitwarden.atlassian.net/browse/PM-20456)
Updated SDK to last current version `6324c3ab661606ef0ce7dd90ade730615ee9e2c8`.
Included PRs -> https://github.com/bitwarden/sdk-internal/pulls?q=is%3Apr+is%3Aclosed+merged%3A2025-05-23..2025-06-02+
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for …
=> [PM-20456] Updated SDK to 6324c3a

BitwardenShared/Core/Vault/Repositories/VaultRepository.swift, BitwardenShared/Core/Vault/Repositories/VaultRepositoryTests.swift
https://bitwarden.atlassian.net/browse/PM-22300
Simplify TOTP service error message …
=> [PM-22300] Simplify TOTP service error message

BitwardenShared/Core/Vault/Models/Domain/Fixtures/VaultListItem+Fixtures.swift, BitwardenShared/Core/Vault/Repositories/VaultRepository.swift, BitwardenShared/Core/Vault/Repositories/VaultRepositoryTests.swift, BitwardenShared/Core/Vault/Services/TestHelpers/MockVaultClientService.swift, BitwardenShared/Core/Vault/Services/VaultClientService.swift, BitwardenShared/UI/Vault/Vault/VaultGroup/VaultGroupProcessorTests.swift, BitwardenShared/UI/Vault/Vault/VaultList/VaultListItem.swift, BitwardenShared/UI/Vault/Views/VaultListItemRow/VaultListItemRowView.swift
[PM-22401](https://bitwarden.atlassian.net/browse/PM-22401)
Fix TOTP code generation on things using `CipherListView` to use the new code generation SDK API `generateTotpCipherView(view: cipherListView, time: calculationDate)` so it decrypts the TOTP key correctly. …
=> [PM-22401] Fix TOTP code generation on lists using CipherListView

.github/workflows/scan-bwa.yml, .github/workflows/scan.yml
https://bitwarden.atlassian.net/browse/VULN-252
Further restrict permissions to check-run, to prevent abuse of github tokens …
=> Fix permissions for check-run action

.github/workflows/github-release.yml
PM-22524
Update GitHub Release creation workflow to support releasing Password Manager and Authenticator apps. …
=> [PM-22524]  GitHub Release workflow supports releasing BWPM and BWA

.github/workflows/build-bwa.yml
Logging inputs to job summary to help with troubleshooting builds
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from …
=> log inputs to job summary for build workflows

fastlane/Fastfile
PM-18414
Changing the wheels of a moving car isn't easy. :feelsgood: Defaults the bundle ID used in the upload to TestFlight step to provide backwards compatibility with the current Build workflow.
- 🤔 …
=> [PM-18414] Fix testflight upload build step

fastlane/.env.bwa_prod
PM-21331
Update Authenticator Firebase Crashlytics config. :godmode: 
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit …
=> [PM-21331] Update Authenticator Firebase Crashlytics config

.github/workflows/_build-any.yml, .github/workflows/build.yml
[BRE-831](https://bitwarden.atlassian.net/browse/BRE-831)
Adding `if` to secrets retrieval step to match steps where it's needed.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's …
=> [BRE-831] Fixing Secrets Retrievel Step

.github/workflows/publish-github-release.yml
Fix publish-github-release workflow permissions that the https://github.com/bitwarden/gh-actions/blob/main/.github/workflows/_publish-mobile-github-release.yml needs. …
=> Fix publish-github-release workflow permissions

Bitwarden.xcworkspace/xcshareddata/swiftpm/Package.resolved, BitwardenShared/Core/Auth/Repositories/AuthRepository.swift, BitwardenShared/Core/Auth/Repositories/AuthRepositoryTests.swift, project-bwa.yml, project-bwk.yml, project-pm.yml
https://bitwarden.atlassian.net/browse/PM-23872
Update Bitwarden SDK to `ad0761937f454e2785c50a9b8dc9be12f26af830` including:
- https://github.com/bitwarden/sdk-internal/pull/322 - For now we're passing `null` to the `securityState` to comply with the new SDK changes, the proper use will be done in a future PR. …
=> [PM-23872] Update Bitwarden SDK to ad07619

.github/workflows/publish-store.yml
BRE-831
- 🎨 (`:art:`) for suggestions / improvements
- ❌ …
=> secrets fix

BitwardenShared/Core/Platform/Models/Enum/FeatureFlag.swift, BitwardenShared/Core/Platform/Models/Enum/FeatureFlagTests.swift, BitwardenShared/UI/Platform/Application/Utilities/Coordinator.swift, BitwardenShared/UI/Platform/Application/Utilities/CoordinatorTests.swift, BitwardenShared/UI/Platform/DebugMenu/DebugMenuCoordinator.swift, BitwardenShared/UI/Platform/LoginRequest/LoginRequestProcessor.swift, BitwardenShared/UI/Platform/Settings/Settings/Vault/Folders/AddEditFolder/AddEditFolder/AddEditFolderProcessor.swift, BitwardenShared/UI/Tools/Send/Send/SendCoordinator.swift, BitwardenShared/UI/Tools/Send/SendItem/SendItemCoordinator.swift
[PM-24091](https://bitwarden.atlassian.net/browse/PM-24091)
Removes the `mobile-error-reporting` feature flag. …
=> [PM-24091] Remove mobile-error-reporting feature flag

.github/workflows/scan-bwa.yml, .github/workflows/scan.yml
https://bitwarden.atlassian.net/browse/VULN-254
Use the new reusable workflow file in the gh-actions repo. This allows modularity as well as easier maintenance, while reducing copied code.
- 🤔 …
=> Update scan workflow to use centralized reusable component

BitwardenShared/Core/Vault/Services/PolicyService.swift, BitwardenShared/Core/Vault/Services/PolicyServiceTests.swift
https://bitwarden.atlassian.net/browse/PM-24477
Remove admin and owner exemption from restrict item types policy. …
=> [PM-24477] Remove exemption from restrict item types policy

BitwardenKit/Core/Platform/Extensions/Data.swift, fastlane/Fastfile
[PM-25005](https://bitwarden.atlassian.net/browse/PM-25005)
Fix build on release for Xcode 26 beta.
- Removes optimization for `Data::generatedHashBase64Encoded` which was causing the optimizer to fail on build. See https://github.com/swiftlang/swift/issues/83788
- Fixes the Fastfile to execute the `alpha_update_cxp_infoplist.sh` in the right context folder. …
=> [PM-25005] Fix build on release for Xcode 26 beta

.github/workflows/sdlc-sdk-update.yml
N/A
Adding placeholder workflow for the new sdlc-sdk-update.yml so we can test it before merging.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and …
=> Add workflow placeholder for sdlc-sdk-update.yml

Bitwarden/Application/Support/Info.plist, Configs/Common-bwpm.xcconfig, fastlane/.env.bwa_prod, fastlane/.env.bwpm_beta, fastlane/.env.bwpm_prod, fastlane/Fastfile
[PM-25325](https://bitwarden.atlassian.net/browse/PM-25325)
Update main PM app display name depending on the variant:
- PRD: Bitwarden
- Beta: Bitwarden Beta
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) …
=> [PM-25325] Update PM display name depending on the build variant

BitwardenShared/UI/Auth/Login/SingleSignOn/SingleSignOnView.swift, BitwardenShared/UI/Platform/Application/Appearance/Modifiers/TextFieldConfiguration.swift
[PM-24342](https://bitwarden.atlassian.net/browse/PM-24342)
Disables autocorrect for the SSO organization identifier field. …
=> [PM-24342] Disable autocorrect for SSO organization identifier field

Scripts/update-sdk-version.sh
N/A
Fix sed script to prevent this [error](https://github.com/bitwarden/ios/actions/runs/17608940544). …
=> Fix sed script

.github/workflows/_build-any.yml
[PM-25827](https://bitwarden.atlassian.net/browse/PM-25827)
Upgrade `_build-any.yml` workflow to use _macos-26_ to be able to use **Xcode 26 RC**.
Blocked by: https://github.com/rhysd/actionlint/issues/570 …
=> [PM-25827] Upgrade Build workflow to use macos-26

Authenticator/Application/Services/ErrorReporter/CrashlyticsErrorReporter.swift, AuthenticatorShared/Core/Platform/Models/Enum/ClearClipboardValue.swift, AuthenticatorShared/Core/Platform/Models/Enum/DefaultSaveOption.swift, AuthenticatorShared/Core/Vault/Services/Importers/Support/Base32.swift, Bitwarden/Application/Services/ErrorReporter/CrashlyticsErrorReporter.swift, Bitwarden/Application/Services/ErrorReporter/ErrorReporterFactory.swift, BitwardenShared/Core/Auth/Services/KeychainService.swift, BitwardenShared/Core/Platform/Models/Enum/ClearClipboardValue.swift, BitwardenShared/Core/Platform/Services/AuthenticatorSyncService.swift, BitwardenShared/Core/Tools/Utilities/CXFCredentialsResult.swift, BitwardenShared/Core/Vault/Models/Enum/LinkedIdType.swift, BitwardenShared/Core/Vault/Services/TOTP/TOTPServiceError.swift, BitwardenShared/UI/Auth/AuthCoordinator.swift, BitwardenShared/UI/Auth/Landing/LandingView.swift, BitwardenShared/UI/Platform/Application/AppIntentMediator.swift, BitwardenShared/UI/Platform/Application/Utilities/AppContextHelper.swift, BitwardenWatchApp/Entities/StringEncryptionTransformer.swift, BitwardenWatchApp/Utilities/Queue.swift
[PM-25704](https://bitwarden.atlassian.net/browse/PM-25704)
Fixes the `redundantPublic` SwiftLint warnings. …
=> [PM-25704] Fix redundantPublic lint warnings

.github/workflows/sdlc-sdk-update.yml, Scripts/update-sdk-version.sh
PM-26142 
Fix the update of Package.resolved and prevent an edge case where extracting the hash from the commit message would return more than one in case there were more hashes.
Workflow failing: https://github.com/bitwarden/ios/actions/runs/17953659357
Workflow successful: https://github.com/bitwarden/ios/actions/runs/17957116740
- 👍 (`:+1:`) or …
=> [PM-26142] Fix SDK Update - handle commit message having a commit hash and commit Package.resolved changes

BitwardenResources/Localizations/en.lproj/Localizable.strings
https://bitwarden.atlassian.net/browse/PM-26114
This updates our uses of ellipses from three periods (`...`) to the ellipsis character (`…`), per typographic guidelines …
=> [PM-26114] Update ellipses to ellipsis character

BitwardenKit/UI/Platform/Application/Views/ContentBlock.swift, BitwardenShared/UI/Auth/CompleteRegistration/PreventAccountLock/PreventAccountLockView.swift, BitwardenShared/UI/Auth/SetMasterPassword/SetMasterPasswordView.swift, BitwardenShared/UI/Auth/UpdateMasterPassword/UpdateMasterPasswordView.swift, BitwardenShared/UI/Platform/Settings/Settings/About/AboutView.swift, BitwardenShared/UI/Platform/Settings/Settings/AccountSecurity/AccountSecurityView.swift, BitwardenShared/UI/Platform/Settings/Settings/AccountSecurity/PendingRequests/PendingRequestsView.swift, BitwardenShared/UI/Platform/Settings/Settings/Appearance/SelectLanguage/SelectLanguageView.swift, BitwardenShared/UI/Platform/Settings/Settings/AutoFill/AutoFillView.swift, BitwardenShared/UI/Platform/Settings/Settings/SettingsListItem.swift, BitwardenShared/UI/Platform/Settings/Settings/SettingsView.swift, BitwardenShared/UI/Platform/Settings/Settings/Vault/Folders/FoldersView.swift, BitwardenShared/UI/Platform/Settings/Settings/Vault/VaultSettingsView.swift, BitwardenShared/UI/Tools/Generator/Generator/GeneratorView.swift, BitwardenShared/UI/Tools/Send/SendItem/AddEditSendItem/SendItemAccessCountStepper.swift, BitwardenShared/UI/Vault/VaultItem/AddEditItem/AddEditCardItem/AddEditCardItemView.swift, BitwardenShared/UI/Vault/VaultItem/AddEditItem/AddEditIdentityItem/AddEditIdentityItemView.swift, BitwardenShared/UI/Vault/VaultItem/AddEditItem/AddEditItemView.swift, BitwardenShared/UI/Vault/VaultItem/Attachments/AttachmentsView.swift, BitwardenShared/UI/Vault/VaultItem/EditCollections/EditCollectionsView.swift, BitwardenShared/UI/Vault/VaultItem/MoveToOrganization/MoveToOrganizationView.swift, BitwardenShared/UI/Vault/VaultItem/ViewItem/ViewCardItem/ViewCardItemView.swift, BitwardenShared/UI/Vault/VaultItem/ViewItem/ViewIdentityItem/ViewIdentityItemView.swift, BitwardenShared/UI/Vault/VaultItem/ViewItem/ViewSSHKeyItemView/ViewSSHKeyItemView.swift
https://bitwarden.atlassian.net/browse/PM-26064
This consolidates the `ContentBlock` object into `BItwardenKit`, which will enable more consolidation and UI alignment in the future. …
=> [PM-26064] Consolidate ContentBlock into BitwardenKit
