- BitwardenShared/Core/Vault/Services/TOTP/OTPAuthModel.swift
- BitwardenShared/Core/Vault/Services/TOTP/OTPAuthModelTests.swift
- BitwardenShared/Core/Vault/Services/TOTP/TOTPCodeConfigTests.swift
- BitwardenShared/Core/Vault/Services/TOTP/TestHelpers/String+TOTPFixtures.swift
[BIT-2348](https://livefront.atlassian.net/browse/BIT-2350)
Adds support for parsing the account name and issuer from the OTP key.
This is needed as a precursor to searching for matching ciphers based on the account name or issuer from the key.
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or …
> BIT-2348: Add OTP key parsing for account name and issuer

- BitwardenShared/UI/Platform/Application/Utilities/StackNavigator.swift
- BitwardenShared/UI/Platform/Settings/SettingsCoordinator.swift
[BIT-2434](https://livefront.atlassian.net/browse/BIT-2434)
This fixes a crash when presenting a `UIActivityViewController`. These are presented as popovers on iPadOS, and need a `sourceView` to be specified.  …
> BIT-2434: Set a source view and rect when presenting popovers for iPadOS

- .github/workflows/crowdin-pull.yml
- crowdin.yml
https://bitwarden.atlassian.net/browse/PM-9192
This updates the Crowdin paths to `ios` and `ios-watch` directories instead of long trees.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry …
> [PM-9192] Update Crowdin destination path

- BitwardenShared/Core/Auth/Repositories/AuthRepository.swift
- BitwardenShared/Core/Auth/Repositories/AuthRepositoryTests.swift
- BitwardenShared/Core/Auth/Repositories/TestHelpers/MockAuthRepository.swift
- BitwardenShared/Core/Platform/Services/EnvironmentService.swift
- BitwardenShared/Core/Platform/Services/StateService.swift
- BitwardenShared/Core/Platform/Services/StateServiceTests.swift
- BitwardenShared/Core/Platform/Services/TestHelpers/MockEnvironmentService.swift
- BitwardenShared/Core/Platform/Services/TestHelpers/MockStateService.swift
- BitwardenShared/UI/Auth/Extensions/Alert+Auth.swift
- BitwardenShared/UI/Auth/Extensions/AlertAuthTests.swift
- BitwardenShared/UI/Auth/Landing/LandingAction.swift
- BitwardenShared/UI/Auth/Landing/LandingEffect.swift
- BitwardenShared/UI/Auth/Landing/LandingProcessor.swift
- BitwardenShared/UI/Auth/Landing/LandingProcessorTests.swift
- BitwardenShared/UI/Auth/Landing/LandingView.swift
- BitwardenShared/UI/Auth/Landing/LandingViewTests.swift
[BIT-2366](https://livefront.atlassian.net/browse/BIT-2366)
On login, if the user's entered email matches an existing account and the base URLs match, present an alert to switch to that account.
https://github.com/bitwarden/ios/assets/126492398/8f506a9d-99ad-4c40-9027-a7ae21e179aa …
> BIT-2366: Alert user to switch to existing account with matching email on login

- BitwardenShared/Core/Vault/Repositories/VaultRepository.swift
- BitwardenShared/Core/Vault/Repositories/VaultRepositoryTests.swift
- BitwardenShared/UI/Platform/Application/Utilities/Alert/Alert/AlertTests.swift
- BitwardenShared/UI/Vault/Extensions/Alert+Vault.swift
- BitwardenShared/UI/Vault/Helpers/AutofillHelper.swift
- BitwardenShared/UI/Vault/Helpers/AutofillHelperTests.swift
- BitwardenShared/UI/Vault/Vault/VaultGroup/VaultGroupProcessor.swift
- BitwardenShared/UI/Vault/Vault/VaultGroup/VaultGroupProcessorTests.swift
- BitwardenShared/UI/Vault/Vault/VaultList/VaultListProcessor.swift
- BitwardenShared/UI/Vault/Vault/VaultList/VaultListProcessorTests.swift
- BitwardenShared/UI/Vault/VaultItem/CipherItemState.swift
- BitwardenShared/UI/Vault/VaultItem/CipherItemStateTests.swift
[BIT-2393](https://livefront.atlassian.net/browse/BIT-2393)
Enables TOTP features for ciphers in an organization that uses TOTP without giving users premium access. …
> BIT-2393: Enable TOTP features for organizations that use TOTP without premium

- BitwardenShared/UI/Auth/Utilities/UserVerificationHelper.swift
- BitwardenShared/UI/Auth/Utilities/UserVerificationHelperTests.swift
- BitwardenShared/UI/Vault/Vault/VaultCoordinator.swift
- BitwardenShared/UI/Vault/Vault/VaultItemSelection/VaultItemSelectionProcessor.swift
- BitwardenShared/UI/Vault/Vault/VaultItemSelection/VaultItemSelectionProcessorTests.swift
- BitwardenShared/UI/Vault/VaultItem/AddEditItem/AddEditItemProcessor.swift
- BitwardenShared/UI/Vault/VaultItem/AddEditItem/AddEditItemProcessorTests.swift
- BitwardenShared/UI/Vault/VaultItem/ViewItem/ViewLoginItem/Extensions/CipherView+Update.swift
[BIT-2349](https://livefront.atlassian.net/browse/BIT-2349)
Allows adding an OTP key from a QR code to an existing item in the vault. Selecting a vault item brings up the edit view with the key populated.
https://github.com/bitwarden/ios/assets/126492398/a445a8b4-2333-415f-9768-605704725559
- 📝 (`:memo:`) or …
> BIT-2349: Allow adding an OTP key to existing items

- BitwardenShared/Core/Platform/Services/Services.swift
- BitwardenShared/Core/Platform/Services/TestHelpers/MockApplication.swift
- BitwardenShared/Core/Platform/Services/TestHelpers/MockStateService.swift
- BitwardenShared/UI/Platform/Application/AppProcessor.swift
- BitwardenShared/UI/Vault/Vault/VaultCoordinator.swift
- BitwardenShared/UI/Vault/Vault/VaultList/VaultListProcessor.swift
- BitwardenShared/UI/Vault/Vault/VaultList/VaultListProcessorTests.swift
https://bitwarden.atlassian.net/browse/PM-8965
Previously, the app was only registering for push notifications on launch, which meant that it would only register for an active user at that time. This now registers more aggressively, by checking any time the user goes to the vault list. It will also register after a user has granted permission for push notifications. However, it will also only attempt to register once per day (defined as 86400 seconds), to match the MAUI app.
- Communicated to DevOps any …
> [PM-8965] Register for push notifications more aggressively

- .github/workflows/crowdin-push.yml
https://bitwarden.atlassian.net/browse/PM-9193
The crowdin-push.yml workflow is in the wrong location, and is not treated as a workflow. This puts it in the correct location, and has the branch-matching updated to be like other workflows …
> [PM-9193] Fix Crowdin push workflow location

- .github/workflows/build.yml
https://bitwarden.atlassian.net/browse/PM-7982
This splits the build step to retrieve the `GoogleServices-Info.plist` from Azure so that the production and beta builds use different plists. This should allow Crashlytics to work for the Beta build.
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or …
> [PM-7982] Use a different GoogleService-Info.plist file on beta builds

- BitwardenShared/Core/Vault/Services/TestHelpers/MockVaultTimeoutService.swift
- BitwardenShared/UI/Auth/AuthAction.swift
- BitwardenShared/UI/Auth/AuthRouter.swift
- BitwardenShared/UI/Auth/ProfileSwitcher/ProfileSwitcherHandler.swift
- BitwardenShared/UI/Platform/Application/AppCoordinator.swift
- BitwardenShared/UI/Platform/Application/AppCoordinatorTests.swift
- BitwardenShared/UI/Platform/Application/AppProcessor.swift
- BitwardenShared/UI/Platform/Application/AppProcessorTests.swift
- BitwardenShared/UI/Platform/Application/AppRoute.swift
- BitwardenShared/UI/Platform/Application/Utilities/RootViewController.swift
- BitwardenShared/UI/Platform/Application/Utilities/RootViewControllerTests.swift
- BitwardenShared/UI/Platform/Settings/SettingsCoordinator.swift
- BitwardenShared/UI/Vault/Vault/VaultCoordinator.swift
- BitwardenShared/UI/Vault/Vault/VaultCoordinatorTests.swift
- BitwardenShared/UI/Vault/Vault/VaultItemSelection/VaultItemSelectionProcessor.swift
- BitwardenShared/UI/Vault/Vault/VaultItemSelection/VaultItemSelectionProcessorTests.swift
[BIT-2349](https://livefront.atlassian.net/browse/BIT-2349)
If the vault is locked when a TOTP QR code is scanned, open the vault item selection screen after the user's vault has been unlocked. Additionally, this handles switching between accounts with the profile switcher.
https://github.com/bitwarden/ios/assets/126492398/b144c77e-14e1-495c-8359-416852caf42f …
> BIT-2349: Handle navigating to the vault item selection screen after vault unlock or switching accounts

- BitwardenShared/Core/Autofill/Utilities/Fido2Error.swift
- BitwardenShared/UI/Autofill/Utilities/Fido2UserInterfaceHelper.swift
- BitwardenShared/UI/Autofill/Utilities/Fido2UserInterfaceHelperTests.swift
[[PM-8863]](https://bitwarden.atlassian.net/browse/PM-8863)
Fix CI/CD failure in `main` because of using `.fixture()` which is defined under `if #DEBUG` context. Now the function throws an error until it's implemented.
- ❓ (`:question:`) …
> [PM-8863] Fix CI/CD failure on non-debug build.

- BitwardenShared/Core/Auth/Repositories/TestHelpers/MockAuthRepository.swift
- BitwardenShared/UI/Auth/AuthRouterTests.swift
- BitwardenShared/UI/Auth/Extensions/AuthRouter+Redirects.swift
- BitwardenShared/UI/Platform/Application/Extensions/UITabBarControllerExtensionsTests.swift
[PM-9003](https://bitwarden.atlassian.net/browse/PM-9003)
Fixes an error received on app launch if the account timeout settings are set to never / logout. Previously, this was being considered a timeout but then the never lock setting was bypassing vault unlock, so the vault was never unlocked. This adds an additional check for the never lock setting.
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation …
> PM-9003: Fix never lock with logout action error

- .github/workflows/build.yml
- .github/workflows/test.yml
https://bitwarden.atlassian.net/browse/PM-9695
This adds a step to the workflow that explicitly sets the Xcode version, instead of relying on the default in the [runner](https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md). As the default is currently 15.0.1, that's the version I set to as the default (so there should be no change). …
> [PM-9695] Add step to fix Xcode version instead of relying on the default

- BitwardenShared/UI/Platform/Application/Utilities/Alert/Alert/TestHelpers/Alert+TestHelpers.swift
- BitwardenShared/UI/Platform/Settings/Settings/AccountSecurity/AccountSecurityProcessor.swift
- BitwardenShared/UI/Platform/Settings/Settings/AccountSecurity/AccountSecurityProcessorTests.swift
[PM-9000](https://bitwarden.atlassian.net/browse/PM-9000)
- We needed a way to make sure empty pins would not be sent to the backend.  Verified with the android and the existing xamarin app that we allow the user to press "Submit" on the alert with an empty pin but no actual action is performed with setting the empty pin via the backend.  
- Updated tests to include adding in a pin so the logic would execute as expected and added one to make sure we don't perform logic when passing in an empty pin.
https://github.com/user-attachments/assets/d5687bc1-d279-4c52-8be4-995149a5be84 …
> PM-9000 - User can save empty PIN

- BitwardenShared/Core/Vault/Services/VaultTimeoutService.swift
- BitwardenShared/Core/Vault/Services/VaultTimeoutServiceTests.swift
- BitwardenShared/UI/Platform/Settings/Settings/AccountSecurity/AccountSecurityState.swift
[PM-9002](https://bitwarden.atlassian.net/browse/PM-9002)
Fixes the vault from timing out earlier than it should. We were originally storing the timeout value in seconds, but changed to minutes to support migrating from the MAUI app. This case was missed, and the vault was timing out using the timeout value in seconds rather than minutes.
- 👍 …
> PM-9002: Fix vault early timeout

- BitwardenShared/UI/Platform/Application/Views/FormFields/SliderFieldView.swift
[PM-9117](https://bitwarden.atlassian.net/browse/PM-9117)
Fixes a bug where the generator's length slider was missing on iOS 15 & 16. The `apply` view modifier that is being used to add keypresses for iOS 17+ needs to return a view in all cases which was missing for lower iOS versions.
| -- | -- |
| <img width="839" alt="Screenshot 2024-07-17 at 11 16 29 AM" src="https://github.com/user-attachments/assets/053b57f1-ae06-421f-85ea-109002547130"> | <img width="839" alt="Screenshot 2024-07-17 at 11 18 02 AM" src="https://github.com/user-attachments/assets/67b09059-4c1e-4ca3-9108-7a98392066d0"> |
- Protected functional …
> PM-9117: Fix missing generator slider on iOS 15/16

- BitwardenShared/UI/Platform/Application/Appearance/UI.swift
- BitwardenShared/UI/Tools/Send/Send/SendCoordinator.swift
- BitwardenShared/UI/Vault/Vault/VaultCoordinator.swift
[PM-8797](https://bitwarden.atlassian.net/browse/PM-8797)
Updates the search bar to use Bitwarden localizations rather than the system localization. This ensures the correct localizations are used if the language used in the app is different from the system language.
| --- | --- |
| ![localizations-before 1](https://github.com/user-attachments/assets/1671c850-4c0a-494a-b48e-e5287fc407d5) | ![localizations-after 1](https://github.com/user-attachments/assets/7d53c676-25cb-4cd0-9a37-b3f3d6f5ba06) |
| ![localizations-before 2](https://github.com/user-attachments/assets/ee1e060c-8ff0-4e18-a395-40bdfd47c0ae) | ![localizations-after 2](https://github.com/user-attachments/assets/b338aa63-8927-4bdc-bb05-08e72eeb0303) |
- All formatters and local …
> PM-8797: Use localized strings for search bar and cancel button

- BitwardenShared/Core/Auth/Repositories/AuthRepository.swift
- BitwardenShared/Core/Auth/Repositories/AuthRepositoryTests.swift
- BitwardenShared/Core/Platform/Services/ServiceContainer.swift
- BitwardenShared/Core/Platform/Services/StateService.swift
- BitwardenShared/Core/Platform/Services/StateServiceTests.swift
- BitwardenShared/Core/Platform/Services/TestHelpers/MockStateService.swift
- BitwardenShared/Core/Vault/Services/TestHelpers/MockVaultTimeoutService.swift
- BitwardenShared/Core/Vault/Services/VaultTimeoutService.swift
- BitwardenShared/Core/Vault/Services/VaultTimeoutServiceTests.swift
- BitwardenShared/UI/Autofill/Utilities/Fido2UserInterfaceHelper.swift
- BitwardenShared/UI/Autofill/Utilities/Fido2UserVerificationMediator.swift
- BitwardenShared/UI/Autofill/Utilities/Fido2UserVerificationMediatorTests.swift
[PM-8361](https://bitwarden.atlassian.net/browse/PM-8361)
Added logic to know whether the vault has been unlocked in the current session and applied it to the Fido2 user verification flow.
- 🤔 …
> [PM-8361] Added whether the vault has been unlocked interactively

- BitwardenShared/UI/Tools/Send/Send/SendList/SendListProcessor.swift
- BitwardenShared/UI/Tools/Send/Send/SendList/SendListProcessorTests.swift
[PM-8141](https://bitwarden.atlassian.net/browse/PM-8141)
Fixes a bug where deleting a send in the search results doesn't remove it from the list of search results. The view now subscribes to the search results rather than using a static list.
https://github.com/user-attachments/assets/54e8a195-edce-44db-868e-894b244f75b9 …
> PM-8141: Subscribe to send search results to get updates

- BitwardenShared/Core/Autofill/Utilities/Fido2Error.swift
- BitwardenShared/UI/Auth/Utilities/TestHelpers/MockUserVerificationHelper.swift
- BitwardenShared/UI/Auth/Utilities/UserVerificationHelper.swift
- BitwardenShared/UI/Auth/Utilities/UserVerificationHelperTests.swift
- BitwardenShared/UI/Autofill/Utilities/Fido2UserVerificationMediator.swift
- BitwardenShared/UI/Autofill/Utilities/Fido2UserVerificationMediatorTests.swift
- BitwardenShared/UI/Platform/Application/AppProcessor+Fido2Tests.swift
- BitwardenShared/UI/Platform/Application/AppProcessor.swift
- BitwardenShared/UI/Vault/Vault/AutofillList/VaultAutofillListProcessor.swift
- BitwardenShared/UI/Vault/Vault/AutofillList/VaultAutofillListProcessorTests.swift
[PM-8362](https://bitwarden.atlassian.net/browse/PM-8362)
Implements the set up pin flow for passkey user verification.
Pin set up:
https://github.com/user-attachments/assets/ca19200d-4281-42bb-a9d1-ada74560b861
Pin verification:
https://github.com/user-attachments/assets/ecc1cf73-962e-4a90-b665-99886cb74464 …
> PM-8362: Add pin setup for passkey user verification

- BitwardenShared/UI/Platform/Application/Support/Localizations/en.lproj/Localizable.strings
- BitwardenShared/UI/Platform/Settings/Extensions/Alert+Settings.swift
- BitwardenShared/UI/Platform/Settings/Extensions/AlertSettingsTests.swift
[PM-9836](https://bitwarden.atlassian.net/browse/PM-9836)
Updates the confirmation alert when exporting the vault using the JSON password protected format.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for …
> PM-9836: Update password protected vault export confirmation alert

- BitwardenShared/Core/Autofill/Services/AutofillCredentialService.swift
- BitwardenShared/Core/Autofill/Services/AutofillCredentialServiceTests.swift
- BitwardenShared/Core/Autofill/Services/TestHelpers/MockAutofillCredentialService.swift
- BitwardenShared/Core/Autofill/Services/TestHelpers/MockAutofillCredentialServiceDelegate.swift
- BitwardenShared/UI/Platform/Application/AppProcessor.swift
[PM-9660](https://bitwarden.atlassian.net/browse/PM-9660)
If an account has never lock enabled, this unlocks the vault without user interaction prior to autofilling. This fixes a UI issue where a navigation controller would pop up briefly before the vault was unlocked.
| --- | --- |
| <video src="https://github.com/user-attachments/assets/ef50a363-ff29-4a10-8e39-3fa370b32ba4" /> | <video src="https://github.com/user-attachments/assets/62f8b038-05a6-4c32-b998-4061f0814e54" /> |
- …
> PM-9660: Improve autofill extension flow with never lock

- BitwardenShared/UI/Vault/VaultItem/ViewItem/ViewItemAction.swift
- BitwardenShared/UI/Vault/VaultItem/ViewItem/ViewItemActionTests.swift
[PM-9001](https://bitwarden.atlassian.net/browse/PM-9001)
- Prompt user for a master password when downloading an attachment. Right now we freely allow downloading an attachment without asking for the password. 
https://github.com/user-attachments/assets/dd990020-d5f1-4f7a-aceb-46b736720e10
- 📝 (`:memo:`) or …
> PM-9001 - Item with MP Reprompt does not prompt for MP when downloading attachment

- .github/workflows/build.yml
- .github/workflows/cache-dependencies.yml
- .github/workflows/test.yml
- BitwardenShared/UI/Platform/ExtensionSetup/ExtensionActivation/ExtensionActivationViewTests.swift
- BitwardenShared/UI/Tools/Generator/Generator/GeneratorViewTests.swift
- BitwardenShared/UI/Tools/Send/Send/SendList/SendListViewTests.swift
- README.md
[PM-10137](https://bitwarden.atlassian.net/browse/PM-10137)
Bump the Xcode version to use to 15.4 which is aligned with the default one in Github actions runner image.
**Notes:**
For this to happen we need to disable some snapshot tests that could fail because of 15.4 update. They'll be re-enabled in a next PR. …
> [PM-10137] Update Xcode usage to 15.4

- BitwardenShared/UI/Vault/Vault/VaultCoordinator.swift
[PM-6498](https://bitwarden.atlassian.net/browse/PM-6498)
Fix favicons to be shown on autofill extension …
> [PM-6498] Fix favicons to be shown on autofill extension.

- BitwardenShared/Core/Platform/Services/ServiceContainer.swift
- BitwardenShared/Core/Vault/Repositories/TestHelpers/MockVaultRepository.swift
- BitwardenShared/Core/Vault/Repositories/VaultRepository.swift
- BitwardenShared/Core/Vault/Repositories/VaultRepositoryTests.swift
- BitwardenShared/UI/Platform/Tabs/TabCoordinator.swift
- BitwardenShared/UI/Platform/Tabs/TabCoordinatorTests.swift
- BitwardenShared/UI/Vault/Vault/VaultGroup/VaultGroupProcessor.swift
- BitwardenShared/UI/Vault/Vault/VaultGroup/VaultGroupProcessorTests.swift
- BitwardenShared/UI/Vault/Vault/VaultGroup/VaultGroupState.swift
- BitwardenShared/UI/Vault/Vault/VaultGroup/VaultGroupView.swift
- BitwardenShared/UI/Vault/Vault/VaultList/SearchVaultFilterRowView/SearchVaultFilterRowState.swift
- BitwardenShared/UI/Vault/Vault/VaultList/SearchVaultFilterRowView/SearchVaultFilterRowStateTests.swift
- BitwardenShared/UI/Vault/Vault/VaultList/VaultListProcessor.swift
- BitwardenShared/UI/Vault/Vault/VaultList/VaultListProcessorTests.swift
- BitwardenShared/UI/Vault/Vault/VaultList/VaultListState.swift
- BitwardenShared/UI/Vault/Vault/VaultList/VaultListView.swift
[PM-9155](https://bitwarden.atlassian.net/browse/PM-9155)
If the personal ownership and single organization policies are both enabled, the vault filter should be hidden. …
> PM-9155: Hide the vault filter when personal ownership and single organization policies apply

- BitwardenShared/UI/Platform/Settings/Settings/AccountSecurity/AccountSecurityProcessor.swift
- BitwardenShared/UI/Platform/Settings/Settings/AccountSecurity/AccountSecurityProcessorTests.swift
[PM-9000](https://bitwarden.atlassian.net/browse/PM-9000)
- This was returned from QA because we were still allowing whitespaces as an acceptable pin when validating.  This PR trims whitespaces before checking if the pin is empty or not.  
https://github.com/user-attachments/assets/0161bc40-4739-4d19-ac9e-004ea5db6fcb …
> PM-9000 - User can save empty PIN (whitespaces)

- project.yml
[PM-10127](https://bitwarden.atlassian.net/browse/PM-10127)
- Allow sharing of a file/photo from the iOS Share Menu.  When trying to share we saw a screen flicker but no action was taken place.  Noticed the entitlement was missing from the share extension so added that back in and removed it from the test target.  
- I was seeing a weird issue that causes the app to crash within `DefaultAutofillCredentialService` when trying to send.  The function `replaceAllIdentities(userId:)` was the culprit but this must have been something I had set up locally that was causing the issue because after starting with a fresh build I was not able to replicate this behavior.  If this comes back from QA then further investigation would be required to move the logic that kicks off the task in …
> PM-10127 - Can't Share File or Photo For Send via iOS Share Menu

- .github/workflows/build.yml
https://bitwarden.atlassian.net/browse/PM-10512
This updates the way the build number is calculated on an automatic build, so that instead of GitHub run number plus 1000, it's just the GitHub run number.
- …
> [PM-10512] Update build number calculation to just be GitHub run number

- BitwardenAutoFillExtension/CredentialProviderViewController.swift
- BitwardenShared/Core/Auth/Repositories/AuthRepositoryTests.swift
- BitwardenShared/UI/Autofill/Application/Fido2AppExtensionDelegate.swift
- BitwardenShared/UI/Autofill/Application/TestHelpers/MockFido2AppExtensionDelegate.swift
- BitwardenShared/UI/Platform/Application/AppProcessor+Fido2Tests.swift
- BitwardenShared/UI/Platform/Application/AppProcessor.swift
[PM-10450](https://bitwarden.atlassian.net/browse/PM-10450)
Fix Fido2 flow user verification not appearing when in an account with never lock timeout.
The problem arises because of trying to perform user interaction, e.g. prompting for FaceID, before `viewDidAppear` happens. So as a solution we just for it to happen before continuing with user interaction flows. …
> [PM-10450] Fix FIdo2 never lock user verification not appearing

- BitwardenShared/Core/Vault/Services/TOTP/OTPAuthModel.swift
- BitwardenShared/Core/Vault/Services/TOTP/OTPAuthModelTests.swift
- BitwardenShared/UI/Vault/PreviewContent/String+TOTPFixtures.swift
https://bitwarden.atlassian.net/browse/PM-10080
OTP-auth URLs were still doing base-32 checking on their secrets. This changes that so any secret will be allowed, even if it's not base-32 encoded. In practice, we should never see things that aren't base-32, but since the SDK handles it, it seems reasonable for us to allow it.
- 👍 (`:+1:`) or similar …
> [PM-10080] Don't constrain OTP auth codes to base-32 secrets

- BitwardenShared/Core/Auth/Services/Biometrics/BiometricsRepository.swift
- BitwardenShared/Core/Auth/Services/Biometrics/BiometricsRepositoryTests.swift
[PM-10519](https://bitwarden.atlassian.net/browse/PM-10519)
If the device is locked while performing Face ID, Face ID unlock was being disabled for the account. When Face ID is cancelled because the device locks, the `errSecAuthFailed` error is thrown. This was being converted to a `BiometricsServiceError.getAuthKeyFailed` error, which ends up toggling off Face ID. This changes that to instead throw a `BiometricsServiceError.biometryCancelled` error, similar to the other errors around cancellation. 
- …
> PM-10519: Fix Face ID toggled off if device is locked while performing Face ID

- BitwardenShared/UI/Vault/Vault/AutofillList/VaultAutofillListEffect.swift
- BitwardenShared/UI/Vault/Vault/AutofillList/VaultAutofillListProcessor.swift
- BitwardenShared/UI/Vault/Vault/AutofillList/VaultAutofillListProcessorTests.swift
- BitwardenShared/UI/Vault/Vault/AutofillList/VaultAutofillListView.swift
[PM-6498](https://bitwarden.atlassian.net/browse/PM-6498)
Fix vault autofill showing/hiding website icons. …
> [PM-6498] Fix vault autofill showing/hiding website icons.

- BitwardenShared/UI/Auth/Utilities/UserVerificationHelper.swift
- BitwardenShared/UI/Auth/Utilities/UserVerificationHelperTests.swift
[PM-10487](https://bitwarden.atlassian.net/browse/PM-10487)
Fix cancellation handling on setting up the PIN on Fido2 flows. …
> [PM-10487] Handle cancellation on setting up the PIN on Fido2 flows

- BitwardenShared/Core/Autofill/Services/AutofillCredentialService.swift
- BitwardenShared/Core/Autofill/Services/AutofillCredentialServiceTests.swift
[PM-10539](https://bitwarden.atlassian.net/browse/PM-10539)
Remove all OS Store identities when switching to a locked account. This fixes an issue where the user was changing to a locked account and then trying to autofill which was showing the previous user credentials, and when opening the autofill extension it was failing as the credential was not belonging to the current (locked) user.
https://github.com/user-attachments/assets/f505431f-c792-4eeb-8914-16cd26eee30e
- Communicated to DevOps any …
> [PM-10539] Remove all identities when switching to a locked account

- BitwardenShared/Core/Vault/Helpers/CipherMatchingHelper.swift
- BitwardenShared/Core/Vault/Helpers/CipherMatchingHelperTests.swift
[PM-9849](https://bitwarden.atlassian.net/browse/PM-9849)
Fix ciphers matching filter on autofill extension by sanitizing the URL when it doesn't come from an App. …
> [PM-9849] Fix cipher matching logic to sanitize the URL

- BitwardenShared/Core/Platform/Models/Enum/FeatureFlag.swift
- BitwardenShared/UI/Auth/AuthRouter.swift
- BitwardenShared/UI/Auth/AuthRouterTests.swift
- BitwardenShared/UI/Auth/Extensions/AuthRouter+Redirects.swift
[PM-10517](https://bitwarden.atlassian.net/browse/PM-10517)
Adds support for using the carousel feature flag to determine whether to show the landing or carousel view on app launch. …
> PM-10517: Add feature flag for intro carousel

- BitwardenShared/Core/Autofill/Services/AutofillCredentialService.swift
- BitwardenShared/Core/Autofill/Services/AutofillCredentialServiceTests.swift
- BitwardenShared/UI/Autofill/Utilities/Fido2UserInterfaceHelper.swift
- BitwardenShared/UI/Autofill/Utilities/Fido2UserInterfaceHelperTests.swift
- BitwardenShared/UI/Autofill/Utilities/TestHelpers/MockFido2UserInterfaceHelper.swift
- BitwardenShared/UI/Vault/Vault/AutofillList/VaultAutofillListProcessor+Fido2Tests.swift
- BitwardenShared/UI/Vault/Vault/AutofillList/VaultAutofillListProcessor.swift
[PM-10487](https://bitwarden.atlassian.net/browse/PM-10487)
Fix Fido2 creation when no OS Biometrics nor Passcode is configured and the user has Never lock timeout.
As the SDK doesn't send the user verification preference for `isVerificationEnabled` I've workaround it by setting it up in the `Fido2UserVerificationHelper` directly to have it there when the method is triggered and be able to compare and trigger the appropriate logic for each value.
- …
> [PM-10487] Fix Fido2 creation when no OS Unlock configured

- Bitwarden/Application/Support/Assets.xcassets/BackgroundColors/backgroundSplash.colorset/Contents.json
- Bitwarden/Application/Support/Assets.xcassets/TintColors/tintSplash.colorset/Contents.json
- Bitwarden/Application/Support/Resources/LaunchScreen.storyboard
[PM-10281](https://bitwarden.atlassian.net/browse/PM-10281)
Updates the colors on the splash screen in light mode to have a Bitwarden blue logo with a white background.
| Light | Dark |
| --- | --- |
| <img width="559" alt="Screenshot 2024-08-07 at 12 04 06 PM" src="https://github.com/user-attachments/assets/6c2df90f-4d36-4770-a8a8-38bf02427b3f"> | <img width="559" alt="Screenshot 2024-08-07 at 12 05 07 PM" src="https://github.com/user-attachments/assets/250eed49-b50a-418f-b74a-e9e8eb63d7c1"> |
- …
> PM-10281: Update splash screen colors

- BitwardenShared/Core/Platform/Services/StateService.swift
- BitwardenShared/Core/Platform/Services/StateServiceTests.swift
- BitwardenShared/Core/Platform/Services/Stores/AppSettingsStore.swift
- BitwardenShared/Core/Platform/Services/Stores/AppSettingsStoreTests.swift
- BitwardenShared/Core/Platform/Services/Stores/TestHelpers/MockAppSettingsStore.swift
- BitwardenShared/Core/Platform/Services/TestHelpers/MockStateService.swift
- BitwardenShared/UI/Auth/AuthRouterTests.swift
- BitwardenShared/UI/Auth/Extensions/AuthRouter+Redirects.swift
[PM-10639](https://bitwarden.atlassian.net/browse/PM-10639)
Adds the logic to determine when to show the intro carousel. If the feature is enabled, and there's no accounts on the device, the intro carousel should be shown on app launch. Once the user successfully creates an account or logs in, the carousel won't be shown on future app launches.
- 👍 …
> PM-10639: Implement conditional logic for showing the intro carousel

- BitwardenShared/Core/Auth/Services/Biometrics/BiometricsRepository.swift
- BitwardenShared/Core/Auth/Services/Biometrics/BiometricsRepositoryTests.swift
- BitwardenShared/Core/Platform/Services/TestHelpers/MockStateService.swift
- BitwardenShared/UI/Auth/VaultUnlockSetup/VaultUnlockSetupProcessor.swift
- BitwardenShared/UI/Auth/VaultUnlockSetup/VaultUnlockSetupProcessorTests.swift
- BitwardenShared/UI/Auth/VaultUnlockSetup/VaultUnlockSetupState.swift
- BitwardenShared/UI/Auth/VaultUnlockSetup/VaultUnlockSetupViewTests.swift
- BitwardenShared/UI/Platform/Settings/Settings/AccountSecurity/AccountSecurityProcessor.swift
- BitwardenShared/UI/Platform/Settings/Settings/AccountSecurity/AccountSecurityProcessorTests.swift
[PM-10271](https://bitwarden.atlassian.net/browse/PM-10271)
On the set up unlock view, this enables toggling the Face/Touch ID toggle for turning biometrics unlock on or off.
https://github.com/user-attachments/assets/0f274056-342b-4403-b565-68776a98912e
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes …
> PM-10271: Set up unlock: allow configuring biometrics

- .github/workflows/CI-main.yml
- .github/workflows/build.yml
https://bitwarden.atlassian.net/browse/PM-10838
This expands the `build.yml` workflow to be callable, and migrates building-on-pushes-to-main from it to `ci-main.yml`, which will call `build.yml` for those builds using a matrix strategy.
Unfortunately, we'll need to push the build numbers up to avoid conflicts for the time being.
- 👍 (`:+1:`) or …
> [PM-10838] Use CI-main for regular builds to production and beta

- BitwardenShared/Core/Platform/Models/Enum/FeatureFlag.swift
- BitwardenShared/Core/Platform/Services/API/Fixtures/ValidServerConfig.json
- BitwardenShared/Core/Platform/Services/ConfigService.swift
- BitwardenShared/Core/Platform/Services/ConfigServiceTests.swift
[PM-10893](https://bitwarden.atlassian.net/browse/PM-10893)
Adds a property to feature flags to prevent them from being configured remotely. Since some features are developed behind feature flags, when the flag is ready to be enabled, there may be previous app versions in use that have that flag but are not feature complete. This ensures that feature flags can only enabled on app versions after we allow remote configuration.  …
> PM-10893: Add option to prevent feature flags from being configured remotely

- BitwardenShared/UI/Vault/VaultItem/AddEditItem/AddEditItemProcessor.swift
- BitwardenShared/UI/Vault/VaultItem/LoginTOTPState.swift
- BitwardenShared/UI/Vault/VaultItem/LoginTOTPStateTests.swift
https://bitwarden.atlassian.net/browse/PM-10542
When a TOTP was removed from a login entry that had one, the app was saving the TOTP as an empty string rather than nil; as well, if asked to generate a code for an empty string, it would assume it a valid key and generate it. This change adjusts this so that empty and whitespace-only strings coalesce into nil values. Some tests around this are also added. …
> [PM-10542] Handle TOTP codes with empty or whitespace-only keys

- BitwardenShared/Core/Auth/Models/Request/PostKeyConnectorUserKeyRequestModel.swift
- BitwardenShared/Core/Auth/Models/Request/SetKeyConnectorKeyRequestModel.swift
- BitwardenShared/Core/Auth/Models/Response/KeyConnectorUserKeyResponseModel.swift
- BitwardenShared/Core/Auth/Models/Response/KeyConnectorUserKeyResponseModelTests.swift
- BitwardenShared/Core/Auth/Services/API/Account/AccountAPIService.swift
- BitwardenShared/Core/Auth/Services/API/Account/AccountAPIServiceTests.swift
- BitwardenShared/Core/Auth/Services/API/Account/Requests/ConvertToKeyConnectorRequest.swift
- BitwardenShared/Core/Auth/Services/API/Account/Requests/ConvertToKeyConnectorRequestTests.swift
- BitwardenShared/Core/Auth/Services/API/Account/Requests/SetKeyConnectorKeyRequest.swift
- BitwardenShared/Core/Auth/Services/API/Account/Requests/SetKeyConnectorKeyRequestTests.swift
- BitwardenShared/Core/Auth/Services/API/KeyConnector/Fixtures/APITestData+KeyConnector.swift
- BitwardenShared/Core/Auth/Services/API/KeyConnector/Fixtures/KeyConnectorUserKey.json
- BitwardenShared/Core/Auth/Services/API/KeyConnector/KeyConnectorAPIService.swift
- BitwardenShared/Core/Auth/Services/API/KeyConnector/KeyConnectorAPIServiceTests.swift
- BitwardenShared/Core/Auth/Services/API/KeyConnector/Requests/KeyConnectorUserKeyRequest.swift
- BitwardenShared/Core/Auth/Services/API/KeyConnector/Requests/KeyConnectorUserKeyRequestTests.swift
- BitwardenShared/Core/Auth/Services/API/KeyConnector/Requests/PostKeyConnectorUserKeyRequest.swift
- BitwardenShared/Core/Auth/Services/API/KeyConnector/Requests/PostKeyConnectorUserKeyRequestTests.swift
- BitwardenShared/Core/Auth/Services/API/Organization/OrganizationAPIService.swift
- BitwardenShared/Core/Auth/Services/API/Organization/OrganizationAPIServiceTests.swift
- BitwardenShared/Core/Auth/Services/API/Organization/Requests/LeaveOrganizationRequest.swift
- BitwardenShared/Core/Auth/Services/API/Organization/Requests/LeaveOrganizationRequestTests.swift
- BitwardenShared/Core/Platform/Services/API/APIService.swift
- BitwardenShared/Core/Platform/Services/API/APIServiceTests.swift
[PM-10945](https://bitwarden.atlassian.net/browse/PM-10945)
Adds the following API requests needed to implement key connector:
- `GET {key-connector-url}/user-keys`
- `POST {key-connector-url}/user-keys`
- `POST /accounts/convert-to-key-connector`
- `POST /accounts/set-key-connector-key`
- `POST /organizations/{id}/leave` …
> PM-10945: Add Key Connector API requests

- BitwardenShared/UI/Auth/AuthCoordinatorTests.swift
- BitwardenShared/UI/Auth/AuthModule.swift
- BitwardenShared/UI/Auth/AuthRouter.swift
- BitwardenShared/UI/Auth/AuthRouterTests.swift
- BitwardenShared/UI/Auth/Extensions/AuthRouter+Redirects.swift
https://bitwarden.atlassian.net/browse/PM-10977
This prevents the welcome carousel from being displayed when using the app as an extension (e.g. for autofill).
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) …
> [PM-10977] Don't show welcome carousel when in an extension

- Bitwarden/Application/UIApplication+Application.swift
- BitwardenShared/Core/Platform/Services/Application.swift
- BitwardenShared/Core/Platform/Services/TestHelpers/MockApplication.swift
- BitwardenShared/UI/Platform/Application/AppProcessor.swift
https://bitwarden.atlassian.net/browse/PM-11189
Xcode 15 and 16 have different signatures for `UIApplication.beginBackgroundTask(::)` due to changes in Swift Concurrency, and that was preventing the app from building in Xocde 16.
This does not fix tests, however—that will have to wait until a new version of [ViewInspector](https://github.com/nalexn/ViewInspector) to be released. This work is captured in [PM-11213](https://bitwarden.atlassian.net/browse/PM-11213).
This is part of the broader effort to get the app ready for iOS 18, Xcode 16, and Swift 6
- Used …
> [PM-11189] Allow app to build in Xcode 16

- BitwardenShared/Core/Auth/Models/Request/VerifyEmailTokenRequestModel.swift
- BitwardenShared/Core/Auth/Services/API/Account/AccountAPIService.swift
- BitwardenShared/Core/Auth/Services/API/Account/AccountAPIServiceTests.swift
- BitwardenShared/Core/Auth/Services/API/Account/Fixtures/APITestData+Account.swift
- BitwardenShared/Core/Auth/Services/API/Account/Fixtures/VerifyEmailTokenExpiredLink.json
- BitwardenShared/Core/Auth/Services/API/Account/Requests/VerifyEmailTokenRequest.swift
- BitwardenShared/Core/Auth/Services/API/Account/Requests/VerifyEmailTokenRequestTests.swift
https://bitwarden.atlassian.net/browse/PM-9842
Add services to verify if token received by email is still valid. Can return error if the token is expired or user is already registered.
- 🤔 (`:thinking:`) …
> [PM-9842] Verify email token services

- BitwardenShared/UI/Auth/Login/LoginView.swift
- BitwardenShared/UI/Platform/Application/Appearance/Modifiers/ScaledFrame.swift
- BitwardenShared/UI/Platform/Application/Appearance/Styles/AccessoryButtonStyle.swift
- BitwardenShared/UI/Platform/Application/Appearance/Styles/PrimaryButtonStyle.swift
- BitwardenShared/UI/Platform/Application/Views/BitwardenMenuField.swift
- BitwardenShared/UI/Platform/Application/Views/BitwardenTextField.swift
- BitwardenShared/UI/Platform/Application/Views/BitwardenTextValueField.swift
- BitwardenShared/UI/Vault/VaultItem/AddEditItem/AddEditIdentityItem/AddEditIdentityItemView.swift
- BitwardenShared/UI/Vault/VaultItem/ViewItem/ViewIdentityItem/ViewIdentityItemView.swift
https://bitwarden.atlassian.net/browse/PM-11133
As of Xcode 16 and Swift 6, using `.previewDisplayName` and `.previewLayout` in a `#Preview` macro produces a warning. This updates all those instances in the code to the macro-ized form.
This does not fully complete PM-11133, but is a step along the way.
- 📝 …
> [PM-11133] Fix preview macro warnings

- Networking/Package.swift
- Networking/Sources/Networking/Extensions/Logger+Networking.swift
- Networking/Sources/Networking/HTTPMethod.swift
- Networking/Sources/Networking/HTTPResponse.swift
https://bitwarden.atlassian.net/browse/PM-11133
This is part of the iOS 18 / Xcode 16 / Swift 6 effort
This updates our Networking module to have no warnings with strict concurrency checking turned on, and also annotates `Sendable` to eliminate warnings in the main project. …
> [PM-11133] Update Networking module for strict concurrency

- BitwardenShared/Core/Platform/Models/Enum/FeatureFlag.swift
[PM-11222](https://bitwarden.atlassian.net/browse/PM-11222)
Allows the email verification flag to be remotely configured. …
> PM-11222: Allow email verification feature flag to be remotely configured

- BitwardenShared/Core/Vault/Services/SyncService.swift
- BitwardenShared/Core/Vault/Services/SyncServiceTests.swift
[PM-11253](https://bitwarden.atlassian.net/browse/PM-11253)
This fixes a bug where the set master password screen is shown for a key connector user upon sync. This screen should only be shown as part of sync for TDE users who need a password but don't yet have one. …
> PM-11253: Don't trigger set master password for non-TDE users on sync

- Bitwarden/Application/AppDelegate.swift
- BitwardenShared/UI/Auth/Login/LoginProcessor.swift
- BitwardenShared/UI/Auth/Login/SingleSignOn/SingleSignOnProcessor.swift
- BitwardenShared/UI/Auth/Login/TwoFactorAuth/TwoFactorAuthProcessor.swift
- BitwardenShared/UI/Autofill/Application/Fido2AppExtensionDelegate.swift
- BitwardenShared/UI/Autofill/Application/Fido2AppExtensionDelegateTests.swift
- BitwardenShared/UI/Platform/Application/AppExtensionDelegate.swift
- BitwardenShared/UI/Platform/Application/AppProcessor+Fido2Tests.swift
- BitwardenShared/UI/Platform/Application/Utilities/Coordinator.swift
- BitwardenShared/UI/Platform/LoginRequest/LoginRequestProcessor.swift
- BitwardenShared/UI/Platform/Settings/Settings/Appearance/SelectLanguage/SelectLanguageProcessor.swift
- BitwardenShared/UI/Platform/Settings/Settings/AutoFill/AppExtension/AppExtensionProcessor.swift
- BitwardenShared/UI/Platform/Settings/Settings/Vault/Folders/AddEditFolder/AddEditFolderProcessor.swift
- BitwardenShared/UI/Platform/Tabs/TabModule.swift
- BitwardenShared/UI/Vault/Helpers/AutofillHelperTests.swift
- BitwardenShared/UI/Vault/Vault/AutofillList/VaultAutofillListProcessor+Fido2Tests.swift
- BitwardenShared/UI/Vault/VaultItem/AddEditItem/AddEditItemProcessor.swift
- BitwardenShared/UI/Vault/VaultItem/AddEditItem/Extensions/ForEachIndexed.swift
- BitwardenShared/UI/Vault/VaultItem/EditCollections/EditCollectionsProcessor.swift
- BitwardenShared/UI/Vault/VaultItem/MoveToOrganization/MoveToOrganizationProcessor.swift
https://bitwarden.atlassian.net/browse/PM-11133
This is part of the iOS 18 / Xcode 16 / Swift 6 effort
This adds `@MainActor` annotations to a number of protocols to eliminate Swift 6 errors. On the whole, these are delegate protocols between a `Processor` (which is `@MainActor`) and a `Coordinator` (which is `@MainActor`).
- 👍 (`:+1:`) or similar …
> [PM-11133] Expand MainActor annotations

- BitwardenShared/Core/Auth/Services/Biometrics/BiometricsRepository.swift
- BitwardenShared/Core/Auth/Services/Biometrics/BiometricsRepositoryTests.swift
- BitwardenShared/Core/Auth/Services/Biometrics/BiometricsService.swift
- BitwardenShared/Core/Auth/Services/TestHelpers/MockBiometricsRepository.swift
- BitwardenShared/UI/Platform/Application/Support/Localizations/en.lproj/Localizable.strings
- BitwardenShared/UI/Platform/Settings/Extensions/Alert+Settings.swift
- BitwardenShared/UI/Platform/Settings/Extensions/AlertSettingsTests.swift
- BitwardenShared/UI/Platform/Settings/Settings/AccountSecurity/AccountSecurityProcessor.swift
- BitwardenShared/UI/Platform/Settings/Settings/AccountSecurity/AccountSecurityProcessorTests.swift
[PM-585](https://bitwarden.atlassian.net/browse/PM-585)
Improve text when setting unlock with PIN on app restart to say that it can be with biometrics or master password. …
> [PM-585] Improved text when setting unlock with PIN on app restart

- BitwardenShared/Core/Auth/Repositories/AuthRepository.swift
- BitwardenShared/Core/Auth/Repositories/AuthRepositoryTests.swift
- BitwardenShared/Core/Platform/Services/KeyConnectorService.swift
- BitwardenShared/Core/Platform/Services/KeyConnectorServiceTests.swift
- BitwardenShared/Core/Platform/Services/StateService.swift
- BitwardenShared/Core/Platform/Services/StateServiceTests.swift
- BitwardenShared/Core/Platform/Services/TestHelpers/MockStateService.swift
[PM-11297](https://bitwarden.atlassian.net/browse/PM-11297)
After a user removes their master password and migrates to Key Connector, we should set their `hasMasterPassword` flag to false so that their timeout action is updated along with other actions that require the user’s master password (delete account, export vault, etc should use OTP).
- 👍 …
> PM-11297: Set hasMasterPassword flag to false after migrating user to Key Connector

- .github/workflows/build.yml
https://bitwarden.atlassian.net/browse/PM-11347
This adds the version of Xcode a build was made with in the tester notes in TestFlight. When we start building the app with multiple versions of Xcode (primarily Beta Xcode versions), this will help people looking at TestFlight identify which version exactly they want to use. …
> [PM-11347] Include Xcode version in tester notes

- BitwardenShared/Core/Platform/Models/Enum/FeatureFlag.swift
[PM-11426](https://bitwarden.atlassian.net/browse/PM-11426)
Given that there's still some work to do for email verification, this disables the feature flag to prevent it from being configured remotely.
- 🤔 …
> PM-11426: Disable email verification flag from being configured remotely

- BitwardenShared/Core/Platform/Services/ConfigService.swift
- BitwardenShared/Core/Platform/Services/ConfigServiceTests.swift
[PM-11420](https://bitwarden.atlassian.net/browse/PM-11420)
Fix issue where the app was taking a lot of time to open appearing to be frozen on the splash screen when having poor connectivity.
This was done by moving to background getting the config from server when is not being forced to refresh. So now the `AppProcessor` and any other place (where the caller doesn't force refresh) are getting the local config immediately and getting the server config on a background task so it's available for the next time is requested.
- …
> [PM-11420] Fix app taking long time to open on poor connectivity.

- BitwardenShared/Core/Platform/Services/ConfigServiceTests.swift
- BitwardenShared/UI/Auth/AuthRoute.swift
- BitwardenShared/UI/Vault/Vault/VaultList/VaultListProcessorTests.swift
- BitwardenShared/UI/Vault/Vault/VaultList/VaultListState.swift
- BitwardenShared/UI/Vault/Vault/VaultList/VaultListView.swift
[PM-11473](https://bitwarden.atlassian.net/browse/PM-11473)
Fixes an issue where changing the vault filter in the vault list would filter the vault items but wouldn't update the title of the filter row. The filter state used to draw that row was being shared between the list and search filters, but these should have been separate states.
| Before | After | 
| --- | --- |
| <video src="https://github.com/user-attachments/assets/76e2ee95-3acf-411b-a3a2-3dba231aab7e" > | <video src="https://github.com/user-attachments/assets/a07094ed-981c-4045-84a8-440af3fece7a" > |
- Used …
> PM-11473: Fix vault list filter title not updating

- BitwardenShared/UI/Auth/Login/SingleSignOn/SingleSignOnProcessor.swift
- BitwardenShared/UI/Auth/Login/SingleSignOn/SingleSignOnProcessorTests.swift
[PM-11434](https://bitwarden.atlassian.net/browse/PM-11434)
Previously, we were only persisting the SSO org identifier if you completed SSO and were immediately taken to vault unlock. This changes that to also persist this if the user is redirected to two factor, set/update master password, or the TDE login options. …
> PM-11434: Remember SSO org identifier even if redirected

- BitwardenShared/Core/Vault/Services/PolicyService.swift
- BitwardenShared/Core/Vault/Services/PolicyServiceTests.swift
https://bitwarden.atlassian.net/browse/PM-11373
PasswordGenerator policies are not being enforced to owners, admins and users that have access to policies. All users should have the password generator policies applied.
- ❓ (`:question:`) …
> [PM-11373] passwordGenerator policy should not exempt organization from policies

- BitwardenShared/Core/Platform/Services/MigrationService.swift
- BitwardenShared/Core/Platform/Services/MigrationServiceTests.swift
- BitwardenShared/Core/Platform/Services/ServiceContainer.swift
[PM-11653](https://bitwarden.atlassian.net/browse/PM-11653)
Adds a migration to migrate any integrity state values from MAUI for the app extensions. We were previously doing this for the app, but not the extensions. …
> PM-11653: Migrate app extension integrity state values for biometrics

- project.yml
[PM-11710](https://bitwarden.atlassian.net/browse/PM-11710)
Fix Cryptographic error on login by updating the SDK reference which instead of throwing InvalidKey error, it ignores it. …
> [PM-11710] Updated SDK reference

- BitwardenShared/Core/Auth/Repositories/AuthRepository.swift
- BitwardenShared/Core/Auth/Repositories/AuthRepositoryTests.swift
- BitwardenShared/UI/Auth/AuthRouter.swift
- BitwardenShared/UI/Auth/AuthRouterTests.swift
- BitwardenShared/UI/Auth/Extensions/AuthRouter+Redirects.swift
[PM-11720](https://bitwarden.atlassian.net/browse/PM-11720)
- When a user doesn't have a MP set but has a TDE account, they should be brought to a SSO flow (if biometrics are enabled to authenticate). 
- 🤔 …
> PM-11720 - TDE User Without MP Cannot Enable Autofill For Account

- BitwardenShared/Core/Auth/Repositories/AuthRepository.swift
- BitwardenShared/Core/Auth/Repositories/AuthRepositoryTests.swift
- BitwardenShared/Core/Auth/Repositories/TestHelpers/MockAuthRepository.swift
- BitwardenShared/Core/Auth/Services/AuthService.swift
- BitwardenShared/Core/Platform/Services/ClientService.swift
- BitwardenShared/Core/Platform/Services/ClientServiceTests.swift
- BitwardenShared/Core/Platform/Services/ErrorReporter/BitwardenError.swift
- BitwardenShared/Core/Platform/Services/TestHelpers/MockClientService.swift
- BitwardenShared/UI/Auth/CompleteRegistration/CompleteRegistrationProcessor.swift
- BitwardenShared/UI/Auth/CompleteRegistration/CompleteRegistrationProcessorTests.swift
- BitwardenShared/UI/Auth/CreateAccount/CreateAccountProcessor.swift
- BitwardenShared/UI/Auth/CreateAccount/CreateAccountProcessorTests.swift
- BitwardenShared/UI/Platform/Settings/Settings/Vault/ExportVault/ExportVaultProcessor.swift
- BitwardenShared/UI/Platform/Settings/Settings/Vault/ExportVault/ExportVaultProcessorTests.swift
[PM-11697](https://bitwarden.atlassian.net/browse/PM-11697)
When creating a new account on a device that has at least one existing account, it's possible for the app to crash when checking the strength of the new account's password.
The root cause is that `DefaultClientService` maintains a cache of the SDK client as a dictionary, mapping a user ID to their SDK. It's possible for this dictionary to be modified from multiple threads. Making the service an actor fixes the concurrency issue.
I also noticed another issue here. When adding a new account, a user ID doesn't exist for the account yet, so we have some logic that returns a new SDK for these calls, and this SDK doesn't end up being cached. If there's an existing account on the device when adding a new account, that existing account …
> PM-11697: Fix potential crash when creating a new account

- Bitwarden/Application/Support/Settings.bundle/Acknowledgements.plist
- Bitwarden/Application/Support/Settings.bundle/Acknowledgements/SwiftUI-Introspect.plist
- BitwardenShared/UI/Platform/Application/Views/BitwardenTextField.swift
- project.yml
[PM-11740](https://bitwarden.atlassian.net/browse/PM-11740)
Smart punctuation was acting into password fields (unmasked) so when the user wanted to input two dashes in a row, it was being transformed into a dash. This disables smart dashes so the automatic transformation is not applied.
This PR adds [SwiftUI-Introspect](https://github.com/siteline/swiftui-introspect) package in order to be able to change the [smartDashesType](https://developer.apple.com/documentation/uikit/uitextinputtraits/2866013-smartdashestype) given that it's not directly available in the SwiftUI TextField. 
- Protected functional changes with optionality (feature …
> [PM-11740] Fix to disable smart dashes in password field

- BitwardenShared/Core/Platform/Models/Enum/FeatureFlag.swift
[BITAU-159](https://livefront.atlassian.net/browse/BITAU-159)
This PR brings the feature flag key inline with the naming we just discussed in our feature flag meeting - `enable-authenticator-sync-ios`.
- 🤔 …
> [BITAU-159] Authenticator Sync Feature Flag Name Change

- BitwardenShared/Core/Auth/Services/Biometrics/BiometricsRepository.swift
- BitwardenShared/Core/Auth/Services/Biometrics/BiometricsRepositoryTests.swift
- BitwardenShared/Core/Platform/Services/ErrorReporter/BitwardenError.swift
- BitwardenShared/UI/Auth/VaultUnlock/VaultUnlockProcessor.swift
- BitwardenShared/UI/Auth/VaultUnlock/VaultUnlockProcessorTests.swift
[PM-11883](https://bitwarden.atlassian.net/browse/PM-11883)
This improves the handling of errors during Face ID unlock to hopefully fix the issue of Face ID being deactivated due to any errors other than the auth key not being found. `BiometricsServiceError.getAuthKeyFailed` was being thrown for any unhandled errors, but this is also used to determine if Face ID should be deactivated if the auth key doesn't exist. This also adds error logging to Crashlytics for the `getAuthKeyFailed` and other errors to give more context if this doesn't solve the issue.
- Used …
> PM-11883: Improve handling of biometric unlock errors

- BitwardenShared/Core/Auth/Repositories/AuthRepository.swift
- BitwardenShared/Core/Auth/Repositories/AuthRepositoryTests.swift
[PM-11979](https://bitwarden.atlassian.net/browse/PM-11979)
If a user has PIN unlock enabled without requiring a master password on app restart, the unlocking with a PIN should configure biometric integrity if needed so biometrics can be used on future extension invocations.
https://github.com/user-attachments/assets/7b16368f-3ff4-43ec-859a-5f4784d9d502
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation …
> PM-11979: Allow PIN unlock to configure biometric integrity if needed

- Package.swift
[BITAU-171](https://livefront.atlassian.net/browse/BITAU-171)
In the previous PR, I missed the Package.swift reference that exposes the package name. This PR is simply to fix that one file to expose the correct name - `AuthenticatorBridgeKit` …
> [BITAU-171] Fix SPM Package file to expose the correct name - AuthenticatorBridgeKit

- BitwardenShared/Core/Auth/Repositories/AuthRepository.swift
- BitwardenShared/Core/Auth/Repositories/AuthRepositoryTests.swift
[PM-10740](https://bitwarden.atlassian.net/browse/PM-10740)
This fixes an issue where the user has PIN unlock enabled, but it's toggled off in the app's settings.
The following conditions need to be true for this:
- PIN unlock is enabled and MP is required upon app restart.
- Biometrics unlock is also enabled. 
When the app restarts, unlocking with biometrics instead of MP causes the PIN unlock toggle to be turned off. When unlocking with biometrics, we weren't deriving the user's pin key and storing it in memory so it could be used to unlock the user's vault with their PIN.
- …
> PM-10740: Configure PIN key after biometrics unlock if require unlocking with MP

- BitwardenShared/UI/Vault/Vault/AutofillList/VaultAutofillListView.swift
[PM-11522](https://bitwarden.atlassian.net/browse/PM-11522)
- Aligned the logic in VaultListView for showing and hiding the search view. 
- Collaborated with @matt-livefront, who was able to replicate the issue, and confirmed that syncing the view logic resolved the problem. …
> PM-11522 - Large gap at the top of the autofill list after canceling a search

- .github/workflows/_version.yml
- .github/workflows/dispatch-and-download/action.yml
https://bitwarden.atlassian.net/browse/PM-10877
First step in moving version calculation to it's own file. Also adds a new composite action to dispatch, wait and download artifacts from other workflows. We need these in `main` before we're able to use them in our existing build related workflows.
- 📝 …
> [PM-10877] New workflows for version calculation and workflow dispatch

- BitwardenShared/Core/Platform/Services/StateService.swift
- BitwardenShared/Core/Platform/Services/StateServiceTests.swift
- BitwardenShared/Core/Platform/Services/Stores/AppSettingsStore.swift
- BitwardenShared/Core/Platform/Services/Stores/AppSettingsStoreTests.swift
- BitwardenShared/Core/Platform/Services/Stores/TestHelpers/MockAppSettingsStore.swift
- BitwardenShared/Core/Platform/Services/TestHelpers/MockStateService.swift
- BitwardenShared/UI/Auth/AuthCoordinator.swift
- BitwardenShared/UI/Auth/AuthRoute.swift
- BitwardenShared/UI/Auth/Extensions/Alert+Auth.swift
- BitwardenShared/UI/Auth/Extensions/AlertAuthTests.swift
- BitwardenShared/UI/Auth/VaultUnlockSetup/VaultUnlockSetupAction.swift
- BitwardenShared/UI/Auth/VaultUnlockSetup/VaultUnlockSetupEffect.swift
- BitwardenShared/UI/Auth/VaultUnlockSetup/VaultUnlockSetupProcessor.swift
- BitwardenShared/UI/Auth/VaultUnlockSetup/VaultUnlockSetupProcessorTests.swift
- BitwardenShared/UI/Auth/VaultUnlockSetup/VaultUnlockSetupView.swift
- BitwardenShared/UI/Auth/VaultUnlockSetup/VaultUnlockSetupViewTests.swift
- BitwardenShared/UI/Platform/Application/Support/Localizations/en.lproj/Localizable.strings
[PM-10270](https://bitwarden.atlassian.net/browse/PM-10270)
Adds support for setting up an unlock method later. Tapping the "Set up later" button will show an alert asking the user to confirm that they want to set up unlock later.
I also added a `needsVaultUnlockSetup` key in user defaults to determine whether the user has finished setting up unlock. A future PR will set this when the account is created, and then this can be used to determine whether to prompt the user at a future time to set up unlock methods.
- CI builds …
> PM-10270: Set up unlock later

- BitwardenShared/Core/Platform/Models/Domain/EnvironmentUrlData.swift
- BitwardenShared/Core/Platform/Models/Domain/EnvironmentUrlDataTests.swift
- BitwardenShared/Core/Platform/Models/Domain/EnvironmentUrls.swift
- BitwardenShared/Core/Platform/Models/Domain/EnvironmentUrlsTests.swift
- BitwardenShared/Core/Platform/Services/EnvironmentServiceTests.swift
- BitwardenShared/Core/Tools/Repositories/SendRepository.swift
- BitwardenShared/Core/Tools/Repositories/SendRepositoryTests.swift
[PM-12242](https://bitwarden.atlassian.net/browse/PM-12242)
Update default US and EU region URLs to not use append suffix logic as in Self-host but fixed set URLs.
Check [MAUI code](https://github.com/bitwarden/mobile/blob/main/src/Core/Models/Data/EnvironmentUrlData.cs#L9) as reference. …
> [PM-12242] Updated default US and EU region URLs

- BitwardenShared/Core/Auth/Services/API/Auth/Fixtures/APITestData+Auth.swift
- BitwardenShared/Core/Platform/Services/StateService.swift
- BitwardenShared/Core/Platform/Services/StateServiceTests.swift
- BitwardenShared/Core/Platform/Services/Stores/AppSettingsStore.swift
- BitwardenShared/Core/Platform/Services/Stores/AppSettingsStoreTests.swift
- BitwardenShared/Core/Platform/Services/Stores/TestHelpers/MockAppSettingsStore.swift
- BitwardenShared/Core/Platform/Services/TestHelpers/MockStateService.swift
- BitwardenShared/UI/Auth/CompleteRegistration/CompleteRegistrationProcessor.swift
- BitwardenShared/UI/Auth/CompleteRegistration/CompleteRegistrationProcessorTests.swift
- BitwardenShared/UI/Auth/StartRegistration/StartRegistrationProcessor.swift
- BitwardenShared/UI/Auth/StartRegistration/StartRegistrationProcessorTests.swift
- BitwardenShared/UI/Platform/Application/Support/Localizations/en.lproj/Localizable.strings
[PM-12012](https://bitwarden.atlassian.net/browse/PM-12012)
This update addresses an issue with the account creation process, which is divided into two steps. Currently, users can change the application region before completing the second step, potentially leading to registration in a different environment from where they began.
To resolve this, we are now saving pre-authentication URLs alongside the email address in the application state. These URLs will be loaded when the user initiates the completion of their registration, ensuring a consistent experience throughout the process.
https://github.com/user-attachments/assets/8930d4c3-f436-4693-9d2a-cae4b1828184
- Written new unit and / or integration …
> [PM-12012] Save region during account creation

- BitwardenShared/Core/Auth/Services/AuthService.swift
- BitwardenShared/Core/Auth/Services/AuthServiceTests.swift
- BitwardenShared/Core/Auth/Services/TestHelpers/MockAuthService.swift
- BitwardenShared/Core/Platform/Models/Enum/AccountSetupProgress.swift
- BitwardenShared/Core/Platform/Services/StateService.swift
- BitwardenShared/Core/Platform/Services/StateServiceTests.swift
- BitwardenShared/Core/Platform/Services/Stores/AppSettingsStore.swift
- BitwardenShared/Core/Platform/Services/Stores/AppSettingsStoreTests.swift
- BitwardenShared/Core/Platform/Services/Stores/TestHelpers/MockAppSettingsStore.swift
- BitwardenShared/Core/Platform/Services/TestHelpers/MockStateService.swift
- BitwardenShared/UI/Auth/AuthCoordinator.swift
- BitwardenShared/UI/Auth/AuthCoordinatorTests.swift
- BitwardenShared/UI/Auth/AuthRoute.swift
- BitwardenShared/UI/Auth/AuthRouterTests.swift
- BitwardenShared/UI/Auth/CompleteRegistration/CompleteRegistrationProcessor.swift
- BitwardenShared/UI/Auth/CompleteRegistration/CompleteRegistrationProcessorTests.swift
- BitwardenShared/UI/Auth/Extensions/AuthRouter+Redirects.swift
- BitwardenShared/UI/Auth/Login/LoginProcessor.swift
- BitwardenShared/UI/Auth/Login/LoginProcessorTests.swift
- BitwardenShared/UI/Auth/Login/LoginState.swift
- BitwardenShared/UI/Auth/VaultUnlockSetup/VaultUnlockSetupProcessor.swift
- BitwardenShared/UI/Auth/VaultUnlockSetup/VaultUnlockSetupProcessorTests.swift
[PM-10524](https://bitwarden.atlassian.net/browse/PM-10524)
Adds support for persisting the user's progress for setting up unlock methods and enabling autofill during the create account flow. This is used to bring them back to these screens after vault unlock if the app is restarted and if they choose to set up either of these things later.
- 👍 …
> PM-10524: Persist user's autofill and vault unlock setup progress in create account flow

- BitwardenShared/Core/Auth/Services/TestHelpers/MockClientFido2Client.swift
- project.yml
[PM-12278](https://bitwarden.atlassian.net/browse/PM-12278)
Upgrade SDK to fix EncString type downgrades.
Related SDK PR: https://github.com/bitwarden/sdk/pull/1041 …
> [PM-12278] Upgrade SDK to fix EncString type downgrades

- BitwardenShared/UI/Auth/AuthRouterTests.swift
- BitwardenShared/UI/Auth/Extensions/AuthRouter+Redirects.swift
https://bitwarden.atlassian.net/browse/PM-12343
Users who aren't SSO users are being forced into the SSO flow, particularly with the extension. This is likely because somehow their account in UserDefaults doesn't have user decryption options set. With this change, if we can't find those options, we assume the user has a master password, so we won't go into the SSO flow.
- Updated any necessary documentation (Confluence, contributing docs) or informed …
> Fix issue where non-SSO users are forced into an SSO flow

- BitwardenShared/Core/Autofill/Services/AutofillCredentialService.swift
- BitwardenShared/Core/Autofill/Services/AutofillCredentialServiceTests.swift
- BitwardenShared/Core/Autofill/Services/TestHelpers/MockAutofillCredentialService.swift
- BitwardenShared/Core/Platform/Services/TestHelpers/MockStateService.swift
- BitwardenShared/UI/Platform/Application/AppProcessor.swift
- BitwardenShared/UI/Platform/Application/AppProcessorTests.swift
- BitwardenShared/UI/Platform/Settings/Settings/AccountSecurity/AccountSecurityProcessor.swift
- BitwardenShared/UI/Platform/Settings/Settings/AccountSecurity/AccountSecurityProcessorTests.swift
- BitwardenShared/UI/Platform/Settings/SettingsCoordinator.swift
[PM-12313](https://bitwarden.atlassian.net/browse/PM-12313)
During the new create account flow, if the user chooses to set up unlock methods and autofill later, enabling either of these in settings should update the stored value so that any future badging no longer appears. …
> PM-12313: Update account setup progress when enabling autofill or vault unlock methods

- BitwardenShared/Core/Tools/Models/Domain/PasswordGenerationOptions.swift
- BitwardenShared/Core/Tools/Models/Domain/PasswordGenerationOptionsTests.swift
- BitwardenShared/Core/Vault/Models/Enum/PolicyOptionType.swift
- BitwardenShared/Core/Vault/Services/PolicyService.swift
- BitwardenShared/Core/Vault/Services/PolicyServiceTests.swift
- BitwardenShared/UI/Tools/Generator/Generator/GeneratorProcessor.swift
- BitwardenShared/UI/Tools/Generator/Generator/GeneratorProcessorTests.swift
- BitwardenShared/UI/Tools/Generator/Generator/GeneratorView.swift
https://bitwarden.atlassian.net/browse/PM-11894
Renaming property `defaultValue` to `overridePasswordType` as it is the name used on the other clients
Updating the behaviour so that it forces the user to use the `overridePasswordType` on the password generator
https://github.com/user-attachments/assets/4f021f4d-fd13-45fb-be9e-f709cb54a117
- 👍 …
> [PM-11894] update password generator policy

- BitwardenShared/UI/Auth/Login/TwoFactorAuth/TwoFactorAuthProcessor.swift
- BitwardenShared/UI/Auth/Login/TwoFactorAuth/TwoFactorAuthProcessorTests.swift
- BitwardenShared/UI/Platform/Application/Support/Localizations/en.lproj/Localizable.strings
[PM-9754](https://bitwarden.atlassian.net/browse/PM-9754)
Update error message when the AuthUrl from Duo 2FA is null to match the other clients. …
> [PM-9754] Update Duo AuthUrl null error message to match other clients

- BitwardenShared/Core/Auth/Services/AuthService.swift
- BitwardenShared/Core/Auth/Services/AuthServiceTests.swift
- BitwardenShared/Core/Autofill/Services/AutofillCredentialService.swift
[PM-12312](https://bitwarden.atlassian.net/browse/PM-12312)
During the new create account flow, if a new account is created and autofill is already enabled for the app, the setup autofill screen should not be shown to the user. This bypasses the autofill screen by setting the user's autofill setup progress to complete when the account is created.
- 👍 …
> PM-12312: Update autofill setup progress when account is created and autofill is enabled

- BitwardenShared/Core/Auth/Services/AuthServiceTests.swift
- BitwardenShared/Core/Platform/Services/ClientServiceTests.swift
- BitwardenShared/Core/Platform/Services/TestHelpers/MockConfigService.swift
- BitwardenShared/UI/Auth/AuthRouterTests.swift
[PM-12976](https://bitwarden.atlassian.net/browse/PM-12976)
The two `subscribesToBadgePublisher` tests in `SettingsProcessorsTests` intermittently fail due to a threading issue with the shared `featureFlagsBool` dictionary in `MockConfigService`. To fix this, I opted to make `MockConfigService` run on the main actor. This seemed like the least invasive change to fix this given that most of our tests already run on the main actor.
```
Error: -[BitwardenSharedTests.SettingsProcessorTests test_init_subscribesToBadgePublisher_error] : -[_NSCoreDataTaggedObjectID objectForKey:]: unrecognized selector sent to instance 0x8000000000000000 (NSInvalidArgumentException)
```
https://github.com/bitwarden/ios/actions/runs/11076634320/job/30780148425#step:9:7762 
- All …
> PM-12976: Fix threading issue for SettingsProcessorTests

- BitwardenShared/Core/Auth/Services/AuthService.swift
- BitwardenShared/Core/Auth/Services/AuthServiceTests.swift
- BitwardenShared/Core/Platform/Services/ServiceContainer.swift
- BitwardenShared/Core/Platform/Services/StateService.swift
- BitwardenShared/Core/Platform/Services/TestHelpers/MockStateService.swift
[PM-12565](https://bitwarden.atlassian.net/browse/PM-12565)
This addresses a comment @fedemkr made here: https://github.com/bitwarden/ios/pull/972/files#r1777654377
If setting the user's account setup progress fails as part of login, we should log the error rather than throw which would cause the login to fail. …
> PM-12565: Don't fail login if setting account setup progress fails

- BitwardenShared/Core/Auth/Services/AuthServiceTests.swift
[PM-12976](https://bitwarden.atlassian.net/browse/PM-12976)
Fixes a test build error because of a missing `@MainActor` attribute for accessing the `MockConfigService`.
This is an addition to https://github.com/bitwarden/ios/pull/987 which was missed in https://github.com/bitwarden/ios/pull/988.
- 📝 (`:memo:`) …
> PM-12976: Fix test that needs main actor attribute

- Configs/local-sdk.yml
- README.md
- project.yml
https://bitwarden.atlassian.net/browse/PM-7587
For development purposes it can be beneficial to build against a local SDK build instead of the published artifacts. This uses the `include` function of `XcodeGen` to conditionally swap out the remote dependency for a local if `LOCAL_SDK` env flag is set.
- 📝 …
> [PM-7587] Support conditionally loading local sdk

- .github/CODEOWNERS
[PM-9328](https://bitwarden.atlassian.net/browse/PM-9328)
Updating CODEOWNERS so the mobile team owns all of the .github  …
> [PM-9328] CODEOWNERS - Mobile team owns all .github folder changes

- BitwardenShared/UI/Auth/AuthCoordinator.swift
- BitwardenShared/UI/Auth/CompleteRegistration/CompleteRegistrationProcessor.swift
- BitwardenShared/UI/Auth/CompleteRegistration/CompleteRegistrationProcessorTests.swift
- BitwardenShared/UI/Auth/CompleteRegistration/MasterPasswordGenerator/MasterPasswordGeneratorProcessor.swift
- BitwardenShared/UI/Auth/CompleteRegistration/MasterPasswordGenerator/MasterPasswordGeneratorProcessorTests.swift
- BitwardenShared/UI/Auth/CompleteRegistration/MasterPasswordGenerator/TestHelpers/MockMasterPasswordUpdateDeleagate.swift
- BitwardenShared/UI/Auth/CompleteRegistration/MasterPasswordGuidance/MasterPasswordGuidanceProcessor.swift
- BitwardenShared/UI/Auth/CompleteRegistration/MasterPasswordGuidance/MasterPasswordGuidanceProcessorTests.swift
[PM-10676](https://bitwarden.atlassian.net/browse/PM-10676)
- After generating a new passphrase, we need to be able to save it when creating a new Master Password during account creation.
- Used delegation to communicate between the CompleteRegistrationProcessor and the MasterPasswordGeneratorProcessor via the MasterPasswordUpdateDelegate.
https://github.com/user-attachments/assets/ddba74b3-1028-43f1-923b-70ee27a8e74e …
> PM-10676 - Fill in generated passphrase

- .github/workflows/CI-main.yml
[PM-12580](https://bitwarden.atlassian.net/browse/PM-12580)
Fixes the internal beta app CI by moving the patch _patching_ out of the job.  …
> [PM-12580] Fix internal beta app CI

- Bitwarden/Application/SceneDelegate.swift
- BitwardenShared/UI/Platform/Application/AppProcessor.swift
[PM-10281](https://bitwarden.atlassian.net/browse/PM-10281)
Applies an overridden light/dark mode theme to the splash screen. There's still a brief portion of the app launch that we can't override, but the splash screen should have the correct theme after that.
App launch:
| --- | --- |
| <video src="https://github.com/user-attachments/assets/b1889c68-7f8d-4d88-8459-cf7525324526" /> | <video src="https://github.com/user-attachments/assets/a466ee40-84b3-4832-afbc-16a757917671" /> |
App switcher:
| --- | --- |
| <video src="https://github.com/user-attachments/assets/4f339d0b-6bb6-4699-8b58-b482bdab9b69" /> | <video src="https://github.com/user-attachments/assets/6cd42b31-faa8-4d26-8330-c58e445b80f4" /> |
- All …
> PM-10281: Set custom app theme on splash window

- .github/workflows/build.yml
[PM-13205](https://bitwarden.atlassian.net/browse/PM-13205)
CI-main was failing while updating release notes due to a change in Apple services last week. Fastlane fixed it in https://github.com/fastlane/fastlane/pull/22256 which was [released in 2.223.1](https://github.com/fastlane/fastlane/issues/22248#issuecomment-2378489778), but our brew is still getting 2.220.0. 
By updating brew we should now get fastlane >=2.224.0.   …
> [PM-13205] Fix CI-main builds by updating brew

- BitwardenShared/UI/Auth/StartRegistration/CheckEmail/CheckEmailProcessor.swift
- BitwardenShared/UI/Auth/StartRegistration/CheckEmail/CheckEmailProcessorTests.swift
[PM-12988](https://bitwarden.atlassian.net/browse/PM-12988)
- Using `dismissPresented` when closing out the `CheckEmailView` so the close/swipe down ux match.
- When QA was testing this ticket they found that the dismiss navigation on the `CheckEmailView` didn't match the swipe down dismiss.  This is because this was missed in the original PR [here](https://github.com/bitwarden/ios/pull/1010).
https://github.com/user-attachments/assets/a84c0d8c-0346-4bac-a0a6-9a2b7f1c6ae9
- Communicated to DevOps any …
> PM-12988 - Fix close navigation on `CheckEmailView`

- BitwardenShared/UI/Platform/Application/AppProcessor.swift
- BitwardenShared/UI/Platform/Application/AppProcessorTests.swift
[PM-12736](https://bitwarden.atlassian.net/browse/PM-12736)
Dismisses the autofill badge if the app is foregrounded and the autofill extension is enabled. Previously this was only happening on start up or when the autofill view was open.
https://github.com/user-attachments/assets/0e0655ad-36c3-4c55-bdfd-b54c2098ffdc …
> PM-12736: Dismiss badge for autofill once enabled

- BitwardenShared/UI/Auth/AuthCoordinator.swift
- BitwardenShared/UI/Auth/IntroCarousel/IntroCarouselAction.swift
- BitwardenShared/UI/Auth/IntroCarousel/IntroCarouselEffect.swift
- BitwardenShared/UI/Auth/IntroCarousel/IntroCarouselProcessor.swift
- BitwardenShared/UI/Auth/IntroCarousel/IntroCarouselProcessorTests.swift
- BitwardenShared/UI/Auth/IntroCarousel/IntroCarouselView.swift
- BitwardenShared/UI/Auth/IntroCarousel/IntroCarouselViewTests.swift
[PM-12782](https://bitwarden.atlassian.net/browse/PM-12782)
If email verification is enabled, the intro carousel will open the start registration view instead of the previous create account flow.
https://github.com/user-attachments/assets/4fae9abf-3878-4304-9d3c-3c9cc41f0915 …
> PM-12782: Handle email verification feature flag when navigating from the intro carousel

- BitwardenShared/UI/Platform/Application/Views/BitwardenTextValueField.swift
- BitwardenShared/UI/Vault/VaultItem/ViewItem/ViewItemDetailsView.swift
https://bitwarden.atlassian.net/browse/PM-13027
Setting `textSelectionEnabled` on  `BitwardenTextValueField` as `true` in order to allow user to long press copy all textfields …
> [PM-13027] Allowing longpress copy on textfields

- BitwardenShared/UI/Platform/Application/Support/Localizations/en.lproj/Localizable.strings
- BitwardenShared/UI/Platform/Application/Utilities/Navigator.swift
- BitwardenShared/UI/Vault/Vault/ImportLogins/ImportLoginsAction.swift
- BitwardenShared/UI/Vault/Vault/ImportLogins/ImportLoginsEffect.swift
- BitwardenShared/UI/Vault/Vault/ImportLogins/ImportLoginsProcessor.swift
- BitwardenShared/UI/Vault/Vault/ImportLogins/ImportLoginsProcessorTests.swift
- BitwardenShared/UI/Vault/Vault/ImportLogins/ImportLoginsView.swift
- BitwardenShared/UI/Vault/Vault/ImportLogins/ImportLoginsViewTests.swift
- BitwardenShared/UI/Vault/Vault/VaultCoordinator.swift
[PM-11159](https://bitwarden.atlassian.net/browse/PM-11159)
On the last import logins page, hitting Continue should sync the user's vault. This adds the sync call and loading overlay. Navigation to the success page will be in a separate PR.
https://github.com/user-attachments/assets/fe63a071-d75f-478f-aeca-53e3ae138cf4 …
> PM-11159: Add vault sync for importing logins

- BitwardenShared/Core/Auth/Services/AuthService.swift
- BitwardenShared/Core/Auth/Services/AuthServiceTests.swift
[PM-13280](https://bitwarden.atlassian.net/browse/PM-13280)
Based on [this Crashlytics report](https://console.firebase.google.com/project/bitwarden-c2b35/crashlytics/app/ios:com.8bit.bitwarden/issues/b77dd77f85ac1aaf077debe2294a887a?time=last-seven-days&versions=2024.9.2%20(1106)&sessionEventKey=c40822bf5c3748e4a7efeb0124637617_2001491588821595139), on Login with device we should pass `isPreAuth: true` for auth SDK client. …
> [PM-13280] Fix isPreAuth flag on login with device.

- BitwardenShared/Core/Auth/Models/Response/CreateAccountResponseModel.swift
- BitwardenShared/Core/Auth/Models/Response/IdentityTokenResponseModel.swift
- BitwardenShared/Core/Auth/Models/Response/KnownDeviceResponseModel.swift
- BitwardenShared/Core/Auth/Models/Response/PreLoginResponseModel.swift
- BitwardenShared/Core/Auth/Models/Response/PreValidateSingleSignOnResponse.swift
- BitwardenShared/Core/Auth/Models/Response/RegisterFinishResponseModel.swift
- BitwardenShared/Core/Platform/Models/Domain/ServerConfig.swift
- BitwardenShared/Core/Platform/Services/API/Extensions/JSONResponse+Bitwarden.swift
- BitwardenShared/Core/Platform/Services/API/Response/ConfigResponseModel.swift
- BitwardenShared/Core/Platform/Utilities/DefaultFalse.swift
- BitwardenShared/Core/Platform/Utilities/DefaultFalseTests.swift
- BitwardenShared/Core/Vault/Models/Response/ProfileResponseModel.swift
[PM-13835](https://bitwarden.atlassian.net/browse/PM-13835)
Improves the flexibility of JSON decoding by supporting pascal or camel case keys. Also, allows for decoding a few bools which may not always be present.
This should fix the following errors in Crashlytics:
- NSCocoaErrorDomain (4865): No value associated with key CodingKeys(stringValue: "ciphers", intValue: nil) ("ciphers").
- NSCocoaErrorDomain (4865): No value associated with key CodingKeys(stringValue: "kdf", intValue: nil) ("kdf").
- NSCocoaErrorDomain (4865): No value associated with key CodingKeys(stringValue: "forcePasswordReset", intValue: nil) ("forcePasswordReset").
- NSCocoaErrorDomain (4865): No value associated with key CodingKeys(stringValue: "featureStates", intValue: nil) ("featureStates").
- Contributor …
> PM-13835: Improve JSON decoding flexibility

- BitwardenShared/Core/Vault/Repositories/TestHelpers/MockVaultRepository.swift
- BitwardenShared/Core/Vault/Repositories/VaultRepository.swift
- BitwardenShared/Core/Vault/Repositories/VaultRepositoryTests.swift
- BitwardenShared/Core/Vault/Services/CipherService.swift
- BitwardenShared/Core/Vault/Services/CipherServiceTests.swift
- BitwardenShared/Core/Vault/Services/Stores/CipherDataStore.swift
- BitwardenShared/Core/Vault/Services/Stores/CipherDataStoreTests.swift
- BitwardenShared/Core/Vault/Services/Stores/TestHelpers/MockCipherDataStore.swift
- BitwardenShared/Core/Vault/Services/TestHelpers/MockCipherService.swift
- BitwardenShared/UI/Platform/Application/Support/Localizations/en.lproj/Localizable.strings
- BitwardenShared/UI/Vault/Extensions/Alert+Vault.swift
- BitwardenShared/UI/Vault/Extensions/AlertVaultTests.swift
- BitwardenShared/UI/Vault/Vault/ImportLogins/ImportLoginsProcessor.swift
- BitwardenShared/UI/Vault/Vault/ImportLogins/ImportLoginsProcessorTests.swift
[PM-13885](https://bitwarden.atlassian.net/browse/PM-13885)
This handles the case where a user navigates through the import login flow and after syncing, the user's vault is still empty. An alert is shown asking the user if they want to try again or import logins later.
https://github.com/user-attachments/assets/8ceaf161-8231-4323-b345-2479d7d363a6
- …
> PM-13885: Handle empty vault after import logins

- BitwardenShared/Core/Platform/Models/Domain/EnvironmentUrls.swift
- BitwardenShared/Core/Platform/Models/Domain/EnvironmentUrlsTests.swift
[PM-13691](https://bitwarden.atlassian.net/browse/PM-13691) - Managed base URL setting of EU returns US environment URLs
[PM-13443](https://bitwarden.atlassian.net/browse/PM-13443) - User lands on empty SSO identifier screen even with claimed domain
Previously, if the managed base URL or a self-hosted base URL was set to the EU server (https://vault.bitwarden.eu), the app would still use US environment URLs. If the URLs are for a self-hosted region, the app uses the self-hosted base URL to construct the URLs. Otherwise, we were assuming `EnvironmentUrlData` was fully populated. If only the base URL was set, it would default to the US URLs instead of constructing the URLs based on the base URL.
Instead, if the URL's region is for US or EU, we should use the default US or EU URLs rather …
> PM-13691: Fix managed EU base URL setting returns US environment URLs

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/config.yml
- README.md
Now that the app is released on the app store, and not in beta, we should remove references to it being in beta. …
> Clean up references to the beta

- BitwardenShared/UI/Vault/VaultItem/ViewItem/ViewItemDetailsView.swift
https://bitwarden.atlassian.net/browse/PM-13027
Allow custom fields that are of type text to be selectable by longpress
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite …
> [PM-13027] Allowing long press copy on custom field text

- BitwardenShared/UI/Platform/Settings/Settings/AccountSecurity/AccountSecurityProcessor.swift
- BitwardenShared/UI/Platform/Settings/Settings/AccountSecurity/AccountSecurityProcessorTests.swift
[PM-13949](https://bitwarden.atlassian.net/browse/PM-13949)
From Settings > Account security > Set up unlock, if you enable a vault unlock method, but back out of the view instead of tapping the Continue button, the action card wasn't being cleared. This clears the card when navigating back to Account security screen if an unlock method has been enabled.
| --- | --- |
| <video src="https://github.com/user-attachments/assets/d37ef27f-0ea1-4202-ad6c-54a690d1a2e4" /> | <video src="https://github.com/user-attachments/assets/9b19326e-999a-4329-bce1-b96373b7185a" /> |
- Protected functional changes with optionality (feature …
> PM-13949: Dismiss vault unlock action card when backing out of set up unlock with unlock method enabled

- BitwardenShared/Core/Vault/Repositories/VaultRepository.swift
- BitwardenShared/Core/Vault/Repositories/VaultRepositoryTests.swift
- BitwardenShared/Core/Vault/Services/SyncService.swift
- BitwardenShared/Core/Vault/Services/SyncServiceTests.swift
- BitwardenShared/Core/Vault/Services/TestHelpers/MockSyncService.swift
[PM-12655](https://bitwarden.atlassian.net/browse/PM-12655)
In a slow connection scenario the vault tab was displaying the loading indicator for a long time (potentially until request timeout) so it could seem that the app hangs.
This attempts to fix this on the scenario where the vault has local data to display, so it immediately displays such data while the sync happens in the background. This was happening because of a request being sent to check whether sync was needed before streaming the local vault data; now this check is done only with local data on the streaming vault list items process.
| --- | --- |
| <video src="https://github.com/user-attachments/assets/7ccd7b59-d66b-436b-81a3-9d6bb78781db" /> | <video …
> [PM-12655] Fix vault tab endless loading when in slow connection

- BitwardenShared/UI/Auth/Landing/LandingProcessor.swift
- @fedemkr brought this to my attention from this [PR](https://github.com/bitwarden/ios/pull/1072#discussion_r1815809464). 
- Wrapped `refreshConfig()` in a Task to prevent UI delays on slow internet connections. This avoids blocking critical actions (e.g., .appeared refresh calls, closing the Self-host settings view) that were previously held up by awaiting refreshConfig(). For features that require configuration data, fallback flows ensure functionality even if refreshConfig() isn’t instantly loaded.
- …
> Use Task Wrapper for `refreshConfig()` to Improve UI Responsiveness on Slow Connections

- BitwardenShared/UI/Auth/AuthCoordinator.swift
- BitwardenShared/UI/Auth/AuthCoordinatorTests.swift
- BitwardenShared/UI/Auth/AuthModule.swift
- BitwardenShared/UI/Platform/Application/AppModuleTests.swift
- BitwardenShared/UI/Platform/Settings/Settings/AutoFill/PasswordAutoFill/PasswordAutoFillCoordinator.swift
- BitwardenShared/UI/Platform/Settings/Settings/AutoFill/PasswordAutoFill/PasswordAutoFillCoordinatorTests.swift
- BitwardenShared/UI/Platform/Settings/Settings/AutoFill/PasswordAutoFill/PasswordAutoFillModule.swift
- BitwardenShared/UI/Platform/Settings/Settings/AutoFill/PasswordAutoFill/PasswordAutoFillProcessor.swift
- BitwardenShared/UI/Platform/Settings/Settings/AutoFill/PasswordAutoFill/PasswordAutoFillProcessorTests.swift
- BitwardenShared/UI/Platform/Settings/Settings/AutoFill/PasswordAutoFill/PasswordAutofillEvent.swift
- BitwardenShared/UI/Platform/Settings/Settings/AutoFill/PasswordAutoFill/PasswordAutofillRoute.swift
- BitwardenShared/UI/Platform/Settings/SettingsCoordinator.swift
- BitwardenShared/UI/Platform/Settings/SettingsCoordinatorTests.swift
- GlobalTestHelpers/MockAppModule.swift
[PM-12735](https://bitwarden.atlassian.net/browse/PM-12735)
Currently, when you enable autofill from settings, when returning to the app after autofill has been enabled, you are still on the "Set up autofill" screen. This changes it so the "Set up autofill" screen will be dismissed once autofill has been enabled.
https://github.com/user-attachments/assets/e1837213-ff1a-4fde-935f-7e46524c77b5 …
> PM-12735: Navigate back to settings after enabling autofill

- BitwardenShared/UI/Auth/AuthRouterTests.swift
- BitwardenShared/UI/Auth/Extensions/AuthRouter+Redirects.swift
[PM-13694](https://bitwarden.atlassian.net/browse/PM-13694)
This sets the carousel shown flag prior to navigating the user to any account setup screens after an account has been created. This prevents the possibility of the carousel being shown again if the app is restarted before account setup has completed. …
> PM-13694: Set carousel shown prior to account setup screens

- .github/workflows/CI-main.yml
- .github/workflows/build.yml
- .test-simulator-device-name
- GlobalTestHelpers/Support/BitwardenTestCase.swift
- README.md
https://bitwarden.atlassian.net/browse/PM-11213
Because the [macos-15 runner](https://github.com/actions/runner-images/blob/main/images/macos/macos-15-Readme.md) doesn't have an iPhone 15 Pro as an option, we need to update to an iPhone 16 Pro.
As well, in [the previous PR](https://github.com/bitwarden/ios/pull/1070), I missed that `CI-main.yml` was also manually setting the Xcode version, and that has also been updated. …
> [PM-11213] Use iPhone 16 Pro test device and finish updating builds for Xcode 16.1

- BitwardenShared/Core/Platform/Services/AuthenticatorSyncService.swift
- BitwardenShared/Core/Platform/Services/NotificationCenterService.swift
- BitwardenShared/Core/Platform/Services/NotificationCenterServiceTests.swift
[BITAU-194](https://livefront.atlassian.net/browse/BITAU-194)
This PR addresses two problems:
1. BITAU-194: We were seeing occasional `NSInvalidArgumentException` that were caused by the `AuthenticatorSyncService` trying to write to the Keychain when it had moved out of memory. I've added specific tasks that we then cancel in the `AuthenticatorSyncService.deinit()`. This avoids the service continuing to listen for events past the end of the test that spawned it.
2. Katherine had asked me to bring my tests for NotificationCenterService from [Authenticator PR #178](https://github.com/bitwarden/authenticator-ios/pull/178) to the PM app. We previously didn't have tests in the PM app for this.
- Written …
> [BITAU-194] Fix issue with unit tests failing occasionally; Add tests for NotifcationCenterService

- BitwardenShared/UI/Auth/AuthRouterTests.swift
- BitwardenShared/UI/Auth/Extensions/AuthRouter+Redirects.swift
[PM-12051](https://bitwarden.atlassian.net/browse/PM-12051)
Fixes an issue with automatic account switching when logging out if the two accounts are in separate environments.
- Account A logged into environment X
- Account B logged into environment Y
- If account A logs out, the app will automatically switches to account B. When this occurred, the environment service wasn't loading the URLs for account B/environment Y. This caused any future networking requests to fail for account B in the current session.
- CI builds …
> PM-12051: Fix sync error after logout and switch accounts

- BitwardenShared/Core/Auth/Models/Response/ResponseValidationErrorModel.swift
- BitwardenShared/Core/Auth/Models/Response/ResponseValidationErrorModelTests.swift
- BitwardenShared/UI/Auth/Login/TwoFactorAuth/TwoFactorAuthProcessor.swift
- BitwardenShared/UI/Auth/Login/TwoFactorAuth/TwoFactorAuthProcessorTests.swift
[PM-9089](https://bitwarden.atlassian.net/browse/PM-9089)
When logging in with a master password and 2FA code when SSO is required, the app was incorrectly showing an error stating that the verification code was incorrect instead of that SSO is required. This fixes that so the error from the server is parsed and used to display the error alert.
- 👍 …
> PM-9089: Update two factor auth screen to parse server error

- .github/workflows/build.yml
https://bitwarden.atlassian.net/browse/PM-14499
When a default value is set for an input, we're not able to dispatch workflows that value. Removing the DEBUG_MENU default value so our team is able to create builds without the menu included.  …
> [PM-14499] Remove default compiler flag from build workflow

- BitwardenShared/Core/Platform/Services/AuthenticatorSyncService.swift
- BitwardenShared/Core/Platform/Services/AuthenticatorSyncServiceTests.swift
[BITAU-204](https://livefront.atlassian.net/browse/BITAU-204)
This PR attempts to address the threading issue that's been causing problems in unit tests. Specifically, it adds a Task property to manage enabling sync. Previously, there were issues where multiple threads could enter the key methods, both threads find there is no key, and both threads attempt to add the key. The property is guaranteed to be thread-safe by virtue of the sync service being an actor. In addition, `enableSyncForUserId(_)` is **not** `async`, meaning that the actor will only allow one thread in at a time. This essentially creates a serial, synchronous queue for sync enabling.
- Written new unit and / or integration tests …
> BITAU-204 Fix Concurrency Issues in Sync Service/Tests

- BitwardenShared/Core/Platform/Services/StateService.swift
- BitwardenShared/Core/Platform/Services/StateServiceTests.swift
- BitwardenShared/Core/Platform/Services/Stores/AppSettingsStore.swift
- BitwardenShared/Core/Platform/Services/Stores/AppSettingsStoreTests.swift
- BitwardenShared/Core/Platform/Services/Stores/TestHelpers/MockAppSettingsStore.swift
- BitwardenShared/Core/Platform/Services/TestHelpers/MockStateService.swift
- BitwardenShared/UI/Platform/Application/AppCoordinator.swift
- BitwardenShared/UI/Platform/Application/AppCoordinatorTests.swift
- BitwardenShared/UI/Platform/Application/AppProcessor.swift
- BitwardenShared/UI/Platform/Application/AppProcessorTests.swift
- BitwardenShared/UI/Platform/Application/AppRoute.swift
[PM-14556](https://bitwarden.atlassian.net/browse/PM-14556)
If the active user is switched in an extension, update the app to that active user.
https://github.com/user-attachments/assets/968a8ce8-1da4-4c6b-ab74-cb8c80c9a069
- ❓ …
> PM-14556: Update active user if switched in extension

- BitwardenShared/Core/Platform/Services/TestHelpers/MockConfigService.swift
- BitwardenShared/UI/Auth/AuthRouterTests.swift
- BitwardenShared/UI/Auth/CompleteRegistration/CompleteRegistrationProcessorTests.swift
- BitwardenShared/UI/Auth/IntroCarousel/IntroCarouselProcessorTests.swift
- BitwardenShared/UI/Auth/Landing/LandingProcessor.swift
- BitwardenShared/UI/Auth/Landing/LandingProcessorTests.swift
- BitwardenShared/UI/Auth/StartRegistration/StartRegistrationProcessorTests.swift
- BitwardenShared/UI/Platform/ExtensionSetup/ExtensionActivation/ExtensionActivationProcessorTests.swift
[PM-14502](https://bitwarden.atlassian.net/browse/PM-14502)
Fixes the email verification feature flag not loading for account creation. When the landing processor was fetching the feature flags, it was missing the `isPreAuth: true` argument.
https://github.com/user-attachments/assets/4f6eb01a-3de7-4d5d-bcd7-e8a308d27f6a …
> PM-14502: Fix account creation email verification feature flag loading

- BitwardenShared/UI/Platform/Application/AppCoordinator.swift
[PM-14501](https://bitwarden.atlassian.net/browse/PM-14501)
- This PR addresses an issue where setting DebugMenuCoordinator as a child coordinator within AuthCoordinator caused a navigation error during the email verification flow. Specifically, attempting to present CompleteRegistrationView resulted in the error:
`Attempt to present <UINavigationController: 0x1069ea200> on <UINavigationController: 0x10d010000> (from <UINavigationController: 0x10d010000>) whose view is not in the window hierarchy.`
- The solution was to avoid setting `DebugMenuCoordinator` as a child coordinator, as it didn’t require being a part of the AuthCoordinator's child coordinators. This fix ensures that the email verification flow functions correctly without interference from the debug menu.
##Before …
> PM-14501 - Sometimes tapping the Verify Email link will not load the Master Password bottom sheet correctly

- BitwardenShared/Core/Auth/Repositories/AuthRepository.swift
- BitwardenShared/Core/Auth/Repositories/AuthRepositoryTests.swift
- BitwardenShared/Core/Auth/Repositories/TestHelpers/MockAuthRepository.swift
- BitwardenShared/Core/Autofill/Services/AutofillCredentialService.swift
- BitwardenShared/Core/Autofill/Services/AutofillCredentialServiceTests.swift
- BitwardenShared/Core/Platform/Services/StateService.swift
- BitwardenShared/Core/Platform/Services/StateServiceTests.swift
- BitwardenShared/Core/Platform/Services/Stores/AppSettingsStore.swift
- BitwardenShared/Core/Platform/Services/Stores/AppSettingsStoreTests.swift
- BitwardenShared/Core/Platform/Services/Stores/TestHelpers/MockAppSettingsStore.swift
- BitwardenShared/Core/Platform/Services/TestHelpers/MockStateService.swift
- BitwardenShared/UI/Auth/AuthAction.swift
- BitwardenShared/UI/Auth/AuthRouter.swift
- BitwardenShared/UI/Auth/AuthRouterTests.swift
- BitwardenShared/UI/Auth/Extensions/Alert+Auth.swift
- BitwardenShared/UI/Auth/Extensions/AuthRouter+Redirects.swift
- BitwardenShared/UI/Auth/Landing/LandingProcessorTests.swift
- BitwardenShared/UI/Auth/ProfileSwitcher/ProfileSwitcherHandler.swift
- BitwardenShared/UI/Auth/VaultUnlock/VaultUnlockProcessorTests.swift
- BitwardenShared/UI/Platform/Application/AppCoordinator.swift
- BitwardenShared/UI/Platform/Application/AppCoordinatorTests.swift
- BitwardenShared/UI/Platform/Settings/Settings/AccountSecurity/AccountSecurityProcessor.swift
- BitwardenShared/UI/Platform/Settings/Settings/AccountSecurity/AccountSecurityProcessorTests.swift
- BitwardenShared/UI/Platform/Settings/SettingsCoordinator.swift
- BitwardenShared/UI/Platform/Settings/SettingsCoordinatorTests.swift
- BitwardenShared/UI/Vault/Vault/VaultCoordinator.swift
- BitwardenShared/UI/Vault/Vault/VaultCoordinatorTests.swift
- BitwardenShared/UI/Vault/Vault/VaultList/VaultListProcessorTests.swift
[PM-14579](https://bitwarden.atlassian.net/browse/PM-14579)
Fix issue where when session timeout is Never and the user manually locked the vault, the vault was being automatically unlocked when closing and opening back the app again.
So the behavior now is that if the user manually locks the vault then it remains locked no matter the session timeout. …
> [PM-14579] Fix maintaining vault locked on timeout Never.

- BitwardenShared/Core/Platform/Services/AuthenticatorSyncService.swift
- BitwardenShared/Core/Platform/Services/AuthenticatorSyncServiceTests.swift
- BitwardenShared/Core/Platform/Services/StateService.swift
- BitwardenShared/Core/Platform/Services/StateServiceTests.swift
- BitwardenShared/Core/Platform/Services/Stores/AppSettingsStore.swift
- BitwardenShared/Core/Platform/Services/Stores/AppSettingsStoreTests.swift
- BitwardenShared/Core/Platform/Services/Stores/TestHelpers/MockAppSettingsStore.swift
- BitwardenShared/Core/Platform/Services/TestHelpers/MockConfigService.swift
- BitwardenShared/Core/Platform/Services/TestHelpers/MockStateService.swift
- BitwardenShared/Core/Vault/Models/Response/Fixtures/ProfileOrganizationResponseModel+Fixtures.swift
- BitwardenShared/Core/Vault/Models/Response/ProfileOrganizationResponseModel.swift
- BitwardenShared/UI/Auth/AuthRouterTests.swift
- BitwardenShared/UI/Auth/CompleteRegistration/CompleteRegistrationProcessorTests.swift
- BitwardenShared/UI/Auth/IntroCarousel/IntroCarouselProcessorTests.swift
- BitwardenShared/UI/Auth/Landing/LandingProcessor.swift
- BitwardenShared/UI/Auth/Landing/LandingProcessorTests.swift
- BitwardenShared/UI/Auth/StartRegistration/StartRegistrationProcessorTests.swift
- BitwardenShared/UI/Platform/Application/AppCoordinator.swift
- BitwardenShared/UI/Platform/Application/AppCoordinatorTests.swift
- BitwardenShared/UI/Platform/Application/AppProcessor.swift
- BitwardenShared/UI/Platform/Application/AppProcessorTests.swift
- BitwardenShared/UI/Platform/Application/AppRoute.swift
- BitwardenShared/UI/Platform/ExtensionSetup/ExtensionActivation/ExtensionActivationProcessorTests.swift
[PM-14620](https://bitwarden.atlassian.net/browse/PM-14620)
Fixes a JSON decoding error in Crashlytics because `accessSecretsManager` is missing. I'm guessing this is caused by an older self-hosted instance? But since we don't use this property, I don't see any reason to keep it around. …
> PM-14620: Remove unused accessSecretsManager property to fix JSON decoding errors

- Bitwarden/Application/UIApplication+Application.swift
- BitwardenShared/Core/Autofill/Extensions/BitwardenSdk+Autofill.swift
- BitwardenShared/Core/Platform/Extensions/BitwardenSdk+Platform.swift
- BitwardenShared/Core/Platform/Services/API/Extensions/JSONRequestBody+Bitwarden.swift
- BitwardenShared/Core/Vault/Extensions/BitwardenSdk+Vault.swift
- BitwardenShared/UI/Auth/Utilities/TestHelpers/MockVaultUnlockSetupHelper.swift
- BitwardenShared/UI/Auth/Utilities/VaultUnlockSetupHelper.swift
- BitwardenShared/UI/Platform/Application/TestHelpers/Extensions/DispatchTimeInterval.swift
- BitwardenShared/UI/Tools/PasswordHistory/PasswordHistoryList/PasswordHistoryListView.swift
Now that we're on Xcode 16.1, there are a number of new warnings that have cropped up in the project. As well, Xcode 16.1 gives us more ability to deal with some other warnings that have been hanging around a while. This attempts to fix some of these warnings, which should prepare us better for Swift 6 eventually. …
> Fix various warnings

- BitwardenShared/UI/Platform/Application/AppCoordinator.swift
[PM-14501](https://bitwarden.atlassian.net/browse/PM-14501)
- Backport `PM-14501` to `main` …
> PM-14501 - Backport to `main`

- BitwardenShared/Core/Platform/Utilities/AnyCodable.swift
- BitwardenShared/Core/Platform/Utilities/AnyCodableTests.swift
- BitwardenShared/Core/Platform/Utilities/DefaultValue.swift
- BitwardenShared/Core/Platform/Utilities/DefaultValueTests.swift
- BitwardenShared/Core/Vault/Models/API/CipherSecureNoteModel.swift
- BitwardenShared/Core/Vault/Models/Enum/CipherRepromptType.swift
- BitwardenShared/Core/Vault/Models/Enum/CipherRepromptTypeTests.swift
- BitwardenShared/Core/Vault/Models/Enum/SecureNoteType.swift
- BitwardenShared/Core/Vault/Models/Response/CipherDetailsResponseModel.swift
- BitwardenShared/Core/Vault/Models/SecureNoteTypeTests.swift
[PM-14646](https://bitwarden.atlassian.net/browse/PM-14646) - Fix JSON decoding errors for invalid CipherRepromptType, SecureNoteType, decimal policy timeout minutes
[PM-13105 ](https://bitwarden.atlassian.net/browse/PM-13105) - [iOS] Users getting "An Error has occurred" and can't access their vaults
This fixes the following JSON decoding errors:
Invalid CipherRepromptType:
```
Cannot initialize CipherRepromptType from invalid Int value 65
```
Invalid SecureNoteType:
```
Cannot initialize SecureNoteType from invalid Int value 2
```
Unexpected decimal when decoding a vault timeout policy minutes property:
```
( "CodingKeys(stringValue: \"policies\", intValue: nil)", "_JSONKey(stringValue: \"Index 7\", intValue: 7)", "CodingKeys(stringValue: \"data\", intValue: nil)", …
```
> PM-14646: Fix JSON decoding errors

- BitwardenShared/Core/Auth/Repositories/AuthRepository.swift
- BitwardenShared/Core/Auth/Repositories/AuthRepositoryTests.swift
- BitwardenShared/Core/Auth/Repositories/TestHelpers/MockAuthRepository.swift
- BitwardenShared/Core/Autofill/Services/AutofillCredentialService.swift
- BitwardenShared/Core/Autofill/Services/AutofillCredentialServiceTests.swift
- BitwardenShared/Core/Platform/Services/StateService.swift
- BitwardenShared/Core/Platform/Services/StateServiceTests.swift
- BitwardenShared/Core/Platform/Services/Stores/AppSettingsStore.swift
- BitwardenShared/Core/Platform/Services/Stores/AppSettingsStoreTests.swift
- BitwardenShared/Core/Platform/Services/Stores/TestHelpers/MockAppSettingsStore.swift
- BitwardenShared/Core/Platform/Services/TestHelpers/MockStateService.swift
- BitwardenShared/UI/Auth/AuthAction.swift
- BitwardenShared/UI/Auth/AuthRouter.swift
- BitwardenShared/UI/Auth/AuthRouterTests.swift
- BitwardenShared/UI/Auth/Extensions/Alert+Auth.swift
- BitwardenShared/UI/Auth/Extensions/AuthRouter+Redirects.swift
- BitwardenShared/UI/Auth/Landing/LandingProcessorTests.swift
- BitwardenShared/UI/Auth/ProfileSwitcher/ProfileSwitcherHandler.swift
- BitwardenShared/UI/Auth/VaultUnlock/VaultUnlockProcessorTests.swift
- BitwardenShared/UI/Platform/Application/AppCoordinator.swift
- BitwardenShared/UI/Platform/Application/AppCoordinatorTests.swift
- BitwardenShared/UI/Platform/Settings/Settings/AccountSecurity/AccountSecurityProcessor.swift
- BitwardenShared/UI/Platform/Settings/Settings/AccountSecurity/AccountSecurityProcessorTests.swift
- BitwardenShared/UI/Platform/Settings/SettingsCoordinator.swift
- BitwardenShared/UI/Platform/Settings/SettingsCoordinatorTests.swift
- BitwardenShared/UI/Vault/Vault/VaultCoordinator.swift
- BitwardenShared/UI/Vault/Vault/VaultCoordinatorTests.swift
- BitwardenShared/UI/Vault/Vault/VaultList/VaultListProcessorTests.swift
[PM-14579](https://bitwarden.atlassian.net/browse/PM-14579)
Backport #1121 to main …
> [PM-14579] Backport to main

- BitwardenShared/Core/Platform/Utilities/AnyCodable.swift
- BitwardenShared/Core/Platform/Utilities/AnyCodableTests.swift
- BitwardenShared/Core/Platform/Utilities/DefaultValue.swift
- BitwardenShared/Core/Platform/Utilities/DefaultValueTests.swift
- BitwardenShared/Core/Vault/Models/API/CipherSecureNoteModel.swift
- BitwardenShared/Core/Vault/Models/Enum/CipherRepromptType.swift
- BitwardenShared/Core/Vault/Models/Enum/CipherRepromptTypeTests.swift
- BitwardenShared/Core/Vault/Models/Enum/SecureNoteType.swift
- BitwardenShared/Core/Vault/Models/Response/CipherDetailsResponseModel.swift
- BitwardenShared/Core/Vault/Models/SecureNoteTypeTests.swift
[PM-14646](https://bitwarden.atlassian.net/browse/PM-14646)
Backport https://github.com/bitwarden/ios/pull/1122 to `main`. …
> PM-14646: Fix JSON decoding errors (backport of #1122)

- BitwardenShared/Core/Vault/Models/Response/Fixtures/ProfileOrganizationResponseModel+Fixtures.swift
- BitwardenShared/Core/Vault/Models/Response/ProfileOrganizationResponseModel.swift
[PM-14620](https://bitwarden.atlassian.net/browse/PM-14620)
Backport https://github.com/bitwarden/ios/pull/1116 to main.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite …
> PM-14620: Remove unused accessSecretsManager property to fix JSON decoding errors (backport of #1116)

- BitwardenShared/Core/Auth/Repositories/AuthRepository.swift
- BitwardenShared/Core/Auth/Repositories/AuthRepositoryTests.swift
- BitwardenShared/UI/Auth/AuthRouterTests.swift
- BitwardenShared/UI/Auth/Extensions/AuthRouter+Redirects.swift
[PM-12051](https://bitwarden.atlassian.net/browse/PM-12051)
Related to https://github.com/bitwarden/ios/pull/1100.
Fixes an issue with automatic account switching when deleting an account if the account that will be switched to after the deletion is in a separate environments.
- Account A logged into environment X
- Account B logged into environment Y
- If account A is deleted, the app will automatically switches to account B. When this occurred, the environment service wasn't loading the URLs for account B/environment Y. This caused any future networking requests to fail for account B in the current session.
- Protected functional changes …
> PM-12051: Fix sync error after delete and switch accounts

- BitwardenShared/Core/Vault/Services/TOTP/TOTPKey.swift
- BitwardenShared/Core/Vault/Services/TOTP/TOTPKeyModel.swift
- BitwardenShared/UI/Platform/Application/AppProcessor.swift
- BitwardenShared/UI/Platform/Application/AppProcessorTests.swift
- BitwardenShared/UI/Vault/PreviewContent/String+TOTPFixtures.swift
- BitwardenShared/UI/Vault/Vault/VaultCoordinator.swift
- BitwardenShared/UI/Vault/Vault/VaultCoordinatorTests.swift
- BitwardenShared/UI/Vault/Vault/VaultItemSelection/VaultItemSelectionProcessor.swift
- BitwardenShared/UI/Vault/Vault/VaultItemSelection/VaultItemSelectionProcessorTests.swift
- BitwardenShared/UI/Vault/Vault/VaultItemSelection/VaultItemSelectionState.swift
- BitwardenShared/UI/Vault/Vault/VaultItemSelection/VaultItemSelectionStateTests.swift
- BitwardenShared/UI/Vault/Vault/VaultItemSelection/VaultItemSelectionView.swift
- BitwardenShared/UI/Vault/Vault/VaultItemSelection/VaultItemSelectionViewTests.swift
- BitwardenShared/UI/Vault/Vault/VaultRoute.swift
[BITAU-179](https://livefront.atlassian.net/browse/BITAU-179)
This PR refactors the Vault selection to handle `TOTPKeyModel` instead of `OTPAuthModel`. Previously, the vault selection was only used for incoming otpauth URLs from the camera's QR code scanning. This meant that it was built using `OTPAuthModel` to hold all of the TOTP details. When building the Authenticator sync feature, we wanted to allow users to move any of their codes from Authenticator to the PM app. But some of those codes could be Steam URI codes or standard codes, which wouldn't have parsed when handed to `OTPAuthModel`.
By refactoring the route, processor, state, etc to use `TOTPKeyModel` we allow for handling of any codes that could be sent from the Authenticator app.
In testing this, I discovered that the way the …
> [BITAU-179] Refactor Vault Selection to Include Standard and SteamURI TOTP Types

- BitwardenShared/UI/Platform/Application/Appearance/Modifiers/ImageStyle.swift
- BitwardenShared/UI/Platform/Application/Appearance/Styles/ToolbarButtonStyle.swift
- BitwardenShared/UI/Platform/Application/Extensions/View+Toolbar.swift
[PM-14573](https://bitwarden.atlassian.net/browse/PM-14573)
Updates the color of disabled toolbar buttons. This fixes an issue where the save button when sends are disabled looks like the enabled button.
| --- | --- |
| <img width="568" alt="Screenshot 2024-11-15 at 10 17 41 AM" src="https://github.com/user-attachments/assets/d03e6de6-0112-42d1-a658-6424192dd1d4"> | <img width="568" alt="Screenshot 2024-11-15 at 10 16 15 AM" src="https://github.com/user-attachments/assets/c425bd5e-f6e4-4217-ba52-c24b4be8a03d"> |
Dark mode:
- Used internationalization (i18n) …
> PM-14573: Add ToolbarButtonStyle to update a toolbar button's disabled state color

- BitwardenShared/Core/Platform/Services/ServiceContainer.swift
- BitwardenShared/Core/Vault/Services/SyncService.swift
- BitwardenShared/Core/Vault/Services/SyncServiceTests.swift
[PM-14962](https://bitwarden.atlassian.net/browse/PM-14962)
If a push notification triggers a background sync while the vault is locked, we should wait on adding the organization’s keys to the SDK until the user unlocks their vault. Currently it happens as part of sync which causes an error to be thrown by the SDK.
This fixes a Crashlytics error where an SDK error is logged: `BitwardenSdk.BitwardenError: The client vault is locked and needs to be unlocked before use.`
- Communicated to DevOps any …
> PM-14962: Don't add organization keys to SDK after sync if vault is locked

- .github/workflows/github-release.yml
- .github/workflows/release-branch.yml
[PM-11598](https://bitwarden.atlassian.net/browse/PM-11598)
Adds workflows for creating GitHub Releases and release branches. These have been tested in https://github.com/bitwarden/android first.
- 🤔 …
> [PM-11598] Add workflows for creating GitHub Releases and release branches

- BitwardenShared/Core/Platform/Models/Enum/FeatureFlag.swift
- BitwardenShared/Core/Platform/Models/Enum/FeatureFlagTests.swift
- BitwardenShared/UI/Vault/VaultItem/AddEditItem/AddEditItemProcessorTests.swift
- BitwardenShared/UI/Vault/VaultItem/AddEditItem/AddEditSSHKeyItem/SSHKeyItemState.swift
- BitwardenShared/UI/Vault/VaultItem/CipherItemState.swift
[PM-15119](https://bitwarden.atlassian.net/browse/PM-15119)
Fix SSH key item should be able to be cloned.
Additionally, enabled `ssh-key-vault-item ` feature flag to be remotely configured.
- 🤔 …
> [PM-15119] Fix SSH Key item cloning issue

- BitwardenShared/Core/Auth/Services/KeychainRepository.swift
- BitwardenShared/Core/Auth/Services/KeychainRepositoryTests.swift
[PM-10913](https://bitwarden.atlassian.net/browse/PM-10913)
This fixes an issue where a TDE user who is requesting admin approval closes the app before approval is granted. This ends up logging the user out and when they launch the app again and do SSO, they land back on the approval screen even if approval was previously granted. The pending login request was being deleted when the user was logged out. This removes it from being deleted when logging out.
https://github.com/user-attachments/assets/e90f98b4-b4b4-4285-b958-83b11fec292e
- Used internationalization (i18n) for all …
> PM-10913: Fix pre-approved users are forced to request admin approval

- .github/workflows/github-release.yml
- Scripts/download-artifacts.sh
PM-11598
Started as a fix for iOS artifacts upload, ended up as bigger revamp of the GitHub Release creation workflow. Improvements:
1. Gets Version info from run artifacts
2. Replaced third-party action with GH CLI
3. Automated notes now handle tags in unconnected branches (ie, release branches with cherry picks 🍒 ⛏️ )
4. Run artifacts are now zipped and properly uploaded
5. 🍥 Logs  
- Updated any necessary documentation (Confluence, contributing docs) …
> [PM-11598] fix: GitHub Release v2

- BitwardenShared/UI/Auth/Login/SingleSignOn/SingleSignOnProcessor.swift
- BitwardenShared/UI/Auth/Login/SingleSignOn/SingleSignOnProcessorTests.swift
[PM-13319](https://bitwarden.atlassian.net/browse/PM-13319)
When using SSO and a claimed domain, the organization's identifier was being overwritten by the saved organization identifier. That led to downstream errors when the identifier was later used after SSO authentication. This fixes that to only use the saved organization identifier if the API doesn't return an organization identifier.
- Updated any necessary documentation (Confluence, contributing …
> PM-13319: Fix unable to JIT into domain claimed organization

- BitwardenShared/Core/Tools/Repositories/SendRepository.swift
- BitwardenShared/Core/Tools/Repositories/SendRepositoryTests.swift
- BitwardenShared/Core/Tools/Repositories/TestHelpers/MockSendRepository.swift
- BitwardenShared/Core/Vault/Repositories/TestHelpers/MockVaultRepository.swift
- BitwardenShared/Core/Vault/Repositories/VaultRepository.swift
- BitwardenShared/Core/Vault/Repositories/VaultRepositoryTests.swift
- BitwardenShared/UI/Tools/Send/Send/SendList/SendListProcessor.swift
- BitwardenShared/UI/Tools/Send/Send/SendList/SendListProcessorTests.swift
- BitwardenShared/UI/Vault/Vault/VaultGroup/VaultGroupProcessor.swift
- BitwardenShared/UI/Vault/Vault/VaultList/VaultListProcessor.swift
- BitwardenShared/UI/Vault/Vault/VaultList/VaultListProcessorTests.swift
https://bitwarden.atlassian.net/browse/PM-15416
This changes the behavior of pull-to-refresh to respect time gates and other business logic around when we should actually do a refresh. It does not change the behavior of other places we trigger a manual refresh.
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) …
> [PM-15416] Change pull-to-refresh to not force a sync

- BitwardenShared/UI/Auth/IntroCarousel/IntroCarouselProcessor.swift
- BitwardenShared/UI/Auth/IntroCarousel/IntroCarouselProcessorTests.swift
- BitwardenShared/UI/Auth/Landing/LandingProcessor.swift
- BitwardenShared/UI/Auth/Landing/LandingProcessorTests.swift
- BitwardenShared/UI/Auth/StartRegistration/StartRegistrationAction.swift
- BitwardenShared/UI/Auth/StartRegistration/StartRegistrationProcessor.swift
- BitwardenShared/UI/Auth/StartRegistration/StartRegistrationProcessorTests.swift
- BitwardenShared/UI/Auth/StartRegistration/StartRegistrationView.swift
[PM-14632](https://bitwarden.atlassian.net/browse/PM-14632)
From the create account screen in the email verification flow, if you change the environment to an environment that doesn't support email verification, attempting to create an account will fail because the environment doesn't have the updated endpoints. This changes that to switch back to the legacy create account flow.
https://github.com/user-attachments/assets/6c60b706-082d-4c58-aade-a95e0d532f7e
- Communicated to DevOps any deployment …
> PM-14632: Revert to legacy create account flow if updated environment doesn't support email verification

- .github/workflows/CI-main.yml
https://bitwarden.atlassian.net/browse/PM-9375
When building the [previous PR for this](https://github.com/bitwarden/ios/pull/1151), changes were made over time to how `CI - main` would invoke the Simulator build, but we missed the split of variant and mode into two properties. This fixes that invocation.
- 📝 …
> Fix how CI main invokes simulator build

- BitwardenShared/Core/Platform/Models/Enum/FeatureFlag.swift
- BitwardenShared/Core/Platform/Models/Enum/FeatureFlagTests.swift
[BITAU-186](https://livefront.atlassian.net/browse/BITAU-186)
This PR moves the `enableAuthenticatorSync` feature flag into the remotely configurable list. It remains defaulted to `false` but this allows us to remotely enable it when we want to roll out the feature. …
> [BITAU-186] Enable Remote Config for Sync Feature Flag

- BitwardenShared/UI/Vault/VaultItem/AddEditItem/AddEditItemProcessor.swift
- BitwardenShared/UI/Vault/VaultItem/AddEditItem/AddEditItemProcessorTests.swift
- BitwardenShared/UI/Vault/VaultItem/CipherItemState.swift
- BitwardenShared/UI/Vault/VaultItem/CipherItemStateTests.swift
https://bitwarden.atlassian.net/browse/PM-15419
This is a defect on https://github.com/bitwarden/ios/pull/1130
There was an issue where we were showing the Delete button on the Edit Item screen even when a user didn't have Manage permissions for the collection that item was in. This was because when finding relevant collections, we were explicitly only getting ones that weren't readonly—which meant that when computing whether or not the user could delete the item, it would look like the item wasn't in any collections, which means it can be deleted. This updates the logic for getting those collections to include readonly collections.
- …
> [PM-12991] Don't show delete on edit screen if user can't delete

- BitwardenShared/Core/Auth/Repositories/AuthRepository.swift
- BitwardenShared/Core/Auth/Repositories/AuthRepositoryTests.swift
- BitwardenShared/Core/Auth/Repositories/TestHelpers/MockAuthRepository.swift
- BitwardenShared/UI/Auth/AuthRouterTests.swift
- BitwardenShared/UI/Auth/Extensions/AuthRouter+Redirects.swift
- BitwardenShared/UI/Auth/ProfileSwitcher/ProfileSwitcherHandler.swift
- BitwardenShared/UI/Platform/Application/AppProcessor.swift
- BitwardenShared/UI/Platform/Application/AppProcessorTests.swift
- BitwardenShared/UI/Vault/Vault/VaultList/VaultListProcessorTests.swift
[PM-11494](https://bitwarden.atlassian.net/browse/PM-11494)
This update addresses the issue where session timeouts are not recorded when a user switches accounts.
- The ```lastActiveTime``` is now recorded whenever a user switches to a different account.
- A session timeout verification is performed before displaying the profile switcher.
- 👍 …
> PM-11494: fixed session timeout not being respected when switch account

- BitwardenShared/UI/Platform/Application/Extensions/View+Toolbar.swift
- BitwardenShared/UI/Platform/Settings/Settings/Vault/Folders/FoldersView.swift
- BitwardenShared/UI/Platform/Settings/Settings/Vault/Folders/FoldersViewTests.swift
- BitwardenShared/UI/Tools/Send/Send/SendList/SendListView.swift
- BitwardenShared/UI/Tools/Send/Send/SendList/SendListViewTests.swift
- BitwardenShared/UI/Vault/Vault/AutofillList/VaultAutofillListAction.swift
- BitwardenShared/UI/Vault/Vault/AutofillList/VaultAutofillListProcessor+Fido2Tests.swift
- BitwardenShared/UI/Vault/Vault/AutofillList/VaultAutofillListProcessor.swift
- BitwardenShared/UI/Vault/Vault/AutofillList/VaultAutofillListProcessorTests.swift
- BitwardenShared/UI/Vault/Vault/AutofillList/VaultAutofillListView.swift
- BitwardenShared/UI/Vault/Vault/AutofillList/VaultAutofillListViewTests.swift
- BitwardenShared/UI/Vault/Vault/VaultGroup/VaultGroupView.swift
- BitwardenShared/UI/Vault/Vault/VaultGroup/VaultGroupViewTests.swift
- BitwardenShared/UI/Vault/Vault/VaultItemSelection/VaultItemSelectionView.swift
- BitwardenShared/UI/Vault/Vault/VaultItemSelection/VaultItemSelectionViewTests.swift
- BitwardenShared/UI/Vault/Vault/VaultList/VaultListView.swift
- BitwardenShared/UI/Vault/Vault/VaultList/VaultListViewTests.swift
[PM-15388](https://bitwarden.atlassian.net/browse/PM-15388)
Removes the plus button from the navigation bar on screens where the FAB was previously added.
| --- | --- |
| <img width="568" alt="Screenshot 2024-12-05 at 10 32 38 AM" src="https://github.com/user-attachments/assets/b5124aff-f2cb-4cea-8340-7bf5b1935493"> | <img width="568" alt="Screenshot 2024-12-05 at 10 32 08 AM" src="https://github.com/user-attachments/assets/99b93076-2dc8-495e-9e6a-78fca27af210"> |
- Communicated to …
> PM-15388: Remove plus button from navigation bars on screens which have a FAB

- BitwardenShared/Core/Tools/Services/Temp/ClientExportersProtocol+Extensions.swift
PM-14800
Fix CI build on release because it was using `fixture` from DEBUG builds which was breaking.
Changed the fixtures array to be empty; it will be updated in a future PR. …
> [PM-14800] Fix importCxf so it doesn't break build in non-debug builds.

- BitwardenShared/Core/Platform/Models/Domain/EnvironmentUrlData.swift
- BitwardenShared/Core/Platform/Models/Domain/EnvironmentUrlDataTests.swift
- BitwardenShared/Core/Platform/Models/Domain/EnvironmentUrls.swift
- BitwardenShared/Core/Platform/Models/Domain/EnvironmentUrlsTests.swift
- BitwardenShared/Core/Platform/Services/EnvironmentService.swift
- BitwardenShared/Core/Platform/Services/EnvironmentServiceTests.swift
- BitwardenShared/Core/Platform/Services/TestHelpers/MockEnvironmentService.swift
https://bitwarden.atlassian.net/browse/PM-8216
This adds additional URLs to the Environment Service, Environment URLs, and Environment URL Data objects for 1) changing email (which is currently just the account screen) and 2) setting up two-factor authentication. These will be used by new screens in the future.
This also adds new tests to backfill some gaps in our test coverage.
This also does a bit of minor refactoring to unify casing structure inside each of these classes to follow the [Swift API Design Guidelines](https://www.swift.org/documentation/api-design-guidelines/), which suggests that "URL" should be capitalized inside of properties and function names. Ideally we would also change `EnvironmentUrls` and `EnvironmentUrlData` to `EnvironmentURLs` and `EnvironmentURLData` for this …
> [PM-8216] Add Change Email and Set Up Two-Factor URLs

- .github/workflows/github-release.yml
[PM-11598](https://bitwarden.atlassian.net/browse/PM-11598)
Adds version input overrides to GitHub Release workflows, enabling 🛹 stake holders to continue the release process when the build workflow doesn't provide the version-info file. If nothing is provided we'll fallback to 0.0.0 (0). …
> [PM-11598] chore: Add version overrides to GitHub Release workflow

- .github/workflows/release-branch.yml
PM-16211
The previous method to retrieve the last release git tag only worked when all tags are in the main branch. We'll now get the last tag across all branches.
While at it removed the rc prefix input which won't be used in this repo. …
> [PM-16211] chore(ci): Fix hotfix branch creation workflow by retrieving the last tag across all branches

- BitwardenShared/UI/Platform/Application/Appearance/Styles/SecondaryButtonStyle.swift
[PM-16239](https://bitwarden.atlassian.net/browse/PM-16239)
This fixes an issue where the secondary button style wasn't receiving tap events when tapping on the transparent background area of the button.
- …
> PM-16239: Fix tap area of SecondaryButtonStyle

- Bitwarden/Application/SceneDelegate.swift
https://bitwarden.atlassian.net/browse/PM-16213
Currently, the debug menu can be opened by shaking the device or triple tapping with 3 fingers. The latter isn’t possible to do in a Simulator and requires two hands while using a physical device. 
This PR addresses that by reducing the number of required fingers to 1. …
> [PM-16213] feat: Reduce the required fingers to open the debug menu to 1

- BitwardenShared/UI/Vault/Utilities/HasTOTPCodesSections.swift
- BitwardenShared/UI/Vault/Vault/AutofillList/VaultAutofillListProcessor.swift
The tests `VaultAutofillListProcessorTotpTests.test_refreshTOTPCodes_searchItems()` and `VaultAutofillListProcessorTotpTests.test_refreshTOTPCodes_searchItemsEmpty()` have had race conditions causing intermittent failures, particularly on CI.
The ultimate issue is that `VaultAutofillListProcessor.refreshTOTPCodes(searchItems:)` calls out to `HasTOTPCodesSections.refreshTOTPCodes(for:in:using:)`, which is a nonisolating function, to get a new value of `state.ciphersForSearch`. However, the tests—which are `@MainActor`—rely on waiting for a call being made inside that nonisolating function. Sometimes the test would pick up that change before execution would go back to the `.refreshTOTPCodes(searchItems:)` to get assigned to the variable, so the test was checking the variable's value before …
> [BEEEP] Fix intermittently failing tests

- Bitwarden/Application/Support/Settings.bundle/Acknowledgements/SwiftLint.plist
- BitwardenShared/UI/Platform/Application/Extensions/String.swift
- BitwardenShared/UI/Platform/Settings/Settings/About/AboutProcessorTests.swift
- BitwardenShared/UI/Platform/Settings/Settings/About/AboutState.swift
https://bitwarden.atlassian.net/browse/PM-16686
Some tests were failing because of hardcoded copyright strings set to 2024. This updates them to be dynamic. Along with this is an update to copyright in the acknowledgements bundle, along with updating to use an en-dash in the year range. …
> [PM-16686] Update copyrights to be dynamic

- BitwardenShared/Core/Platform/Models/Enum/FeatureFlag.swift
- BitwardenShared/Core/Platform/Models/Enum/FeatureFlagTests.swift
- BitwardenShared/UI/Auth/TwoFactorNotice/TwoFactorNoticeHelper.swift
- BitwardenShared/UI/Auth/TwoFactorNotice/TwoFactorNoticeHelperTests.swift
https://bitwarden.atlassian.net/browse/PM-8216 but see discussion also at: https://bitwarden.atlassian.net/browse/PM-8217?focusedCommentId=80853
This adds a local feature flag, `ignore-environment-check`, [matching Android's name](https://github.com/bitwarden/android/blob/main/app/src/main/java/com/x8bit/bitwarden/data/platform/manager/model/FlagKey.kt#L168). When this flag is `true`, then the Two-Factor notice will not take into account the user's region when determining if the notice should be displayed, which will make it easier to develop or test this screen, because it can now work against our non-prod environments.
- Protected …
> [PM-8216] Add ignore-environment-check flag to make dev/QA of the two-factor notice easier

- BitwardenShared/UI/Vault/Vault/VaultCoordinator.swift
https://bitwarden.atlassian.net/browse/PM-16776
This adds a Back button to the second screen of the Two-Factor Notice, where the user can set up their two-factor authentication. This is accomplished by making the navigation bar not be hidden, and instead be transparent. …
> [PM-16776] Add back button to the set up two-factor screen

- BitwardenShared/UI/Vault/VaultItem/AddEditItem/AddEditItemView.swift
- BitwardenShared/UI/Vault/VaultItem/EditCollections/EditCollectionsView.swift
- BitwardenShared/UI/Vault/VaultItem/MoveToOrganization/MoveToOrganizationView.swift
> [QA-961] Adding missing AutomationID to EditCollection list

- Scripts/build.sh
https://bitwarden.atlassian.net/browse/PM-16533
This fixes an implicit reference to `project.yml` that was missed in [PR 1231](https://github.com/bitwarden/ios/pull/1231), and both makes it explicit and refers correctly to `project-pm.yml`. …
> [PM-16533] Include proper reference to project-pm.yml

- BitwardenShared/UI/Tools/ImportCXP/ImportCXP/ImportCXPProcessor.swift
- BitwardenShared/UI/Tools/ImportCXP/ImportCXP/ImportCXPProcessorTests.swift
- BitwardenShared/UI/Tools/ImportCXP/ImportCXP/ImportCXPState.swift
- BitwardenShared/UI/Tools/ImportCXP/ImportCXP/ImportCXPStateTests.swift
- BitwardenShared/UI/Tools/ImportCXP/ImportCXPCoordinator.swift
[PM-15359](https://bitwarden.atlassian.net/browse/PM-15359)
Fail Credential Exchange import if personal ownership policy is enabled.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry …
> [PM-15359] Consider Credential Exchange import policies

- BitwardenShared/UI/Vault/VaultItem/AuthenticatorKeyCapture/ManualEntryView.swift
> [QA-965] Adding accesibilityIDs for Manual TOTP entry page elements

- .github/workflows/test.yml
PM-17135
Updates test.yml pull request target and sets a job limit timeout, as a stopgap while we figure what's causing some runs to hang. E.g. https://github.com/bitwarden/ios/actions/runs/12776029096/
- …
> [PM-17135] Update test.yml target and set job timeout limit

- .github/workflows/test.yml
PM-16183
Some test runs are hanging until the runner reaches the timeout limit (e.g. https://github.com/bitwarden/ios/actions/runs/12776029096/). While troubleshooting it I noticed logs weren't correctly ordered, which is due to our testing suit running concurrently and us missing `NSUnbufferedIO=YES`, per xcbeautify docs ([ref](https://github.com/cpisciotta/xcbeautify?tab=readme-ov-file#usage).
While setting that flag would help, for the time being we're temporarily removing xcbeautify until we figure what's causing tests to hang.
- Used internationalization (i18n) for all UI …
> [PM-16183] Temporarily remove xcbeautify to troubleshoot hanging test runs

- BitwardenShared/Core/Platform/Services/Stores/DataStore.swift
Fixes the following CoreData test warnings:
```
⚠️  CoreData: Multiple NSEntityDescriptions claim the NSManagedObject subclass 'BitwardenShared.CipherData' so +entity is unable to disambiguate.
CoreData: warning: 'CipherData' from NSManagedObjectModel claims 'BitwardenShared.CipherData'.
```
- 📝 (`:memo:`) or …
> Fix CoreData test warnings

- .github/workflows/test.yml
- BitwardenShared/Core/Vault/Models/Enum/CipherTypeTests.swift
https://bitwarden.atlassian.net/browse/PM-17194
1. Splits test.yml in test and report jobs to reduce the permissions available during the build process. 
2. Adds a comment to the PR when code coverage report upload fails. [Example](https://github.com/bitwarden/android/pull/4538#issuecomment-2580778503)
3. While at it, fixes the codecov plugin input by removing it. In V5 it would need to be `plugins` but, given that we're taking care of building first we don't seem to need that plugin.
> [!IMPORTANT]
> About 3., while testing the initial changes I noticed that when the codecov action fails, it's a silent error by design and won't fail the workflow job. This is the case if the coverage report can't be found for instance. Discussing it with @SaintPatrck we agreed that uploading code coverage …
> [PM-17194] Split test.yml job 

- Scripts/bootstrap.sh
PM-16212
Improves bootstrap.sh version mismatch check to handle multiple xcodes installed. The actual fix is `head -n 1` but while at it, we're now checking `xcodebuild -version` first and falling back to `system_profiler SPDeveloperToolsDataType` if it fails. This will happen on fresh installs, before xcode-select is configured. 
This check was introduced in https://github.com/bitwarden/ios/pull/1221 …
> [PM-16212] Fix: bootstrap version mismatch fails when multiple xcodes are installed

- Bitwarden/Application/SceneDelegate.swift
- BitwardenShared/Core/Tools/Repositories/ExportCXFCiphersRepository.swift
- BitwardenShared/Core/Tools/Repositories/ExportCXFCiphersRepositoryTests.swift
- BitwardenShared/Core/Tools/Repositories/ImportCiphersRepository.swift
- BitwardenShared/Core/Tools/Repositories/ImportCiphersRepositoryTests.swift
- BitwardenShared/Core/Tools/Repositories/TestHelpers/MockExportCXFCiphersRepository.swift
- BitwardenShared/Core/Tools/Utilities/CredentialManagerFactory.swift
- BitwardenShared/Core/Tools/Utilities/CredentialManagerFactoryTests.swift
- BitwardenShared/Core/Tools/Utilities/TestHelpers/MockCredentialManagerFactory.swift
- BitwardenShared/Core/Vault/Services/TestHelpers/ASImportableAccount+Extensions.swift
- BitwardenShared/Core/Vault/Services/TestHelpers/ASImportableItem+Extensions.swift
- BitwardenShared/UI/Tools/ExportCXF/ExportCXF/ExportCXFProcessor.swift
- BitwardenShared/UI/Tools/ExportCXF/ExportCXF/ExportCXFProcessorTests.swift
- BitwardenShared/UI/Tools/ImportCXF/ImportCXF/ImportCXFProcessor.swift
- BitwardenShared/UI/Tools/ImportCXF/ImportCXF/ImportCXFProcessorTests.swift
[PM-16555](https://bitwarden.atlassian.net/browse/PM-16555)
Remove compiler checks: `#if compiler(>=6.0.3)` given that now CI/CD is using Xcode 16.2.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more …
> [PM-16555] Remove Xcode 16.2 compiler checks (>= 6.0.3)

- Scripts/alpha_update_cxp_infoplist.sh
- Scripts/build.sh
- Scripts/select_variant.sh
- Scripts/update_app_ci_build_info.sh
Fix build.yml failing when CXP compiler flag is used due to missing `alpha_update_cxp_infoplist.sh`. This is due to build scripts being called from the repo root instead of the `Scripts` folder. 
- 🤔 …
> [PM-17461][PM-14800] Fix: CXP build fails due to wrong script path

- Bitwarden/Application/SceneDelegate.swift
- BitwardenShared/Core/Tools/Repositories/ImportCiphersRepository.swift
- BitwardenShared/Core/Tools/Repositories/ImportCiphersRepositoryTests.swift
- BitwardenShared/Core/Tools/Utilities/CredentialManagerFactory.swift
- BitwardenShared/Core/Tools/Utilities/CredentialManagerFactoryTests.swift
- BitwardenShared/Core/Tools/Utilities/TestHelpers/MockCredentialManagerFactory.swift
- BitwardenShared/Core/Vault/Services/ExportVaultService.swift
- BitwardenShared/Core/Vault/Services/ExportVaultServiceTests.swift
- BitwardenShared/Core/Vault/Services/TestHelpers/ASImportableAccount+Extensions.swift
- BitwardenShared/Core/Vault/Services/TestHelpers/ASImportableItem+Extensions.swift
- BitwardenShared/Core/Vault/Services/TestHelpers/MockExportVaultService.swift
- BitwardenShared/UI/Platform/Settings/SettingsCoordinator.swift
- BitwardenShared/UI/Platform/Settings/SettingsCoordinatorTests.swift
- BitwardenShared/UI/Tools/ImportCXP/ImportCXP/ImportCXPProcessor.swift
- BitwardenShared/UI/Tools/ImportCXP/ImportCXP/ImportCXPProcessorTests.swift
- Configs/BitwardenSharedTests-Debug.xcconfig
- Configs/BitwardenSharedTests-Release.xcconfig
- project.yml
[PM-17467](https://bitwarden.atlassian.net/browse/PM-17467)
**Cherry pick of #1295 but targeting release branch.**
Wrap all Credential Exchange related APIs into the compiler flag `SUPPORTS_CXP` so those symbols are not added to the final IPA until Apple has the final version of the APIs. If we don't wrap them, then if Apple decides to do a breaking change in those APIs it could lead to a crash in the app.
Additionally, configs files were added and `project-pm.yml` has been updated so BitwardenSharedTests target can also have `SWIFT_ACTIVE_COMPILATION_CONDITIONS` available automatically depending on what's being set on the config.
- …
> [PM-17467] 🍒 Wrapped Credential Exchange related APIs into SUPPORTS_CXP compiler flag (#1295)

- BitwardenShared/UI/Tools/Send/SendItem/AddEditSendItem/AddEditSendItemState.swift
- BitwardenShared/UI/Tools/Send/SendItem/AddEditSendItem/AddEditSendItemStateTests.swift
[PM-17627](https://bitwarden.atlassian.net/browse/PM-17627)
The send expiration date was removed from the UI in https://github.com/bitwarden/ios/pull/1297. Attempting to edit a send that is expired results in a server error. Since the expiration date can no longer be changed, if the send has an expiration date it will be reset to the deletion date upon saving the send. 
- Updated any necessary documentation (Confluence, contributing docs) or informed …
> PM-17627: Reset send expiration to deletion date on edit

- BitwardenShared/Core/Platform/Services/NotificationCenterServiceTests.swift
[PM-17710](https://bitwarden.atlassian.net/browse/PM-17710)
Fix NotificationCenterServiceTests race condition failure that caused tests to execute until timeout or fail randomly with the new `maximum-test-execution-time-allowance` setting.
This was caused when `notificationCenter.post(...)` was executed before the `iterator.next()` started. Therefore the notification value was missed from the publisher and the test never ended.
In order to fix this without adding an explicit `Task.sleep(...)` I've moved the `for await in publisher` to the setup where a flag is set when the value is received and then I call the `notificationCenter.post(...)` inside the `try await waitForAsync { ... }` so if the first time the post is missed then it will loop again in it `waitForAsync` and post again until …
> [PM-17710] Fix NotificationCenterServiceTests race condition failure

- BitwardenShared/Core/Auth/Models/Request/IdentityTokenRequestModel.swift
- BitwardenShared/Core/Auth/Models/Request/IdentityTokenRequestModelTests.swift
- BitwardenShared/Core/Auth/Models/Response/IdentityTokenErrorModel.swift
- BitwardenShared/Core/Auth/Services/API/Auth/AuthAPIServiceTests.swift
- BitwardenShared/Core/Auth/Services/API/Auth/Fixtures/APITestData+Auth.swift
- BitwardenShared/Core/Auth/Services/API/Auth/Fixtures/IdentityTokenNewDeviceError.json
- BitwardenShared/Core/Auth/Services/API/Auth/Requests/IdentityTokenRequest.swift
- BitwardenShared/Core/Auth/Services/API/Auth/Requests/IdentityTokenRequestTests.swift
- BitwardenShared/UI/Auth/Login/LoginProcessor.swift
- BitwardenShared/UI/Auth/Login/LoginWithDevice/LoginWithDeviceProcessor.swift
- BitwardenShared/UI/Auth/Login/LoginWithDevice/LoginWithDeviceProcessorTests.swift
[PM-8222](https://bitwarden.atlassian.net/browse/PM-8222)
Identity will now send error 400 when a user tries to get a token with a new device. 
To verify the device, the user will have to send an otp code.
This PR updates the network layer request models to handle this error.
```
{
"error": "device_error",
"error_description": "New device verification required",
"ErrorModel": {
"Message": "new device verification required",
"Object": "error"
}
}
```
- …
> [PM-8222] Identity new device verification

- BitwardenShared/UI/Tools/Generator/Generator/GeneratorProcessor.swift
- BitwardenShared/UI/Tools/Generator/Generator/GeneratorProcessorTests.swift
[PM-16141](https://bitwarden.atlassian.net/browse/PM-16141)
- fixes the generator screen ```get started``` button action with guided tour. …
> PM-16141: linked get started action with guided tour

- BitwardenShared/UI/Platform/Application/Views/BitwardenTextField.swift
> QA-1070: Fixing broken textField accessibility IDs

- BitwardenShared/Core/Tools/Repositories/ExportCXFCiphersRepository.swift
- BitwardenShared/Core/Tools/Repositories/ExportCXFCiphersRepositoryTests.swift
[PM-17935](https://bitwarden.atlassian.net/browse/PM-17935)
[PM-17936](https://bitwarden.atlassian.net/browse/PM-17936)
Filtered out organization items on Credential Exchange export as the SDK doesn't fully support them yet.
- ❓ …
> [PM-17935] Filtered out organization items on Credential Exchange export

- BitwardenShared/UI/Platform/Application/Views/BitwardenTextField.swift
- BitwardenShared/UI/Vault/VaultItem/AddEditItem/AddEditItemView.swift
[PM-11712](https://bitwarden.atlassian.net/browse/PM-11712)
Given the previous fix #1292 the scroll was behaving incorrectly and scrolling back to the field focused when scrolling away from such field causing a lot of confusion. So this PR fixes it by removing the `KeyboardResponder` and setting the `scrollContentMargins` constantly instead of depending on whether the keyboard is shown which has a better UX given that the animation doesn't jump and fixes the aforementioned issue.
https://github.com/user-attachments/assets/c053b101-c508-4d9e-8136-5c2acae185cf
https://github.com/user-attachments/assets/686d41ca-f95d-4301-9efc-224cdbbe40ea
- …
> [PM-11712] Fix scroll going back to focus when scrolling and dismissing the keyboard

- BitwardenShared/Core/Platform/Services/API/Extensions/JSONDecoder+Bitwarden.swift
- BitwardenShared/Core/Platform/Services/API/Extensions/JSONDecoderBitwardenTests.swift
[PM-17935](https://bitwarden.atlassian.net/browse/PM-17935)
Fix Credential Exchange decoding error happening from iOS 18.3 where `credentialId` and `rpId` has changed their final `d` casing so we don't need the custom management of that anymore from that iOS version.
Prior to iOS 18.3: `credentialID` and `rpID` which doesn't match the same format as in the SDK, thus the custom logic is needed for decoding.
After iOS 18.3: `credentialId` and `rpId` which matches the same format as in the SDK.
- …
> [PM-17935] Fixed CXF decoder for iOS 18.3

- BitwardenShared/UI/Platform/Settings/Settings/About/AboutProcessor.swift
- BitwardenShared/UI/Platform/Settings/Settings/About/AboutProcessorTests.swift
[PM-18271](https://bitwarden.atlassian.net/browse/PM-18271)
The following tests have been failing for me because I override the bundle ID for running on device. This updates the tests to inject the bundle ID so it's not dependent on the app's bundle ID at the time of running tests.
> AboutProcessorTests.swift:158 test_receive_versionTapped_noAdditionalInfo(): XCTAssertEqual failed: ("Optional("© Bitwarden Inc. 2015–2025\n\nVersion: 2024.6.0 (1)\n📱 iPhone14,2 🍏 iOS 16.4 📦 Unkown")") is not equal to ("Optional("© Bitwarden Inc. 2015–2025\n\nVersion: 2024.6.0 (1)\n📱 iPhone14,2 🍏 iOS 16.4 📦 Production")")
> 
> AboutProcessorTests.swift:181 test_receive_versionTapped_withAdditionalInfo(): XCTAssertEqual failed: ("Optional("© Bitwarden Inc. 2015–2025\n\nVersion: 2024.6.0 (1)\n📱 iPhone14,2 🍏 iOS …
> PM-18271: Fix AboutProcessorTests if using overridden bundle ID

- BitwardenShared/Core/Platform/Models/Enum/FeatureFlag.swift
- BitwardenShared/Core/Platform/Models/Enum/FeatureFlagTests.swift
- BitwardenShared/Core/Platform/Services/ClientService.swift
- BitwardenShared/Core/Platform/Services/ClientServiceTests.swift
[PM-18265](https://bitwarden.atlassian.net/browse/PM-18265)
Make feature flag `cipher-key-encryption` default value `false`. …
> [PM-18265] Made cipher key encryption feature flag default value -> false

- BitwardenShared/UI/Platform/Application/Support/Localizations/en.lproj/Localizable.strings
[PM-18423](https://bitwarden.atlassian.net/browse/PM-18423)
Removes the period from empty state string for a vault group folder or collection. …
> PM-18423: Update empty folder and collection string

- BitwardenShared/UI/Auth/Login/TwoFactorAuth/TwoFactorAuthProcessor.swift
- BitwardenShared/UI/Auth/Login/TwoFactorAuth/TwoFactorAuthProcessorTests.swift
- BitwardenShared/UI/Auth/Login/TwoFactorAuth/TwoFactorAuthState.swift
- BitwardenShared/UI/Auth/Login/TwoFactorAuth/TwoFactorAuthView.swift
- BitwardenShared/UI/Platform/Application/Support/Localizations/en.lproj/Localizable.strings
https://bitwarden.atlassian.net/browse/PM-8222
When device needs verification:
- Change title to `Verify your identity`
- Change continue button enabled to 8 chars instead of 6.
- Show error message `Invalid verification code` when the verification code is invalid.
**Title fix:**
**Continue button enabled:**
**Error message:**
- 👍 (`:+1:`) or similar …
> [PM-8222] New device verification page fixes

- BitwardenShared/UI/Auth/Login/TwoFactorAuth/TwoFactorAuthProcessor.swift
- BitwardenShared/UI/Auth/Login/TwoFactorAuth/TwoFactorAuthProcessorTests.swift
- BitwardenShared/UI/Auth/Login/TwoFactorAuth/TwoFactorAuthState.swift
- BitwardenShared/UI/Auth/Login/TwoFactorAuth/TwoFactorAuthView.swift
- BitwardenShared/UI/Platform/Application/Support/Localizations/en.lproj/Localizable.strings
(cherry picked from commit e29448fecb0981d7a7a6eb7ac216364e578df917)
https://bitwarden.atlassian.net/browse/PM-8222
Cherrypick remaining fixes from `main` into `rc` branch.
https://github.com/bitwarden/ios/pull/1381 …
> [PM-8222] Cherrypick - New device verification page fixes (#1381)

- BitwardenShared/Core/Auth/Repositories/AuthRepositoryTests.swift
- BitwardenShared/Core/Platform/Services/StateService.swift
- BitwardenShared/Core/Platform/Services/StateServiceTests.swift
- BitwardenShared/Core/Platform/Services/Stores/AppSettingsStore.swift
- BitwardenShared/Core/Platform/Services/Stores/AppSettingsStoreTests.swift
- BitwardenShared/Core/Platform/Services/Stores/TestHelpers/MockAppSettingsStore.swift
- BitwardenShared/Core/Platform/Services/TestHelpers/MockStateService.swift
- BitwardenShared/Core/Vault/Services/SyncService.swift
- BitwardenShared/Core/Vault/Services/SyncServiceTests.swift
- BitwardenShared/UI/Platform/Application/AppProcessor.swift
- BitwardenShared/UI/Platform/Application/AppProcessorTests.swift
[PM-18460](https://bitwarden.atlassian.net/browse/PM-18460)
When Remove Unlock with Pin policy is enabled and the user logs in, if there was Pin information in cache for such user it should be removed so the feature is disabled in the app after completing the login. …
> [PM-18460] Fix Remove Unlock with Pin policy logic on login

- BitwardenShared/Core/Auth/Repositories/AuthRepositoryTests.swift
- BitwardenShared/Core/Platform/Services/StateService.swift
- BitwardenShared/Core/Platform/Services/StateServiceTests.swift
- BitwardenShared/Core/Platform/Services/Stores/AppSettingsStore.swift
- BitwardenShared/Core/Platform/Services/Stores/AppSettingsStoreTests.swift
- BitwardenShared/Core/Platform/Services/Stores/TestHelpers/MockAppSettingsStore.swift
- BitwardenShared/Core/Platform/Services/TestHelpers/MockStateService.swift
- BitwardenShared/Core/Vault/Services/SyncService.swift
- BitwardenShared/Core/Vault/Services/SyncServiceTests.swift
- BitwardenShared/UI/Platform/Application/AppProcessor.swift
- BitwardenShared/UI/Platform/Application/AppProcessorTests.swift
[PM-18460](https://bitwarden.atlassian.net/browse/PM-18460)
🍒 Cherry-picked #1377 for `release/2025.02-rc7` branch.
When Remove Unlock with Pin policy is enabled and the user logs in, if there was Pin information in cache for such user it should be removed so the feature is disabled in the app after completing the login. …
> [PM-18460]: [RC] Fix Remove Unlock with Pin policy logic on login

- BitwardenShared/Core/Vault/Services/PolicyService.swift
- BitwardenShared/Core/Vault/Services/PolicyServiceTests.swift
[PM-18461](https://bitwarden.atlassian.net/browse/PM-18461)
Fix "Remove unlock with pin" policy not to be exempt from organizations where the user is Admin or Owner given that this policy applies to all members. …
> [PM-18461] [RC] Remove unlock with pin policy admin not exempt

- BitwardenShared/Core/Vault/Services/PolicyService.swift
- BitwardenShared/Core/Vault/Services/PolicyServiceTests.swift
[PM-18461](https://bitwarden.atlassian.net/browse/PM-18461)
Backport of #1388.
Fix "Remove unlock with pin" policy not to be exempt from organizations where the user is Admin or Owner given that this policy applies to all members.
- ❓ …
> [PM-18461] [Backport] Remove unlock with pin policy admin not exempt

- BitwardenShared/UI/Vault/Vault/AutofillList/VaultAutofillListEffect.swift
- BitwardenShared/UI/Vault/Vault/AutofillList/VaultAutofillListProcessor+Fido2Tests.swift
- BitwardenShared/UI/Vault/Vault/AutofillList/VaultAutofillListProcessor.swift
- BitwardenShared/UI/Vault/Vault/AutofillList/VaultAutofillListState.swift
- BitwardenShared/UI/Vault/Vault/AutofillList/VaultAutofillListView.swift
- BitwardenShared/UI/Vault/Vault/AutofillList/VaultAutofillListViewTests.swift
[PM-18486](https://bitwarden.atlassian.net/browse/PM-18486)
Fix on Fido2 credential creation excluded credential found flow, that when a user edits such excluded credential found and removes the passkey from it. Then on going back to the list screen the previous excluded credential shouldn't be shown and the normal Fido2 credential creation flow list should be shown. …
> [PM-18486] Fix register Fido2 credential excluded credential found flow

- BitwardenShared/UI/Vault/VaultItem/ViewItem/ViewItemView.swift
[PM-18244](https://bitwarden.atlassian.net/browse/PM-18244)
- This will fix #1344
I was able to reproduce this bug only on my old iPhone XR which runs on iOS16. 
The bug was like this:
<video src=https://github.com/user-attachments/assets/6ef028af-40c6-4deb-8c3f-1c237f21d9b7 /> …
> PM-18244: Fix close button ui bug on ViewItem screen

- BitwardenShared/UI/Vault/Vault/VaultList/VaultListProcessor.swift
- BitwardenShared/UI/Vault/Vault/VaultList/VaultListProcessorTests.swift
- BitwardenShared/UI/Vault/Vault/VaultList/VaultListSection.swift
- BitwardenShared/UI/Vault/Vault/VaultList/VaultListSectionTests.swift
[PM-18594](https://bitwarden.atlassian.net/browse/PM-18594)
If a user has existing login items in their vault, the coach marks for add login and in the generator should be dismissed.
- 🤔 (`:thinking:`) or …
> [PM-18594] [RC] Hide coach marks if user has existing login items

- BitwardenShared/UI/Vault/Vault/VaultList/VaultListProcessor.swift
- BitwardenShared/UI/Vault/Vault/VaultList/VaultListProcessorTests.swift
- BitwardenShared/UI/Vault/Vault/VaultList/VaultListSection.swift
- BitwardenShared/UI/Vault/Vault/VaultList/VaultListSectionTests.swift
[PM-18594](https://bitwarden.atlassian.net/browse/PM-18594)
Backport of #1390.
If a user has existing login items in their vault, the coach marks for add login and in the generator should be dismissed.
- 🤔 …
> [PM-18594] [Backport] Hide coach marks if user has existing login items

- BitwardenShared/UI/Vault/VaultItem/AddEditItem/AddEditLoginItem/AddEditLoginItemView.swift
- BitwardenShared/UI/Vault/VaultItem/ViewItem/ViewLoginItem/ViewLoginItemView.swift
> QA-1083: Adding accessibility IDs for Passkey elements

- BitwardenShared/UI/Platform/Application/Views/PasswordText.swift
[PM-18386](https://bitwarden.atlassian.net/browse/PM-18386)
Fixes a crash when viewing the color coded unmasked password for long passwords in view item. I was able to reproduce this with a password length of 2000. The crash didn't contain much information, but the contained the following line in the stack trace:
```
#0	0x000000026190e338 in SwiftUI.ConcatenatedTextStorage.resolve<τ_0_0 where τ_0_0: SwiftUI.ResolvedTextContainer>(into: inout τ_0_0, in: SwiftUI.EnvironmentValues, with: SwiftUI.Text.ResolveOptions) -> () ()
```
It seemed like this was due to concatenating `Text` instances when displaying the color coded unmasked password. I switched to using AttributedString and haven't been able to reproduce it.
- All formatters and local linters executed …
> [PM-18386] Fix crash when viewing long passwords

- BitwardenShared/Core/Platform/Services/AuthenticatorSyncService.swift
- BitwardenShared/Core/Platform/Services/AuthenticatorSyncServiceTests.swift
[PM-17634](https://bitwarden.atlassian.net/browse/PM-17634)
**Cherry pick of [https://github.com/bitwarden/ios/pull/1448](#1148) into the release branch**
Previously, when launching the app on a fresh install, we checked the feature flags for bitwarden.com before attempting to start the AuthenticatorSyncService. If the feature flag was initially disabled, the sync service would never start. This led to an issue where users logging into a self-hosted server—which has the feature flag enabled (`enable-pm-bwa-sync`)—would not see sync events during that session, even if logging into a server that has the flag on. This caused the service to only start syncing after a full app restart which then had a fresh value for the feature flag.
Added the check to be inside of …
> 🍒 PM-17634 - Update When The App Checks If Authenticator Sync is Enabled

- BitwardenShared/Core/Auth/Repositories/AuthRepositoryTests.swift
- BitwardenShared/Core/Autofill/Services/AutofillCredentialService.swift
- BitwardenShared/Core/Autofill/Services/AutofillCredentialServiceTests.swift
- BitwardenShared/Core/Platform/Services/AuthenticatorSyncService.swift
- BitwardenShared/Core/Platform/Services/AuthenticatorSyncServiceTests.swift
- BitwardenShared/Core/Platform/Services/ConfigServiceTests.swift
- BitwardenShared/Core/Platform/Services/ServiceContainer.swift
- BitwardenShared/Core/Platform/Services/StateService.swift
- BitwardenShared/Core/Platform/Services/Stores/TestHelpers/MockAppSettingsStore.swift
- BitwardenShared/Core/Platform/Services/TestHelpers/ServiceContainer+Mocks.swift
- BitwardenShared/Core/Tools/Services/GeneratorDataStoreTests.swift
- BitwardenShared/Core/Vault/Repositories/VaultRepositoryTests.swift
- BitwardenShared/Core/Vault/Services/SyncService.swift
- BitwardenShared/Core/Vault/Services/SyncServiceTests.swift
- BitwardenShared/Core/Vault/Services/TestHelpers/MockVaultTimeoutService.swift
- BitwardenShared/Core/Vault/Services/VaultTimeoutService.swift
- BitwardenShared/Core/Vault/Services/VaultTimeoutServiceTests.swift
- BitwardenShared/UI/Auth/AuthRouterTests.swift
- BitwardenShared/UI/Autofill/Utilities/Fido2UserInterfaceHelper.swift
- BitwardenShared/UI/Autofill/Utilities/Fido2UserInterfaceHelperTests.swift
- BitwardenShared/UI/Autofill/Utilities/TestHelpers/MockFido2UserInterfaceHelper.swift
- BitwardenShared/UI/Platform/Application/AppProcessorTests.swift
- BitwardenShared/UI/Vault/Vault/AutofillList/VaultAutofillListProcessor+Fido2Tests.swift
- TestHelpers/Support/BaseBitwardenTestCase.swift
[PM-18439](https://bitwarden.atlassian.net/browse/PM-18439)
Fixes a few tests that have been intermittently failing on test runs. Most of these failures stem from concurrency issues where mocks or internal variables are accessed or mutated from separate threads. Moving mocks or tests or some protocols to the main actor to prevent these issues was the general theme around the fixes.
- `AppProcessorTests.test_appBackgrounded_setLastActiveTime`
- Caused by `MockVaultTimeoutService.lastActiveTime` being accessed from multiple threads.
- Fixed by moving `VaultTimeoutService` to the main actor.
- `Fido2UserInterfaceHelperTests.test_checkUserAndPickCredentialForCreation_errors`
- Caused by accessing the continuation from multiple threads?
- Fixed by moving `Fido2UserInterfaceHelper` to the main …
> [PM-18439] Fix flaky tests

- AuthenticatorBridgeKit/AuthenticatorBridgeDataStore.swift
- AuthenticatorShared/Core/Platform/Services/Stores/DataStore.swift
[PM-18439](https://bitwarden.atlassian.net/browse/PM-18439)
Fixes some CoreData warnings when running tests:
```
⚠️  CoreData: Multiple NSEntityDescriptions claim the NSManagedObject subclass 'AuthenticatorBridgeKit.AuthenticatorBridgeItemData' so +entity is unable to disambiguate.
CoreData: warning: 'AuthenticatorBridgeItemData' from NSManagedObjectModel (claims 'AuthenticatorBridgeKit.AuthenticatorBridgeItemData'.
❌ CoreData: +[AuthenticatorBridgeKit.AuthenticatorBridgeItemData entity] Failed to find a unique match for an NSEntityDescription to a managed object subclass
```
The `BitwardenShared` instance was previously fixed in #1276.
- …
> [PM-18439] Fix CoreData model warnings during tests

- BitwardenShared/Core/Platform/Models/Enum/FeatureFlag.swift
- BitwardenShared/Core/Platform/Models/Enum/FeatureFlagTests.swift
- BitwardenShared/UI/Vault/VaultItem/AddEditItem/AddEditItemProcessor.swift
- BitwardenShared/UI/Vault/VaultItem/AddEditItem/AddEditItemProcessorTests.swift
- BitwardenShared/UI/Vault/VaultItem/AddEditItem/AddEditItemState.swift
- BitwardenShared/UI/Vault/VaultItem/AddEditItem/AddEditItemView.swift
- BitwardenShared/UI/Vault/VaultItem/CipherItemState.swift
- BitwardenShared/UI/Vault/VaultItem/CipherItemStateTests.swift
- BitwardenShared/UI/Vault/VaultItem/ViewItem/ViewItemProcessor.swift
- BitwardenShared/UI/Vault/VaultItem/ViewItem/ViewItemProcessorTests.swift
- BitwardenShared/UI/Vault/VaultItem/ViewItem/ViewItemState.swift
- BitwardenShared/UI/Vault/VaultItem/ViewItem/ViewItemStateTests.swift
- BitwardenShared/UI/Vault/VaultItem/ViewItem/ViewItemView.swift
https://bitwarden.atlassian.net/browse/PM-18091
Use new cipher permissions properties to show or hide the delete and restore buttons on the UI.
https://github.com/user-attachments/assets/1598475b-303a-4f49-8914-b02fb75ea440
- ❓ …
> [PM-18091] Update cipher delete & restore permissions

- BitwardenShared/UI/Platform/Settings/Settings/About/EnableFlightRecorder/EnableFlightRecorderView.swift
- BitwardenShared/UI/Platform/Settings/Settings/About/FlightRecorderLogs/FlightRecorderLogsView.swift
[PM-19552](https://bitwarden.atlassian.net/browse/PM-19552)
#1483 added SwiftUI previews that use `PreviewTimeProvider()` which is behind a DEBUG #if/#endif macro. This fixes the failing release build.
https://github.com/bitwarden/ios/actions/runs/14365865412/job/40278544403#step:34:2186 …
> [PM-19552] Wrap SwiftUI previews in DEBUG #if/#endif to fix release build

- BitwardenShared/Core/Platform/Models/Enum/FeatureFlag.swift
- BitwardenShared/Core/Platform/Models/Enum/FeatureFlagTests.swift
- BitwardenShared/Core/Tools/Models/Domain/UsernameGenerationOptions.swift
- BitwardenShared/Core/Tools/Models/Domain/UsernameGenerationOptionsTests.swift
- BitwardenShared/UI/Platform/Application/Support/Localizations/en.lproj/Localizable.strings
- BitwardenShared/UI/Tools/Generator/Generator/GeneratorProcessor.swift
- BitwardenShared/UI/Tools/Generator/Generator/GeneratorProcessorTests.swift
- BitwardenShared/UI/Tools/Generator/Generator/GeneratorState+UsernameState.swift
- BitwardenShared/UI/Tools/Generator/Generator/GeneratorState.swift
- BitwardenShared/UI/Tools/Generator/Generator/GeneratorStateTests.swift
https://bitwarden.atlassian.net/browse/PM-3503
Support self-hosted AnonAddy server URLs in the username generator.
When the feature flag, AnonAddySelfHostAlias, is enabled users can enter the server URL for their self-hosted AnonAddy instance. When disabled, the default cloud URL is used. …
> [PM-3503] Add AnonAddy self-hosted server URL support

- Bitwarden/Application/AppIntents/LogoutAllAccountsIntent.swift
- Bitwarden/Application/AppIntents/ShortcutsProvider.swift
- Bitwarden/Application/Support/AppShortcutsLocalizations/en.lproj/AppShortcuts.strings
- BitwardenShared/Core/Auth/Repositories/TestHelpers/MockAuthRepository.swift
- BitwardenShared/UI/Platform/Application/AppContext.swift
- BitwardenShared/UI/Platform/Application/AppIntentMediator.swift
- BitwardenShared/UI/Platform/Application/AppIntentMediatorTests.swift
- BitwardenShared/UI/Platform/Application/AppProcessor.swift
- BitwardenShared/UI/Platform/Application/Support/Localizations/en.lproj/Localizable.strings
- BitwardenShared/UI/Platform/Application/TestHelpers/MockAppIntentMediator.swift
[PM-19372](https://bitwarden.atlassian.net/browse/PM-19372)
Implemented Log out all accounts App Intent and its Shortcut configuration.
ℹ️ No need for `PendingAppIntentAction` as the logout will be triggered in `AppProcessor -> checkIfExtensionSwitchedAccounts()` when going back to foreground.
⚠️ Merge #1443 first to the app intents feature branch.
- …
> [PM-19372] feat: Log out all accounts App Intent

- BitwardenShared/Core/Platform/Models/Enum/FeatureFlag.swift
- BitwardenShared/Core/Platform/Models/Enum/FeatureFlagTests.swift
- BitwardenShared/Core/Tools/Models/Domain/UsernameGenerationOptions.swift
- BitwardenShared/Core/Tools/Models/Domain/UsernameGenerationOptionsTests.swift
- BitwardenShared/Core/Tools/Models/Enum/ForwardedEmailServiceType.swift
- BitwardenShared/UI/Tools/Generator/Generator/GeneratorProcessor.swift
- BitwardenShared/UI/Tools/Generator/Generator/GeneratorProcessorTests.swift
- BitwardenShared/UI/Tools/Generator/Generator/GeneratorState+UsernameState.swift
- BitwardenShared/UI/Tools/Generator/Generator/GeneratorState.swift
- BitwardenShared/UI/Tools/Generator/Generator/GeneratorStateTests.swift
[PM-18262](https://bitwarden.atlassian.net/browse/PM-18262)
Add support for SimpleLogin Self-host server URL.
This also fixes an issue for SimpleLogin where the default URL to use for the service was not being passed and that's why the generation wasn't working.
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) …
> [PM-18262] feat: Implemented SimpleLogin Self-host server URL

- .github/workflows/build-bwa.yml
- .github/workflows/build.yml
- .github/workflows/test-bwa.yml
- .github/workflows/test.yml
- Brewfile
- Scripts/bootstrap.sh
PM-18414
_Splitting this change from the bigger CI restructuring branch._
Address a recurring dev experience gap by having a list of homebrew dependencies that can be used by our devs locally and in our CI - dependencies were regularly missed while setting up local dev environments. 
Also looked into pinning dependency versions, we would need to create our own tap. References: 
* [Homebrew - Brewfile](https://docs.brew.sh/Brew-Bundle-and-Brewfile#versions): "Homebrew is a [rolling release](https://en.wikipedia.org/wiki/Rolling_release) package manager so it does not support installing arbitrary older versions of software."
* [Homebrew - Versions](https://docs.brew.sh/Versions): "Homebrew’s versions should not be used to “pin” formulae to your personal requirements. You should instead …
> [PM-18414] CI restructuring #3 - Add Brewfile with version pinning

- AuthenticatorShared/Core/Platform/Models/Enum/FeatureFlag.swift
- AuthenticatorShared/Core/Platform/Services/ConfigService.swift
- BitwardenShared/Core/Platform/Models/Enum/FeatureFlag.swift
- BitwardenShared/Core/Platform/Models/Enum/FeatureFlagTests.swift
- BitwardenShared/Core/Platform/Services/ConfigService.swift
https://bitwarden.atlassian.net/browse/BWA-155
This is a small sideways refactor in the process of improving the `ConfigService` behavior between BWA and PM. In particular, this changes the `FeatureFlag.initialValues` variable from static to instance, to match things like `isRemotelyConfigured`. This makes eventually bringing `FeatureFlag` into `BitwardenKit` as a protocol easier, in addition to being more parallel with the other properties on `FeatureFlag`.
- Communicated to DevOps any deployment …
> [BWA-155] refactor: Change FeatureFlag.initialValues from static to an instance variable

- BitwardenShared/Core/Platform/Utilities/Constants.swift
- BitwardenShared/UI/Auth/Extensions/Alert+Auth.swift
- BitwardenShared/UI/Auth/Extensions/AlertAuthTests.swift
- BitwardenShared/UI/Platform/Application/Support/Localizations/en.lproj/Localizable.strings
[PM-8952](https://bitwarden.atlassian.net/browse/PM-8952)
From now on, pin must have a minimum length of 4.
| --- | --- |
|![image](https://github.com/user-attachments/assets/e61ec15c-27d4-4e6d-b7e8-99e29706b206)|![image](https://github.com/user-attachments/assets/18dc3bce-b0fe-4d8a-8fb4-51a55fb01413) | …
> [PM-8952] Implemented minimum length for pin

- BitwardenKit/Core/Platform/Services/API/HTTPServiceBuilder.swift
- BitwardenShared/Core/Platform/Services/API/APIService.swift
- BitwardenShared/Core/Platform/Services/API/FlightRecorderHTTPLogger.swift
- BitwardenShared/Core/Platform/Services/API/FlightRecorderHTTPLoggerTests.swift
- BitwardenShared/Core/Platform/Services/API/TestHelpers/APIService+Mocks.swift
- BitwardenShared/Core/Platform/Services/ServiceContainer.swift
- Networking/Sources/Networking/HTTPLogger.swift
- Networking/Sources/Networking/HTTPMethod.swift
- Networking/Sources/Networking/HTTPService.swift
- project-bwk.yml
Adds flight recorder network request and response logging. This logs the method, URL, and status code without any headers or bodies.
Sample logs:
```
2025-04-25T14:17:43-05:00: Request 78674DB1-8166-40C6-9470-000A4B4F6A86: POST https://identity.bitwarden.com/connect/token
2025-04-25T14:17:43-05:00: Response 78674DB1-8166-40C6-9470-000A4B4F6A86: https://identity.bitwarden.com/connect/token 200
2025-04-25T14:17:43-05:00: Request 61B57E6F-B48C-4A9A-931A-2726A5B346AC: GET https://api.bitwarden.com/config
2025-04-25T14:17:43-05:00: Response 61B57E6F-B48C-4A9A-931A-2726A5B346AC: https://api.bitwarden.com/config 200
2025-04-25T14:17:44-05:00: Request E7A8151A-EE1B-4F3A-899D-2A83544FCADA: GET https://api.bitwarden.com/sync …
```
> [PM-19577] Flight recorder network request and response logging

- BitwardenKit/Core/Platform/Services/API/Extensions/JSONEncoder+Bitwarden.swift
- BitwardenShared/Core/Tools/Repositories/ExportCXFCiphersRepositoryTests.swift
- BitwardenShared/Core/Tools/Repositories/ImportCiphersRepositoryTests.swift
- BitwardenShared/Core/Tools/Utilities/TestHelpers/MockCredentialManagerFactory.swift
With the `SUPPORTS_CXP` flag off by default, some classes used by the CXP and its testing flows got moved without the CXP code being updated. This fixes that with imports and proper scoping.
- 🤔 …
> fix: Handle SUPPORTS_CXP flag

- BitwardenShared/Core/Platform/Models/Enum/FeatureFlag.swift
- BitwardenShared/Core/Platform/Models/Enum/FeatureFlagTests.swift
- BitwardenShared/Core/Platform/Utilities/Constants.swift
- BitwardenShared/UI/Vault/Vault/VaultList/VaultListProcessor.swift
- BitwardenShared/UI/Vault/Vault/VaultList/VaultListProcessorTests.swift
https://bitwarden.atlassian.net/browse/PM-20147
Remove enable-debug-app-review-prompt feature flag from codebase. …
> [PM-20147] Remove enable-debug-app-review-prompt feature flag

- BitwardenShared/Core/Platform/Models/Data/FlightRecorderData.swift
- BitwardenShared/Core/Platform/Models/Data/FlightRecorderDataTests.swift
- BitwardenShared/Core/Platform/Models/Domain/Fixtures/FlightRecorderLogMetadata+Fixtures.swift
- BitwardenShared/Core/Platform/Models/Domain/FlightRecorderLogMetadata.swift
- BitwardenShared/Core/Platform/Models/Domain/FlightRecorderLogMetadataTests.swift
- BitwardenShared/Core/Platform/Services/FlightRecorder.swift
- BitwardenShared/Core/Platform/Services/FlightRecorderTests.swift
- BitwardenShared/UI/Platform/Settings/Settings/About/FlightRecorderLogs/FlightRecorderLogsView.swift
- BitwardenShared/UI/Platform/Settings/Settings/About/FlightRecorderLogs/FlightRecorderLogsViewTests.swift
[PM-19618](https://bitwarden.atlassian.net/browse/PM-19618)
Adds automatic flight recorder log deletion. This handles two cases:
- Turning off the active log at its end date.
- Deleting inactive logs when they reach their expiration date (30 days after logging ended). …
> [PM-19618] Flight recorder automatic log deletion

- BitwardenKit/Core/Platform/Utilities/Mocks/MockBitwardenLogger.swift
- BitwardenShared/Core/Platform/Services/FlightRecorder.swift
- BitwardenShared/UI/Auth/AuthCoordinator.swift
- BitwardenShared/UI/Auth/AuthCoordinatorTests.swift
- BitwardenShared/UI/Platform/Application/AppCoordinator.swift
- BitwardenShared/UI/Platform/Application/NavigatorBuilderModule.swift
- BitwardenShared/UI/Platform/Application/NavigatorBuilderModuleTests.swift
- BitwardenShared/UI/Platform/Application/Utilities/StackNavigator.swift
- BitwardenShared/UI/Platform/Application/Utilities/StackNavigatorTests.swift
- BitwardenShared/UI/Platform/Application/ViewLoggingNavigationController.swift
- BitwardenShared/UI/Platform/Application/ViewLoggingNavigationControllerTests.swift
- BitwardenShared/UI/Platform/Settings/SettingsCoordinator.swift
- BitwardenShared/UI/Platform/Settings/SettingsCoordinatorTests.swift
- BitwardenShared/UI/Platform/Tabs/TabCoordinator.swift
- BitwardenShared/UI/Tools/Generator/GeneratorCoordinator.swift
- BitwardenShared/UI/Tools/Send/Send/SendCoordinator.swift
- BitwardenShared/UI/Vault/ImportLogins/ImportLoginsCoordinator.swift
- BitwardenShared/UI/Vault/ImportLogins/ImportLoginsCoordinatorTests.swift
- BitwardenShared/UI/Vault/Vault/VaultCoordinator.swift
- BitwardenShared/UI/Vault/Vault/VaultCoordinatorTests.swift
- BitwardenShared/UI/Vault/VaultItem/VaultItemCoordinator.swift
- BitwardenShared/UI/Vault/VaultItem/VaultItemCoordinatorTests.swift
- GlobalTestHelpers/MockAppModule.swift
- GlobalTestHelpers/MockStackNavigator.swift
Adds logging for navigation changes to the flight recorder. 
I originally considered adding this logging to the coordinators whenever `navigate(to:)` is called. This only captures forward navigation though (and some dismissals), since navigating back within an existing navigation controller happens outside of the coordinator.
I settled on logging from a `UINavigationController` subclass which can log pushes, pops, presentations, and dismisses. This ends up being fairly easy to inject into the navigation stack, but does rely on using `NavigatorBuilderModule.makeNavigationController()` to build navigation controllers instead of creating `UINavigationController`s directly. Related to this, we had a bunch of places where we were …
> [PM-19577] Log navigation changes to the flight recorder

- BitwardenShared/UI/Tools/Generator/Generator/GeneratorState+UsernameState.swift
https://bitwarden.atlassian.net/browse/PM-16972
For Fastmail, default `website` to empty string instead of `nil`. …
> [PM-16972] Fastmail email alias returning error message

- BitwardenShared/Core/Platform/Models/Enum/FeatureFlag.swift
- BitwardenShared/Core/Platform/Models/Enum/FeatureFlagTests.swift
https://bitwarden.atlassian.net/browse/PM-21650
Enable `isRemotelyConfigured` property for `mobile-error-reporting`. …
> [PM-21650] Enable isRemotelyConfigured for mobile-error-reporting

- Configs/BitwardenKit-Debug.xcconfig
- Configs/BitwardenKit-Release.xcconfig
- project-bwk.yml
https://bitwarden.atlassian.net/browse/PM-21393
`BitwardenKit` was not pulling in `BITWARDEN_FLAGS` to add to compilation flags; this had the effect of making changes in the Debug Menu not actually take effect. This splits BWK's configuration into Release and Debug, like our other targets, and properly brings in the `BITWARDEN_FLAGS`.
- 👍 (`:+1:`) or …
> [PM-21393] fix: Split BitwardenKit configuration into Release and Debug

- BitwardenShareExtension/ShareViewController.swift
- BitwardenShared/UI/Platform/Application/AppCoordinatorTests.swift
- BitwardenShared/UI/Platform/Application/Support/Localizations/en.lproj/Localizable.strings
- BitwardenShared/UI/Tools/Send/Send/SendCoordinator.swift
- BitwardenShared/UI/Tools/Send/Send/SendCoordinatorTests.swift
- BitwardenShared/UI/Tools/Send/Send/SendRoute.swift
- BitwardenShared/UI/Tools/Send/SendItem/AddEditSendItem/AddEditSendItemProcessor.swift
- BitwardenShared/UI/Tools/Send/SendItem/AddEditSendItem/AddEditSendItemProcessorTests.swift
- BitwardenShared/UI/Tools/Send/SendItem/AddEditSendItem/AddEditSendItemState.swift
- BitwardenShared/UI/Tools/Send/SendItem/SendItemCoordinator.swift
- BitwardenShared/UI/Tools/Send/SendItem/SendItemCoordinatorTests.swift
- BitwardenShared/UI/Tools/Send/SendItem/SendItemRoute.swift
- BitwardenShared/UI/Tools/Send/SendItem/ViewSendItem/ViewSendItemAction.swift
- BitwardenShared/UI/Tools/Send/SendItem/ViewSendItem/ViewSendItemEffect.swift
- BitwardenShared/UI/Tools/Send/SendItem/ViewSendItem/ViewSendItemProcessor.swift
- BitwardenShared/UI/Tools/Send/SendItem/ViewSendItem/ViewSendItemProcessorTests.swift
- BitwardenShared/UI/Tools/Send/SendItem/ViewSendItem/ViewSendItemState.swift
- BitwardenShared/UI/Tools/Send/SendItem/ViewSendItem/ViewSendItemView.swift
- BitwardenShared/UI/Tools/Send/SendItem/ViewSendItem/ViewSendItemViewTests.swift
[PM-21125](https://bitwarden.atlassian.net/browse/PM-21125)
Adds the initial setup for navigating to the view item screen. The actual change for navigating to the view send screen hasn't been implemented yet, and will be coming in a future PR.
As part of this, we were passing `hasPremium` as an associated value in the route to the add/edit item screen. This felt overly complex now that we have multiple routes to the add/edit screen. So that has been refactored so the add/edit processor loads that data when the view appears. …
> [PM-21125] Add navigation setup for view send item

- BitwardenShared/UI/Vault/VaultItem/ViewItem/ViewItemAction.swift
- BitwardenShared/UI/Vault/VaultItem/ViewItem/ViewItemActionTests.swift
- BitwardenShared/UI/Vault/VaultItem/ViewItem/ViewItemProcessor.swift
- BitwardenShared/UI/Vault/VaultItem/ViewItem/ViewItemProcessorTests.swift
- BitwardenShared/UI/Vault/VaultItem/ViewItem/ViewItemView.swift
https://bitwarden.atlassian.net/browse/PM-20171
In the `ViewItemView`, create a task reference for `.appeared`. This enables us to cancel it when the view is closed and free the memory.
- 🤔 (`:thinking:`) …
> [PM-20171] Fix ViewItemView retain cycle

- BitwardenShared/Core/Platform/Models/Enum/LanguageOption.swift
- BitwardenShared/UI/Platform/Settings/Settings/About/AboutView.swift
- BitwardenShared/UI/Platform/Settings/Settings/AccountSecurity/AccountSecurityView.swift
- BitwardenShared/UI/Platform/Settings/Settings/Appearance/SelectLanguage/SelectLanguageView.swift
- BitwardenShared/UI/Platform/Settings/Settings/AutoFill/AutoFillView.swift
- BitwardenShared/UI/Platform/Settings/Settings/SettingsListItem.swift
- BitwardenShared/UI/Platform/Settings/Settings/SettingsView.swift
- BitwardenShared/UI/Platform/Settings/Settings/Vault/ExportVault/ExportSettings/ExportSettingsView.swift
- BitwardenShared/UI/Platform/Settings/Settings/Vault/Folders/FoldersView.swift
- BitwardenShared/UI/Platform/Settings/Settings/Vault/VaultSettingsView.swift
[PM-21624](https://bitwarden.atlassian.net/browse/PM-21624)
Removes the divider and `hasDivider` property from `SettingListItem`. Manually specifying the divider is tedious and has mostly been previously replaced by using `ContentBlock` to add the divider between list items. This updates the remaining views within Settings that don't use `ContentBlock`.
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation …
> [PM-21624] Remove divider from SettingListItem

- BitwardenShared/UI/Tools/Send/Send/SendList/SendListView.swift
[PM-21352](https://bitwarden.atlassian.net/browse/PM-21352)
Disables the "New Send" button on the send list empty screen from VoiceOver since the FAB button is also included in VoiceOver and provides the same functionality.
- ❓ …
> [PM-21352] Disable Accessibility VoiceOver for "New Send" Button on Sends Screen

- BitwardenShared/UI/Tools/Send/Send/SendList/SendListItemRowView.swift
- BitwardenShared/UI/Tools/Send/Send/SendList/SendListProcessor.swift
- BitwardenShared/UI/Tools/Send/Send/SendList/SendListProcessorTests.swift
- BitwardenShared/UI/Tools/Send/SendItem/SendItemCoordinator.swift
- BitwardenShared/UI/Tools/Send/SendItem/SendItemCoordinatorTests.swift
- BitwardenShared/UI/Tools/Send/SendItem/SendItemRoute.swift
[PM-21125](https://bitwarden.atlassian.net/browse/PM-21125)
This enables navigation to the view Send view from the Sends list. This also includes an update for navigating to the edit sends view from viewing a send. Edit send is presented on top of view send and tapping the cancel button from edit send should only dismiss the edit send view (without these changes it would dismiss both).
https://github.com/user-attachments/assets/38922319-80c7-44cf-a3ee-0fc237e91442
- Communicated to DevOps any deployment …
> [PM-21125] Enable navigation to view send

- BitwardenShared/Core/Platform/Services/FlightRecorder.swift
- BitwardenShared/Core/Platform/Services/FlightRecorderTests.swift
If appending to the flight recorder log fails, we record an error with the error reporter. Now that the error reporter also logs errors to the flight recorder, there's a potential infinite loop if writing to the log fails. In this case, it doesn't really make sense to continue logging (since the file could be missing or the device is out of storage or some other unrecoverable error), so in order to prevent looping, this deactivates the flight recorder.
https://github.com/bitwarden/ios/pull/1547#discussion_r2078455240 …
> [PM-19577] Deactivate flight recorder if appending to the log fails

- .github/workflows/CI-main.yml
[PM-21825](https://bitwarden.atlassian.net/browse/PM-21825)
The `action: write` permission needs to be set for all jobs calling `build.yml` even when the step that requires it is skipped. 
- 🤔 …
> [PM-21825] Update CI-main.yml permissions

- BitwardenShared/Core/Auth/Repositories/AuthRepository.swift
- BitwardenShared/Core/Auth/Repositories/AuthRepositoryTests.swift
https://bitwarden.atlassian.net/browse/PM-21681
This turns off syncing for a user between PM and BWA when that user logs out of PM. This change will then be picked up by the `AuthenticatorSyncService`, which will do the necessary things to delete data out of the shared storage. …
> [PM-21681] Stop syncing TOTP codes with BWA on PM logout

- BitwardenShared/Core/Auth/Repositories/AuthRepository.swift
- BitwardenShared/Core/Auth/Repositories/AuthRepositoryTests.swift
https://bitwarden.atlassian.net/browse/PM-21681
This is a cherry-pick of https://github.com/bitwarden/ios/pull/1600 to the release branch.
This turns off syncing for a user between PM and BWA when that user logs out of PM. This change will then be picked up by the `AuthenticatorSyncService`, which will do the necessary things to delete data out of the shared storage. …
> [PM-21681] [RC] Stop syncing TOTP codes with BWA on PM logout

- AuthenticatorShared/Core/Platform/Models/Enum/SessionTimeoutValue.swift
- AuthenticatorShared/Core/Platform/Models/Enum/SessionTimeoutValueTests.swift
- AuthenticatorShared/UI/Platform/Application/AppProcessor.swift
- AuthenticatorShared/UI/Platform/Application/AppProcessorTests.swift
- AuthenticatorShared/UI/Platform/Application/Support/Localizations/en.lproj/Localizable.strings
- AuthenticatorShared/UI/Platform/Settings/Settings/SettingsEffect.swift
- AuthenticatorShared/UI/Platform/Settings/Settings/SettingsProcessor.swift
- AuthenticatorShared/UI/Platform/Settings/Settings/SettingsState.swift
- AuthenticatorShared/UI/Platform/Settings/Settings/SettingsView.swift
- AuthenticatorShared/UI/Platform/Settings/Settings/SettingsViewTests.swift
- BitwardenKit/Core/Platform/Models/Enum/SessionTimeoutValue.swift
- BitwardenKit/Core/Platform/Models/Enum/SessionTimeoutValueTests.swift
- BitwardenShared/Core/Auth/Repositories/TestHelpers/MockAuthRepository.swift
- BitwardenShared/Core/Autofill/Services/AutofillCredentialServiceTests.swift
- BitwardenShared/Core/Vault/Services/TestHelpers/MockVaultTimeoutService.swift
- BitwardenShared/UI/Auth/AuthRouterTests.swift
- BitwardenShared/UI/Platform/Settings/Settings/AccountSecurity/AccountSecurityAction.swift
- BitwardenShared/UI/Platform/Settings/Settings/AccountSecurity/AccountSecurityProcessor.swift
- BitwardenShared/UI/Platform/Settings/Settings/AccountSecurity/AccountSecurityProcessorTests.swift
- BitwardenShared/UI/Platform/Settings/Settings/AccountSecurity/AccountSecurityState.swift
- BitwardenShared/UI/Vault/Vault/AutofillList/VaultAutofillListProcessorTests.swift
- BitwardenShared/UI/Vault/Vault/VaultItemSelection/VaultItemSelectionProcessorTests.swift
https://bitwarden.atlassian.net/browse/PM-21681
Because both PM and BWA will need to know each other's session timeout information (particularly, BWA knowing PM), it makes sense for them to have a shared object for tracking it. This pulls that object into `BitwardenKit`, as a separate PR to cut down on noise in future PRs.
Some things are left in the PM and BWA applications. Notably, `allCases` is different between the two currently (as BWA doesn't handle a custom timeout); and localizations are kept separate because we haven't yet decided how to handle localizations in `BitwardenKit` objects. The lack of bringing `Menuable` into `BitwardenKit` similarly is because we haven't yet decided how to handle assets and colors in `BitwardenKit` objects, or I would have brought that over, too.
- …
> [PM-21681] Consolidate SessionTimeout into BitwardenKit

- BitwardenShared/UI/Platform/Application/Support/Localizations/en.lproj/Localizable.strings
- BitwardenShared/UI/Platform/Settings/Settings/About/FlightRecorderLogs/FlightRecorderLogsAction.swift
- BitwardenShared/UI/Platform/Settings/Settings/About/FlightRecorderLogs/FlightRecorderLogsProcessor.swift
- BitwardenShared/UI/Platform/Settings/Settings/About/FlightRecorderLogs/FlightRecorderLogsProcessorTests.swift
- BitwardenShared/UI/Platform/Settings/Settings/About/FlightRecorderLogs/FlightRecorderLogsState.swift
- BitwardenShared/UI/Platform/Settings/Settings/About/FlightRecorderLogs/FlightRecorderLogsView.swift
[PM-20538](https://bitwarden.atlassian.net/browse/PM-20538) - Add delete confirmation for individually deleted logs
[PM-20533](https://bitwarden.atlassian.net/browse/PM-20533) - Add deletion confirmation for logs deleted in bulk
Adds a toast to the flight recorder logs view when a single or all logs have been deleted.
Single log:
https://github.com/user-attachments/assets/bd18b0b5-707d-43c5-a786-355d02ff9e98
All logs:
https://github.com/user-attachments/assets/b8e3f6c3-79a2-4b15-a62f-8f67ada25f8b
- …
> [PM-20538] Display toast on flight recorder log deletion

- BitwardenShared/Core/Platform/Models/Data/FlightRecorderData.swift
- BitwardenShared/Core/Platform/Models/Data/FlightRecorderDataTests.swift
- BitwardenShared/Core/Platform/Services/FlightRecorder.swift
- BitwardenShared/Core/Platform/Services/FlightRecorderTests.swift
- BitwardenShared/Core/Platform/Services/TestHelpers/MockFlightRecorder.swift
- BitwardenShared/Core/Platform/Utilities/DefaultFalse.swift
- BitwardenShared/UI/Vault/Vault/VaultList/VaultListProcessor.swift
- BitwardenShared/UI/Vault/Vault/VaultList/VaultListProcessorTests.swift
[PM-19553](https://bitwarden.atlassian.net/browse/PM-19553)
Previously, the flight recorder banner's dismissal was tracked on a per-user basis. This changes that to track it on an app-wide basis.
- 🤔 …
> [PM-19553] Update flight recorder banner dismissal tracking

- BitwardenShared/UI/Tools/Send/SendItem/ViewSendItem/ViewSendItemView.swift
https://bitwarden.atlassian.net/browse/QA-1170
- Updated any necessary documentation (Confluence, contributing …
> [QA-1170]  Send UI update - Adding missing accessibilityIDs

- Bitwarden/Application/AppIntents/OpenGeneratorIntent.swift
- Bitwarden/Application/AppIntents/ShortcutsProvider.swift
[PM-22347](https://bitwarden.atlassian.net/browse/PM-22347)
Open generator intent error alert was being left behind the app because the intent was automatically opening the Bitwarden app. So this changes the intent to be a `ForegroundContinuableIntent` so it can decide whether to open the app or display the error alert.
This comes with an added step to the user where they need to accept continuing into the app.
- Updated any necessary documentation …
> [PM-22347] Improved Open generator intent error alert behavior

- Bitwarden/Application/AppIntents/OpenGeneratorIntent.swift
[PM-22347](https://bitwarden.atlassian.net/browse/PM-22347)
Fix open generator App Intent so canceling on the alert doesn't set the pending intent. The issue was that cancelling was nonetheless redirecting to generator tab when the user went back to the app.
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for …
> [PM-22347] Fix open generator App Intent on cancel

- AuthenticatorShared/Core/Vault/Services/TestHelpers/BitwardenSdk+VaultMocking.swift
- Bitwarden.xcworkspace/xcshareddata/swiftpm/Package.resolved
- BitwardenShared/Core/Auth/Repositories/AuthRepository.swift
- BitwardenShared/Core/Auth/Repositories/AuthRepositoryTests.swift
- BitwardenShared/Core/Vault/Extensions/BitwardenSdk+Vault.swift
- BitwardenShared/Core/Vault/Extensions/BitwardenSdkVaultTests.swift
- BitwardenShared/Core/Vault/Models/Domain/Fixtures/CipherListView+Fixtures.swift
- BitwardenShared/Core/Vault/Repositories/VaultRepository.swift
- BitwardenShared/Core/Vault/Services/TestHelpers/BitwardenSdk+VaultMocking.swift
- BitwardenShared/UI/Vault/Helpers/VaultItemMoreOptionsHelperTests.swift
- BitwardenShared/UI/Vault/PreviewContent/BitwardenSdk+VaultFixtures.swift
- BitwardenShared/UI/Vault/Vault/AutofillList/VaultAutofillListProcessor+AutofillModeAllTests.swift
- BitwardenShared/UI/Vault/Vault/VaultItemSelection/VaultItemSelectionProcessorTests.swift
- BitwardenShared/UI/Vault/Vault/VaultList/VaultListItemTests.swift
- project-bwa.yml
- project-bwk.yml
- project-pm.yml
[PM-22852](https://bitwarden.atlassian.net/browse/PM-22852)
🍒 Cherry pick from #1686. 
🍒 It also includes #1671 so to update the SDK properly.
Fix master password unlock when entering the first times incorrectly and then correctly to properly unlock the vault when that happens. There was an issue with how the SDK was handling subsequent attempts that when the user entered the first times the password incorrectly then all the next times it will be incorrect event when the user entered the password correctly.
This PR fixes that by updating the SDK with the fixed logic.
- Used …
> [PM-22852] [RC] Fix master password unlock subsequent attempts

- BitwardenShared/UI/Vault/Extensions/Alert+Vault.swift
- BitwardenShared/UI/Vault/Extensions/AlertVaultTests.swift
[PM-22792](https://bitwarden.atlassian.net/browse/PM-22792)
Adds master password reprompt, if enabled, for copying the public key or fingerprint of an SSH key.
https://github.com/user-attachments/assets/f5c7d961-6639-4e58-acdc-09cb1fb0e43c …
> [PM-22792] Add master password reprompt for copying SSH public key and fingerprint

- BitwardenShared/UI/Platform/Application/Extensions/UIViewController.swift
- BitwardenShared/UI/Platform/Application/Utilities/Coordinator.swift
- BitwardenShared/UI/Platform/Application/Utilities/CoordinatorTests.swift
- BitwardenShared/UI/Platform/Application/Utilities/Navigator.swift
- BitwardenShared/UI/Platform/Application/Utilities/StackNavigator.swift
- GlobalTestHelpers/MockRootNavigator.swift
- GlobalTestHelpers/MockTabNavigator.swift
[PM-23087](https://bitwarden.atlassian.net/browse/PM-23087)
The 'Share error details' button on alerts when a generic error occurs presents a share sheet for sharing the details of the error. On iPadOS, presenting the `UIActivityViewController` requires setting the popover presentation controller's source view or it will crash. We have logic to handle this in the StackNavigator's `present(_:)` method, but since this was being presented from the navigator's `rootViewController`, that didn't apply. I ended up moving the present view controller method out of `StackNavigator` and into `Navigator`, which then can be used by all navigators and fixes the crash.
> *** Terminating app due to uncaught exception 'NSGenericException', reason: 'UIPopoverPresentationController …
> [PM-23087] Fix crash presenting 'Share error details' share sheet on iPadOS

- Bitwarden.xcworkspace/xcshareddata/swiftpm/Package.resolved
- project-bwa.yml
- project-bwk.yml
- project-pm.yml
https://bitwarden.atlassian.net/browse/PM-23140
Cherry-pick of [PR 1706](https://github.com/bitwarden/ios/pull/1706) onto `main`
This updates the SDK version to include a fix to handle if a user's credit card number contains the • character (and by extension, other Unicode). That parsing wasn't utilized in earlier versions of the iOS app, and prior to this update, the SDK was throwing an error in the parsing.
- Updated any necessary documentation …
> [PM-23140] 🍒  Update SDK version to get bullet hotfix (#1706)

- .github/workflows/_build-any.yml
PM-18414
Compiler flags are now set. Test run in a different branch, confirmed by QA: https://github.com/bitwarden/ios/actions/runs/16011074192/job/45168843064
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) …
> [PM-18414] Fix compiler flags not being set in new build workflows

- .github/workflows/_build-any.yml
- fastlane/Fastfile
PM-23210
While troubleshooting #1708 I found the following areas where we could improve our CI build times and reliability, cutting 5-10min of execution time per build:
1. Skip waiting for TestFlight to finish processing a build, saves ~5min in general - Per fastlane [source code](https://github.com/fastlane/fastlane/blob/e5dfe9e69f795f06c1420639faafc13fa4761a09/pilot/lib/pilot/build_manager.rb#L67) builds don't need to be fully processed for changelogs to be set, they just need to be visible and fastlane covers that. If we need to know when a build finishes processing we can look into the new TestFlight / AppStoreConnect Webhooks.
2. Skips AppStoreConnect validation, leaving the step in place for troubleshooting if required - build artifacts are stable at this point and this endpoint can …
> [PM-23210] Improve CI build time

- .github/workflows/ci-bwpm.yml
PM-18414
In order for our QA team to test the new Password Manager build workflow we need versions to align with the existing workflow, otherwise they'll clash. 
This will be reverted to the new versioning approach when we're done testing.  …
> [PM-18414] Transition new build workflow back to shared versioning for QA testing

- BitwardenShared/Core/Vault/Repositories/TestHelpers/MockVaultRepository.swift
- BitwardenShared/Core/Vault/Repositories/VaultRepository.swift
- BitwardenShared/Core/Vault/Repositories/VaultRepositoryTests.swift
- BitwardenShared/UI/Vault/Vault/VaultList/VaultListProcessor.swift
- BitwardenShared/UI/Vault/Vault/VaultList/VaultListProcessorTests.swift
[PM-18211](https://bitwarden.atlassian.net/browse/PM-18211)
Currently, `VaultRepository.fetchSync(forceSync:filter:)` returns the list of sections in the vault. When syncing the vault, the sync operation is separate from the database subscription so there isn't a great way to know when to hide the loading indicator on the vault list. By returning the list of sections, we could guarantee that the vault is loaded when the loading indicator is removed. 
However, this ends up loading and processing the vault twice. Instead, we can replace returning the vault list with a check to see if the vault is empty or not. For an empty vault, the database won't publish anything, so the loading indicator can be removed immediately after syncing. Otherwise, we'll wait for the database to publish the vault …
> [PM-18211] Refactor vault list fetch sync to not return vault sections

- BitwardenShared/Core/Platform/Services/KeyConnectorService.swift
- BitwardenShared/Core/Tools/Repositories/SendRepository.swift
- BitwardenShared/Core/Tools/Repositories/SendRepositoryTests.swift
- BitwardenShared/Core/Tools/Repositories/TestHelpers/MockSendRepository.swift
- BitwardenShared/Core/Vault/Repositories/TestHelpers/MockVaultRepository.swift
- BitwardenShared/Core/Vault/Repositories/VaultRepository.swift
- BitwardenShared/Core/Vault/Repositories/VaultRepositoryTests.swift
- BitwardenShared/Core/Vault/Services/SyncService.swift
- BitwardenShared/Core/Vault/Services/SyncServiceTests.swift
- BitwardenShared/Core/Vault/Services/TestHelpers/MockSyncService.swift
- BitwardenShared/UI/Tools/Send/Send/SendList/SendListProcessor.swift
- BitwardenShared/UI/Tools/Send/Send/SendList/SendListProcessorTests.swift
- BitwardenShared/UI/Vault/Vault/VaultGroup/VaultGroupProcessor.swift
- BitwardenShared/UI/Vault/Vault/VaultGroup/VaultGroupProcessorTests.swift
- BitwardenShared/UI/Vault/Vault/VaultList/VaultListProcessor.swift
- BitwardenShared/UI/Vault/Vault/VaultList/VaultListProcessorTests.swift
[PM-24003](https://bitwarden.atlassian.net/browse/PM-24003)
Fixes a bug where the sync was checking that at least 30min has passed on all non-forced syncs.
This has been changed to only do the periodic interval check when app is opened/resumed (vault/send tab appears).
Additionally, improved `KeyConnectorService` logic to short-circuit as soon as possible to not execute unneeded logic.
- Updated any necessary documentation (Confluence, contributing …
> [PM-24003] Fix sync to only have the 30min interval check on app opened/resumed

- BitwardenResources/Localizations/Base.lproj/Localizable.strings
- BitwardenResources/Localizations/en.lproj/Localizable.strings
- BitwardenResources/Resources.swift
- BitwardenShared/UI/Platform/Application/Appearance/UI.swift
- BitwardenShared/UI/Vault/VaultItem/ViewItem/ViewItemDetailsView.swift
- crowdin-pm.yml
- project-bwk.yml
- swiftgen-bwr.yml
https://bitwarden.atlassian.net/browse/PM-23820
Similar to [this PR](https://github.com/bitwarden/android/pull/5550) on the Android side, this copies one string into `BitwardenResources` and updates the appropriate configuration files for SwiftGen, Crowdin, and so on; this will allow us to make sure everything works in Crowdin before moving all of the localizations. …
> [PM-23820] Copy one PM string to BitwardenResources and update Crowdin configuration

- BitwardenShared/Core/Auth/Services/TestHelpers/MockCryptoClient.swift
- BitwardenShared/Core/Platform/Services/AuthenticatorSyncService.swift
- BitwardenShared/Core/Platform/Services/AuthenticatorSyncServiceTests.swift
- BitwardenShared/Core/Platform/Services/ServiceContainer.swift
[PM-23406](https://bitwarden.atlassian.net/browse/PM-23406)
Update to #1750. When authenticator sync is initially enabled, we need to use an unlocked SDK client to create the key if it doesn't already exist. So this brings back the shared `clientService` for this purpose. Once the key is created, ongoing syncing can occur with the separate `authenticatorClientService`. …
> [PM-23406] Fix authenticator sync initial key creation

- BitwardenShared/Core/Platform/Services/AuthenticatorSyncServiceTests.swift
- BitwardenShared/Core/Platform/Services/ClientService.swift
- BitwardenShared/Core/Platform/Services/ClientServiceTests.swift
- BitwardenShared/Core/Vault/Helpers/TestHelpers/MockVaultListPreparedDataBuilder+Extensions.swift
- BitwardenShared/Core/Vault/Helpers/TestHelpers/MockVaultListSectionsBuilder+Extensions.swift
- BitwardenShared/Core/Vault/Helpers/VaultListDirectors/MainVaultListDirectorStrategyTests.swift
- BitwardenShared/Core/Vault/Helpers/VaultListDirectors/MainVaultListGroupDirectorStrategyTests.swift
- BitwardenShared/Core/Vault/Helpers/VaultListPreparedDataBuilder.swift
- BitwardenShared/Core/Vault/Helpers/VaultListSectionsBuilder.swift
- BitwardenShared/Core/Vault/Repositories/VaultRepositoryTests.swift
- BitwardenShared/Core/Vault/Services/ExportVaultServiceTests.swift
- BitwardenShared/Core/Vault/Services/SyncService.swift
- BitwardenShared/UI/Platform/Application/Views/BitwardenMenuField.swift
- Sourcery/Templates/AutoMockable.stencil
[PM-24171](https://bitwarden.atlassian.net/browse/PM-24171)
Improved `AutoMockable.stencil` so it uses short method name by default to generate the mocked properties and added some custom annotations logic to better handle specific cases.
- **useSelectorName**: Add this annotation to a method where you want to use the selector name instead of the short name, e.g. on function overloading.
- **mockReceivedInvocations**: Add this annotation to a method where you want to mock the different received parameters invocations to a method.
- Used internationalization (i18n) for all UI …
> [PM-24171] [BEEEP] Improved AutoMockable stencil to use short method name

- BitwardenShared/Core/Platform/Models/Enum/FeatureFlag.swift
- BitwardenShared/Core/Platform/Models/Enum/FeatureFlagTests.swift
- BitwardenShared/UI/Tools/Generator/Generator/GeneratorProcessor.swift
- BitwardenShared/UI/Tools/Generator/Generator/GeneratorProcessorTests.swift
- BitwardenShared/UI/Tools/Generator/Generator/GeneratorState+UsernameState.swift
- BitwardenShared/UI/Tools/Generator/Generator/GeneratorState.swift
- BitwardenShared/UI/Tools/Generator/Generator/GeneratorStateTests.swift
[PM-24139](https://bitwarden.atlassian.net/browse/PM-24139)
Removes the `simple-login-self-host-alias` feature flag. …
> [PM-24139] Remove simple-login-self-host-alias feature flag

- AuthenticatorShared/UI/DebugMenu/DebugMenuProcessorTests.swift
- AuthenticatorShared/UI/DebugMenu/DebugMenuViewTests.swift
- BitwardenKit/Core/Platform/Models/Domain/FeatureFlag.swift
- BitwardenKit/Core/Platform/Models/Domain/FeatureFlagTests.swift
- BitwardenKit/Core/Platform/Models/Domain/Mocks/TestFeatureFlags.swift
- BitwardenKit/Core/Platform/Services/API/Fixtures/ValidServerConfig.json
- BitwardenKit/Core/Platform/Services/ConfigService.swift
- BitwardenKit/Core/Platform/Services/ConfigServiceTests.swift
- BitwardenShared/Core/Platform/Models/Enum/FeatureFlag.swift
- BitwardenShared/Core/Platform/Models/Enum/FeatureFlagTests.swift
- BitwardenShared/UI/Platform/DebugMenu/DebugMenuProcessorTests.swift
- BitwardenShared/UI/Platform/DebugMenu/DebugMenuViewTests.swift
[PM-22873](https://bitwarden.atlassian.net/browse/PM-22873)
Removes the `isRemotelyConfigured` flag for feature flags in favor of version targeting.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more …
> [PM-22873] Remove isRemotelyConfigured for feature flags

- BitwardenShared/Core/Platform/Models/Enum/FeatureFlag.swift
- BitwardenShared/UI/Vault/VaultItem/AddEditItem/AddEditItemProcessor.swift
- BitwardenShared/UI/Vault/VaultItem/AddEditItem/AddEditItemProcessorTests.swift
- BitwardenShared/UI/Vault/VaultItem/AddEditItem/AddEditItemState.swift
- BitwardenShared/UI/Vault/VaultItem/CipherItemState.swift
- BitwardenShared/UI/Vault/VaultItem/CipherItemStateTests.swift
- BitwardenShared/UI/Vault/VaultItem/ViewItem/ViewItemProcessor.swift
- BitwardenShared/UI/Vault/VaultItem/ViewItem/ViewItemProcessorTests.swift
- BitwardenShared/UI/Vault/VaultItem/ViewItem/ViewItemState.swift
- BitwardenShared/UI/Vault/VaultItem/ViewItem/ViewItemStateTests.swift
[PM-24246](https://bitwarden.atlassian.net/browse/PM-24246)
Removes the `pm-15493-restrict-item-deletion-to-can-manage-permission` feature flag …
> [PM-24246] Remove restrict-item-deletion-to-can-manage-permission feature flag

- BitwardenShared/UI/Tools/Generator/Generator/GeneratorState+UsernameState.swift
- BitwardenShared/UI/Tools/Generator/Generator/GeneratorStateTests.swift
[PM-24116](https://bitwarden.atlassian.net/browse/PM-24116)
In the generator, when generating a catch-all username, display the placeholder (-) until a non-empty domain has been entered.
| <img width="557" height="1063" alt="Screenshot 2025-07-29 at 2 38 47 PM" src="https://github.com/user-attachments/assets/154dd03c-eb12-4cd8-9e75-b525944ce7f7" /> | <img width="557" height="1063" alt="Screenshot 2025-07-29 at 2 48 52 PM" src="https://github.com/user-attachments/assets/cf0b838a-4907-466c-a0e0-64df127f671b" /> | 
- Used …
> [PM-24116] Show placeholder hyphen when generating catch-all username with an empty domain

- .github/workflows/github-release.yml
PM-24564
Fix action not being found by doing the repo checkout first. While at it, fixed run logs not showing values for some variables.   …
> [PM-24564] fix: action not found in GitHub Release creation workflow

- BitwardenShared/Core/Vault/Helpers/CipherMatchingHelper+SingularMatchTests.swift
[PM-23728](https://bitwarden.atlassian.net/browse/PM-23728)
Fix flaky test on CipherMatchingHelper because of comparing  an array with results of an internal usage of Set that doesn't order items.
- 🤔 …
> [PM-23728] Fix flaky test on CipherMatchingHelper

- BitwardenShared/UI/Platform/Application/Appearance/Styles/CircleMenuStyle.swift
- BitwardenShared/UI/Platform/Application/Appearance/Styles/PrimaryMenuStyle.swift
- BitwardenShared/UI/Platform/Application/Views/FloatingActionMenu.swift
- BitwardenShared/UI/Tools/Send/Send/SendList/SendListView.swift
- BitwardenShared/UI/Vault/VaultItem/ViewItem/ViewItemState.swift
[PM-23632](https://bitwarden.atlassian.net/browse/PM-23632)
When we updated some FABs to show a menu, it seemed that a `Menu` could be styled with a `ButtonStyle` instead of a `MenuStyle`. This is convenient for the menu buttons that we use on a few screens, but this doesn't appear to work correctly on iOS 15 or 16. So this introduces two `MenuStyle`s that appear similar to existing `ButtonStyle`s that can be used to style these menu button's correctly.
This affects the following menus:
- Vault list FAB menu
- Send list FAB menu
- Send list empty state menu button
Closes #1735 
Vault list:
| <img width="565" height="1068" alt="Screenshot 2025-08-11 at 4 40 22 PM" src="https://github.com/user-attachments/assets/f62364e4-164a-46d0-8418-8644103f2bf5" /> …
> [PM-23632] Fix style of menu buttons on iOS 15 and 16

- BitwardenShared/UI/Platform/Settings/Settings/Vault/ExportVault/ExportVaultToFile/ExportVaultProcessor.swift
- BitwardenShared/UI/Platform/Settings/Settings/Vault/ExportVault/ExportVaultToFile/ExportVaultProcessorTests.swift
- BitwardenShared/UI/Platform/Settings/SettingsCoordinator.swift
- BitwardenShared/UI/Tools/ExportCXF/ExportCXF/ExportCXFProcessor.swift
- BitwardenShared/UI/Tools/ExportCXF/ExportCXF/ExportCXFProcessorTests.swift
- BitwardenShared/UI/Tools/ExportCXF/ExportCXFCoordinator.swift
[PM-24322](https://bitwarden.atlassian.net/browse/PM-24322)
Logs a `EventType.userClientExportedVault (1007)` event when the user exports a vault.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more …
> [PM-24322] Add event log when exporting individual vaults

- .github/workflows/ci-bwa.yml
- .github/workflows/ci-bwpm.yml
Fix CI new manual builds to pass the Xcode version to _build-any.yml so we can use Xcode beta version to build the apps.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite …
> Fix CI new manual builds to pass the Xcode version

- AuthenticatorShared/UI/Platform/Application/Appearance/UI.swift
- AuthenticatorShared/UI/Platform/Settings/Settings/SettingsView.swift
- AuthenticatorShared/UI/Vault/ItemList/ItemList/ItemListView.swift
https://bitwarden.atlassian.net/browse/PM-24131
This removes the background color from the toolbar in iOS 26, which avoids issues with text disappearing because iOS 26 toolbars no longer should have background colors.
- ❓ (`:question:`) …
> [PM-24131] Adjust BWA navigation bar for iOS 26

- BitwardenAutoFillExtension/CredentialProviderViewController.swift
- BitwardenShared/UI/Platform/Application/AppProcessor.swift
- BitwardenShared/UI/Platform/Application/AppProcessorTests.swift
[PM-24715](https://bitwarden.atlassian.net/browse/PM-24715)
🍒 Same change as in RC fix #1858 
Fix iOS autofill extension app initialization to load environment URLs and config when going through the flows without user interaction. This was causing the app to logout when session timeout was set to Never, Region not set to US and doing any API calls in the flows; like in certain Fido2 autofill scenarios. So instead of performing the API call to the correct server it was defaulting to US, returning a 401 and then when refreshing a 400 with `invalid_grant` logging out the user.
Additionally, needed to change the flows without user interaction be async so we can load the URLs and config correctly.
- …
> [PM-24715] Fix iOS autofill extension app initialization URLs

- BitwardenKit/Core/Platform/Utilities/OSLogErrorReporter.swift
- Scripts/build.sh
[PM-23543](https://bitwarden.atlassian.net/browse/PM-23543)
Added Swift active compilation condition flag `DISABLE_ASSERTION_FAILURE_ON_ERROR` that can be used to disable assertion failure on DEBUG error reporter logging. This has been set in place in the Simulator mode builds on CI so QA Automation doesn't crash when an error is thrown to the log reporter. …
> [PM-23543] debt: Ignore assertion failure on DEBUG when CI building for Simulator

- Bitwarden.xcworkspace/xcshareddata/swiftpm/Package.resolved
- project-bwa.yml
https://bitwarden.atlassian.net/browse/PM-25246
This fixes build failures with BWA that were caused because homebrew always grabs the latest version of protobuf (which right now is 1.31) but we were still using 1.29, and the two versions are incompatible, per [this issue on the swift-protobuf repo](https://github.com/apple/swift-protobuf/issues/1830). This therefore updates our version to 1.31. …
> [PM-25246] Update protobuf version to 1.31.0

- BitwardenKit/Core/Platform/Utilities/OSLogErrorReporter.swift
- Scripts/build.sh
PM-23543
Reverting #1843 as it's causing problems with the Simulator CI build
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially …
> [PM-23543] Revert: Added Swift active compilation condition flag DISABLE_ASSERTION_FAILURE_ON_ERROR

- BitwardenShared/Core/Auth/Repositories/AuthRepository.swift
- BitwardenShared/Core/Auth/Repositories/AuthRepositoryTests.swift
- BitwardenShared/Core/Platform/Models/Enum/FeatureFlag.swift
- BitwardenShared/Core/Platform/Services/ServiceContainer.swift
- BitwardenShared/Core/Platform/Services/StateService.swift
- BitwardenShared/Core/Platform/Services/StateServiceTests.swift
- BitwardenShared/Core/Platform/Services/Stores/AppSettingsStore.swift
- BitwardenShared/Core/Platform/Services/Stores/AppSettingsStoreTests.swift
- BitwardenShared/Core/Platform/Services/Stores/TestHelpers/MockAppSettingsStore.swift
- BitwardenShared/Core/Platform/Services/TestHelpers/MockStateService.swift
- BitwardenShared/Core/Vault/Services/VaultTimeoutService.swift
- BitwardenShared/Core/Vault/Services/VaultTimeoutServiceTests.swift
[PM-23289](https://bitwarden.atlassian.net/browse/PM-23289)
> [!NOTE]
> This depends on https://github.com/bitwarden/sdk-internal/pull/372
Migrates any existing pin keys to a pin protected user key envelope. Existing pins will be migrated when the vault is unlocked. And any new pins will use a pin protected user key envelope on creation.
- 👍 (`:+1:`) …
> [PM-23289] Migrate PIN unlock keys to PinProtectedUserKeyEnvelope

- BitwardenKit/Core/Platform/Extensions/String+Extensions.swift
- BitwardenKit/Core/Platform/Extensions/StringExtensionsTests.swift
- BitwardenKit/Core/Platform/Extensions/URL.swift
- BitwardenKit/Core/Platform/Extensions/URLTests.swift
- BitwardenKit/Core/Platform/Services/API/Extensions/JSONDecoder+Bitwarden.swift
- BitwardenKit/Core/Platform/Services/API/Extensions/JSONDecoderBitwardenTests.swift
- BitwardenKit/Core/Platform/Utilities/URLFixingJSONDecoder.swift
- BitwardenKit/Core/Platform/Utilities/URLFixingJSONDecoderTests.swift
- BitwardenShared/Core/Platform/Extensions/URL.swift
[PM-25284](https://bitwarden.atlassian.net/browse/PM-25284)
Fix CXP JSON decoder so it takes into consideration URIs where it has no scheme, are IP addresses and have a port. This was causing the URL(string:) initializer to return `nil` and breaking the decoding process. This fixes it by prefixing `http://` or `https://` accordingly depending on if it's an IP address or a different type of URI that can't be converted to `URL` directly.
Example of URL that was causing problems: `192.168.0.1:8080`.
> [!NOTE]
> A new decoder was added that can configure property names that are array of URLs to be taken into account for the fix. This will check whether the URL is an IP address and add the `http://` prefix to it so it's able to be automatically decoded to `URL` without problems.
- Contributor …
> [PM-25284] Fix invalid URL on CXP flow when URL is IP address with port

- BitwardenShared/UI/Auth/Landing/LandingView.swift
[PM-25140](https://bitwarden.atlassian.net/browse/PM-25140)
Prior to iOS 26, we relied on the fact that an empty view was enough to hide a toolbar button in the toolbar. However, iOS 26 shows the shadow for a button even if there's nothing in the button. This hides the profile switcher button completely if there's no accounts to show.
| <img width="568" height="1084" alt="Screenshot 2025-09-05 at 4 09 07 PM" src="https://github.com/user-attachments/assets/b873b040-6487-47de-a41f-232467cfa140" /> | <img width="568" height="1084" alt="Screenshot 2025-09-05 at 4 00 00 PM" src="https://github.com/user-attachments/assets/7f49d8a5-c6b8-4844-9f81-9e1582b611e6" /> | 
- …
> [PM-25140] LandingView: hide account switcher toolbar button if no accounts

- BitwardenShared/UI/Vault/VaultItem/AddEditItem/AddEditItemState.swift
- BitwardenShared/UI/Vault/VaultItem/AddEditItem/AddEditItemView.swift
- BitwardenShared/UI/Vault/VaultItem/CipherItemState.swift
- BitwardenShared/UI/Vault/VaultItem/CipherItemStateTests.swift
- BitwardenShared/UI/Vault/VaultItem/ViewItem/ViewItemProcessor.swift
- BitwardenShared/UI/Vault/VaultItem/ViewItem/ViewItemProcessorTests.swift
- BitwardenShared/UI/Vault/VaultItem/ViewItem/ViewItemView.swift
[PM-25449](https://bitwarden.atlassian.net/browse/PM-25449)
Removes the "Move to Organization" and "Collection" menu options when viewing or editing a cipher if the user doesn't belong to an organization. Also, the "Collection" menu option is hidden until the cipher has been moved into an organization.
User not in organization:
| View | Edit |
| <img width="557" height="1063" alt="Screenshot 2025-09-08 at 1 47 14 PM" src="https://github.com/user-attachments/assets/e1b118e3-93c5-4d8f-ab8c-41d46613456f" /> | <img width="557" height="1063" alt="Screenshot 2025-09-08 at 1 48 04 PM" src="https://github.com/user-attachments/assets/f990a1ce-9c5e-47b4-a7e5-70a1836f8cf6" /> | 
User in organization, item in personal vault:
| View | Edit |
| <img width="557" …
> [PM-25449] Update view/edit cipher menu options for users not in an organization

- BitwardenShared/UI/Platform/Settings/Settings/AutoFill/AutoFillProcessor.swift
- BitwardenShared/UI/Platform/Settings/Settings/AutoFill/AutoFillProcessorTests.swift
- BitwardenShared/UI/Vault/VaultItem/AddEditItem/AddEditItemProcessor.swift
- BitwardenShared/UI/Vault/VaultItem/AddEditItem/AddEditItemProcessorTests.swift
https://bitwarden.atlassian.net/browse/PM-25540
The learn more dialog has (advanced) appended to the Math detection type name. This uses strings without the advanced part for that modal.
- 🤔 (`:thinking:`) …
> [PM-25540] Removed advanced text from learn more modals on URI Match detection

- BitwardenShared/Core/Vault/Models/Response/DeleteAttachmentResponse.swift
- BitwardenShared/Core/Vault/Services/API/Cipher/CipherAPIService.swift
- BitwardenShared/Core/Vault/Services/API/Cipher/CipherAPIServiceTests.swift
- BitwardenShared/Core/Vault/Services/API/Cipher/Requests/DeleteAttachmentRequest.swift
- BitwardenShared/Core/Vault/Services/API/Fixtures/APITestData+Vault.swift
- BitwardenShared/Core/Vault/Services/API/Fixtures/deleteAttachment.json
- BitwardenShared/Core/Vault/Services/CipherService.swift
- BitwardenShared/Core/Vault/Services/CipherServiceTests.swift
- BitwardenShared/UI/Vault/VaultItem/ViewItem/ViewLoginItem/Extensions/Cipher+Update.swift
[PM-24371](https://bitwarden.atlassian.net/browse/PM-24371)
A follow-up to https://github.com/bitwarden/ios/pull/1930.
Deleting an attachment updates the revision date on the cipher. This revision date is returned from the `DELETE /ciphers/<cipher-id>/attachment/<attachment-id>` response. We weren't previously parsing this response. This updates that to get the cipher's revision date and update the cipher in the local database. …
> [PM-24371] Fix cipher out-of-date error when deleting an attachment

- AuthenticatorShared/UI/Platform/Application/AppProcessor.swift
- AuthenticatorShared/UI/Platform/Application/AppProcessorTests.swift
[PM-26071](https://bitwarden.atlassian.net/browse/PM-26071)
Fix BWA AppProcessor tests race conditions because of notification center subscriptions by adding a check to see that the task for the notifications subscription has run and also fixed to use the time provider mock present time instead of `.now`.
- 📝 …
> [PM-26071] Fix BWA AppProcessor tests race condition

- AuthenticatorShared/UI/Platform/Application/AppProcessor.swift
- AuthenticatorShared/UI/Platform/Application/AppProcessorTests.swift
[PM-26071](https://bitwarden.atlassian.net/browse/PM-26071)
🍒 Cherry picked from #1968 
Fix BWA AppProcessor tests race conditions because of notification center subscriptions by adding a check to see that the task for the notifications subscription has run and also fixed to use the time provider mock present time instead of `.now`.
- 👍 (`:+1:`) or …
> [PM-26071] [RC] Fix BWA AppProcessor tests race condition

- project-bwa.yml
- project-bwk.yml
- project-pm.yml
https://bitwarden.atlassian.net/browse/PM-26158
This adjusts our explicit dependency graph in our project YML files to avoid a warning that was appearing in the test logs. …
> [PM-26158] Fix AuthenticatorBridgeKit dependency warning

- fastlane/Fastfile
PM-26160
Workaround for Xcode 26 altool's bug where the app ID isn't correctly set. Ongoing discussions:
* https://github.com/fastlane/fastlane/issues/29698
* https://github.com/fastlane/fastlane/discussions/29680
Test runs:
* https://github.com/bitwarden/ios/actions/runs/17984184711
* https://github.com/bitwarden/ios/actions/runs/17984607941
- 👍 …
> [PM-26160] Fix xcode 26 TestFlight upload failures

- BitwardenShared/UI/Auth/ProfileSwitcher/ProfileSwitcherToolbarView.swift
- BitwardenShared/UI/Platform/Application/Extensions/View+Backport.swift
[PM-25567](https://bitwarden.atlassian.net/browse/PM-25567)
Updates the profile switcher toolbar button to be the full circle on iOS 26+.
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry …
> [PM-25567] Update profile switcher toolbar button to full circle

- BitwardenShared/Core/Auth/Repositories/AuthRepository.swift
- BitwardenShared/Core/Auth/Repositories/AuthRepositoryTests.swift
- BitwardenShared/Core/Auth/Services/TestHelpers/MockCryptoClient.swift
[PM-25651](https://bitwarden.atlassian.net/browse/PM-25651)
Updates our usages of `CryptoClient` `updatePassword` to `makeUpdatePassword`.  …
> [PM-25651] Update CryptoClient updatePassword references to makeUpdatePassword

- BitwardenShared/Core/Platform/Services/API/APIService.swift
- BitwardenShared/Core/Platform/Services/API/RefreshableAPIService.swift
- BitwardenShared/Core/Platform/Services/API/RefreshableAPIServiceTests.swift
- BitwardenShared/Core/Platform/Services/API/TestHelpers/MockAccountTokenProvider.swift
- BitwardenShared/Core/Platform/Services/NotificationService.swift
- BitwardenShared/Core/Platform/Services/NotificationServiceTests.swift
- BitwardenShared/Core/Platform/Services/ServiceContainer.swift
[PM-25992](https://bitwarden.atlassian.net/browse/PM-25992)
Fix to refresh the access token when a `.syncOrgKeys` notification is received so if token claims change the app doesn't throw errors on certain operations.
This fixes an issue where the user is already signed in the app, then it gets invited and confirmed into an organization. So then after a sync the user sees new collections (like the default user collection if configured), and if they want to create a login using one of such collections in that organization the API will fail because the token wasn't refresh. With this fix, the API succeeds.
- Protected functional changes with …
> [PM-25992] Fix to refresh the access token on syncOrgKeys notification
